import {
  CompanyProfile,
  PartRequest,
  ProcurementOrder,
  ShipmentTracking,
  PaymentTransaction,
  PortalDocument,
  TeamMember,
  NotificationItem,
} from '@/types';

export const INITIAL_COMPANY_PROFILE: CompanyProfile = {
  id: 'acc_autocare_auckland',
  legalBusinessName: 'AutoCare Auckland Limited',
  tradingName: 'AutoCare Auckland',
  nzbn: '9429041234567',
  businessType: 'Independent Service Centre & Trade Repairer',
  website: 'autocareauckland.co.nz',
  branchCount: 3,
  gstNumber: '128-492-910',
  creditLimitNZD: 50000,
  creditStatus: 'Approved Trade Account (20th Month Following)',
  contacts: {
    primary: {
      name: 'James Wilson',
      email: 'james@example.com',
      phone: '021 555 8921',
      role: 'Administrator',
    },
    accounts: {
      name: 'Sarah Jenkins',
      email: 'accounts@autocareauckland.co.nz',
      phone: '09 525 6810',
    },
    delivery: {
      name: 'Workshop Parts Team',
      phone: '09 525 1100',
    },
  },
  billingAddress: {
    businessName: 'AutoCare Auckland Ltd',
    street: '12 Example Street',
    suburb: 'Penrose',
    city: 'Auckland',
    postcode: '1061',
    country: 'New Zealand',
    hasForklift: true,
    hasLoadingDock: true,
    deliveryNotes: 'Accounts payable: accounts@autocareauckland.co.nz',
  },
  deliveryAddresses: [
    {
      id: 'addr_1',
      businessName: 'Auckland Branch (Main Workshop)',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      country: 'New Zealand',
      isDefault: true,
      hasForklift: true,
      hasLoadingDock: true,
      deliveryNotes: 'Deliver to goods inwards roller door. Ring bell for Parts Counter.',
    },
    {
      id: 'addr_2',
      businessName: 'North Shore Service Hub',
      street: '88 Bush Road',
      suburb: 'Rosedale',
      city: 'Auckland',
      postcode: '0632',
      country: 'New Zealand',
      isDefault: false,
      hasForklift: true,
      hasLoadingDock: false,
      deliveryNotes: 'Bay 3 reception. Opening hours: 7:30 AM - 5:00 PM.',
    },
    {
      id: 'addr_3',
      businessName: 'Manukau Fleet Facility',
      street: '14 Cavendish Drive',
      suburb: 'Manukau',
      city: 'Auckland',
      postcode: '2104',
      country: 'New Zealand',
      isDefault: false,
      hasForklift: true,
      hasLoadingDock: true,
      deliveryNotes: 'Heavy vehicle hoist bay. Loading dock accessible.',
    },
  ],
  memberSince: 'August 2021',
};

// Legacy export alias
export const INITIAL_TRADE_ACCOUNT = INITIAL_COMPANY_PROFILE;

export const INITIAL_REQUESTS: PartRequest[] = [
  // 1. Primary Highlight Request: AH-P-000123 (Toyota Hiace 2019) - Quote Ready / Awaiting Payment
  {
    id: 'req_123',
    referenceNumber: 'AH-P-000123',
    title: 'Left Front Lower Control Arm',
    createdAt: '2026-08-28T08:30:00Z',
    updatedAt: '2026-08-28T10:42:00Z',
    status: 'Quote Ready',
    urgency: 'Urgent',
    vehicle: {
      vin: 'JTEBR32P10029384',
      year: 2019,
      make: 'Toyota',
      model: 'Hiace',
      regoNumber: 'KMR892',
      subModel: 'ZX Grand Cabin 3.0L Diesel',
      engineCode: '1KD-FTV',
      chassisCode: 'KDH201',
      transmission: 'Automatic',
      driveConfiguration: 'RWD',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_123',
        name: 'Left Front Lower Control Arm',
        partNumber: '48069-26150',
        category: 'Steering & Suspension',
        quantity: 1,
        qualityPreference: 'Genuine OEM',
        conditionPreference: 'New Only',
        conditionRequired: 'New OEM',
        vehicleSide: 'Left (Passenger)',
        description: 'Complete lower control arm assembly with factory rubber bushings and lower ball joint.',
        damagePhotos: [
          'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=400&q=80',
        ],
      },
    ],
    selectedFreight: 'Air Freight',
    quoteOptions: [
      {
        id: 'q_123_air',
        type: 'air',
        name: 'Air Freight',
        carrierName: 'Air New Zealand Cargo Flight NZ90',
        transitDays: '5–8 business days',
        estimatedDeliveryDate: '2026-09-04',
        partCostNZD: 350.0,
        freightCostNZD: 85.0,
        procurementServiceNZD: 50.0,
        dutiesAndBiosecurityNZD: 0,
        gstNZD: 0,
        localCourierNZD: 0,
        totalLandedCostNZD: 485.0,
        isRecommended: true,
        notes: 'Priority Air Freight Direct to Auckland Airport with Green-Lane MPI clearance.',
      },
      {
        id: 'q_123_sea',
        type: 'sea',
        name: 'Sea Freight',
        carrierName: 'Autohub Dedicated Consolidated Vessel',
        transitDays: '18–30 business days',
        estimatedDeliveryDate: '2026-09-24',
        partCostNZD: 350.0,
        freightCostNZD: 35.0,
        procurementServiceNZD: 25.0,
        dutiesAndBiosecurityNZD: 0,
        gstNZD: 0,
        localCourierNZD: 0,
        totalLandedCostNZD: 410.0,
        isRecommended: false,
        notes: 'Consolidated sea container arriving at Ports of Auckland.',
      },
    ],
    assignedSpecialist: {
      name: 'Brendon Davies',
      role: 'Senior Sourcing & Logistics Specialist',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      directPhone: '09 525 6814',
      email: 'brendon.d@autohub.co.nz',
    },
    trackingMilestones: [
      {
        id: 'm_123_1',
        title: 'Request Submitted & Catalogued',
        location: 'AutoCare Auckland Portal',
        timestamp: '28 Aug · 08:30 AM',
        status: 'completed',
        description: 'Chassis VIN JTEBR32P10029384 verified in Toyota Japan EPC database.',
      },
      {
        id: 'm_123_2',
        title: 'Sourcing & Supplier Inspection',
        location: 'Tokyo Toyota Parts Distribution Centre, JP',
        timestamp: '28 Aug · 09:15 AM',
        status: 'completed',
        description: 'Genuine OEM Part # 48069-26150 located in central warehouse stock.',
      },
      {
        id: 'm_123_3',
        title: 'Quote Ready for Review',
        location: 'Autohub Auckland Desk',
        timestamp: '28 Aug · 10:42 AM',
        status: 'completed',
        description: 'NZ$485.00 Air Freight and NZ$410.00 Sea Freight quotations prepared.',
      },
    ],
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      country: 'New Zealand',
      hasForklift: true,
      hasLoadingDock: true,
      deliveryNotes: 'Ask for James Wilson at parts desk.',
    },
    messages: [
      {
        id: 'msg_123_1',
        sender: 'user',
        senderName: 'James Wilson',
        timestamp: '28 Aug · 09:05 AM',
        text: 'Can you confirm whether this is genuine OEM?',
      },
      {
        id: 'msg_123_2',
        sender: 'specialist',
        senderName: 'Brendon Davies (Autohub)',
        timestamp: '28 Aug · 10:40 AM',
        text: 'Yes. We’ve confirmed the quoted component is genuine Toyota OEM in factory packaging.',
      },
    ],
    paymentStatus: 'Awaiting Payment',
  },

  // 2. Action Required 2: AH-P-000119 (Mazda CX-5 2021) - Payment Failed
  {
    id: 'req_119',
    referenceNumber: 'AH-P-000119',
    title: 'Front Headlamp (LED Projector RHS)',
    createdAt: '2026-08-27T10:15:00Z',
    updatedAt: '2026-08-28T09:10:00Z',
    status: 'Payment Failed',
    urgency: 'Urgent',
    vehicle: {
      vin: 'JM7KF2W7A00192837',
      year: 2021,
      make: 'Mazda',
      model: 'CX-5',
      regoNumber: 'MZD521',
      subModel: 'GSX 2.5L AWD',
      engineCode: 'PY-VPS',
      chassisCode: 'KF2W',
      transmission: 'Automatic',
      driveConfiguration: 'AWD',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_119',
        name: 'Front Headlamp (LED Projector RHS)',
        partNumber: 'KB8A-51-031',
        category: 'Headlights, Tail Lights & Lighting',
        quantity: 1,
        qualityPreference: 'Genuine OEM',
        conditionRequired: 'New OEM',
        vehicleSide: 'Right (Driver)',
      },
    ],
    quoteOptions: [
      {
        id: 'q_119_air',
        type: 'air',
        name: 'Air Freight',
        carrierName: 'Air NZ Cargo Flight NZ90',
        transitDays: '5–8 business days',
        estimatedDeliveryDate: '2026-09-03',
        partCostNZD: 520.0,
        freightCostNZD: 80.0,
        procurementServiceNZD: 50.0,
        dutiesAndBiosecurityNZD: 0,
        gstNZD: 0,
        localCourierNZD: 0,
        totalLandedCostNZD: 650.0,
        isRecommended: true,
      },
    ],
    approvedQuoteId: 'q_119_air',
    assignedSpecialist: {
      name: 'Kenji Takahashi',
      role: 'Japanese Procurement Specialist',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      directPhone: '+81 45 680 9182',
      email: 'kenji.t@autohub.co.jp',
    },
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    paymentStatus: 'Payment Failed',
  },

  // 3. In Transit: AH-P-000121 (Ford Ranger 2020) - $720
  {
    id: 'req_121',
    referenceNumber: 'AH-P-000121',
    title: 'Door Mirror (RHS Power Folding with Camera)',
    createdAt: '2026-08-25T08:30:00Z',
    updatedAt: '2026-08-28T09:15:00Z',
    status: 'In Transit',
    urgency: 'Standard',
    vehicle: {
      vin: 'MNAEY0FF8NW601934',
      year: 2020,
      make: 'Ford',
      model: 'Ranger',
      regoNumber: 'FRD720',
      subModel: 'Wildtrak 3.2L 4x4',
      engineCode: 'P5AT',
      chassisCode: 'PX3',
      transmission: 'Automatic',
      driveConfiguration: '4WD',
      originMarket: 'Australia',
    },
    parts: [
      {
        id: 'p_121',
        name: 'Door Mirror (RHS Power Folding)',
        partNumber: 'EB3B-17682-BD',
        category: 'Body Panels & Structural Panels',
        quantity: 1,
        qualityPreference: 'Genuine OEM',
        conditionRequired: 'New OEM',
        vehicleSide: 'Right (Driver)',
      },
    ],
    quoteOptions: [
      {
        id: 'q_121_air',
        type: 'air',
        name: 'Air Freight',
        carrierName: 'Qantas Freight Trans-Tasman',
        transitDays: '3–5 business days',
        estimatedDeliveryDate: '2026-09-01',
        partCostNZD: 580.0,
        freightCostNZD: 90.0,
        procurementServiceNZD: 50.0,
        dutiesAndBiosecurityNZD: 0,
        gstNZD: 0,
        localCourierNZD: 0,
        totalLandedCostNZD: 720.0,
        isRecommended: true,
      },
    ],
    approvedQuoteId: 'q_121_air',
    assignedSpecialist: {
      name: 'Sarah Chen',
      role: 'Trans-Tasman Procurement Lead',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
      directPhone: '09 525 6822',
      email: 'sarah.c@autohub.co.nz',
    },
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    paymentStatus: 'Payment Received',
  },

  // 4. Sourcing: AH-P-000122 (Mazda CX-5 2021)
  {
    id: 'req_122',
    referenceNumber: 'AH-P-000122',
    title: 'Headlamp (LHS LED Assembly)',
    createdAt: '2026-08-27T14:00:00Z',
    updatedAt: '2026-08-28T04:20:00Z',
    status: 'Sourcing',
    urgency: 'Standard',
    vehicle: {
      vin: 'JM7KF2W7A00192837',
      year: 2021,
      make: 'Mazda',
      model: 'CX-5',
      regoNumber: 'MZD521',
      subModel: 'GSX 2.5L AWD',
      engineCode: 'PY-VPS',
      chassisCode: 'KF2W',
      transmission: 'Automatic',
      driveConfiguration: 'AWD',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_122',
        name: 'Headlamp (LHS LED Assembly)',
        partNumber: 'KB8A-51-041',
        category: 'Headlights, Tail Lights & Lighting',
        quantity: 1,
        qualityPreference: 'Genuine OEM',
        conditionRequired: 'New OEM',
        vehicleSide: 'Left (Passenger)',
      },
    ],
    assignedSpecialist: {
      name: 'Kenji Takahashi',
      role: 'Japanese Procurement Specialist',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      directPhone: '+81 45 680 9182',
      email: 'kenji.t@autohub.co.jp',
    },
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },

  // 5. In Procurement: AH-P-000120 (Honda Civic Type-R 2021)
  {
    id: 'req_120',
    referenceNumber: 'AH-P-000120',
    title: 'Electric Power Steering Rack & Pinion Assembly',
    createdAt: '2026-08-23T09:30:00Z',
    updatedAt: '2026-08-28T09:20:00Z',
    status: 'Ordered From Supplier',
    urgency: 'Standard',
    vehicle: {
      vin: 'JHMFK8870MU102948',
      year: 2021,
      make: 'Honda',
      model: 'Civic Type-R',
      regoNumber: 'VTC918',
      subModel: 'FK8 2.0L Turbo',
      engineCode: 'K20C1 VTEC Turbo',
      chassisCode: 'FK8',
      transmission: 'Manual',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_120',
        name: 'Electric Power Steering Rack & Pinion Assembly',
        partNumber: '53600-TGH-A02',
        category: 'Steering & Suspension',
        quantity: 1,
        qualityPreference: 'Genuine OEM',
        conditionRequired: 'New OEM',
      },
    ],
    quoteOptions: [
      {
        id: 'q_120_air',
        type: 'air',
        name: 'Air Freight',
        carrierName: 'Singapore Airlines Cargo',
        transitDays: '4–6 business days',
        estimatedDeliveryDate: '2026-09-02',
        partCostNZD: 1650.0,
        freightCostNZD: 250.0,
        procurementServiceNZD: 80.0,
        dutiesAndBiosecurityNZD: 0,
        gstNZD: 0,
        localCourierNZD: 0,
        totalLandedCostNZD: 1980.0,
        isRecommended: true,
      },
    ],
    approvedQuoteId: 'q_120_air',
    assignedSpecialist: {
      name: 'Brendon Davies',
      role: 'Senior Sourcing Lead',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      directPhone: '09 525 6814',
      email: 'brendon.d@autohub.co.nz',
    },
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    paymentStatus: 'Payment Received',
  },

  // 6. In Transit: AH-P-000125 (Nissan Leaf 2020)
  {
    id: 'req_125',
    referenceNumber: 'AH-P-000125',
    title: 'EV On-Board Charger (OBC) Module 6.6kW',
    createdAt: '2026-08-22T14:10:00Z',
    updatedAt: '2026-08-28T08:00:00Z',
    status: 'Customs Clearance',
    urgency: 'Critical (Vehicle Off Road)',
    vehicle: {
      vin: 'ZE1-0428910000000',
      year: 2020,
      make: 'Nissan',
      model: 'Leaf',
      regoNumber: 'MKF302',
      subModel: 'e+ G 62kWh',
      engineCode: 'EM57',
      chassisCode: 'ZE1',
      transmission: 'EV Direct Drive',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_125',
        name: 'Gen 3 High-Voltage On-Board Charger Module',
        partNumber: '292C4-5SA0A',
        category: 'EV / Hybrid Battery & Inverters',
        quantity: 1,
        conditionRequired: 'Grade A Used',
      },
    ],
    quoteOptions: [
      {
        id: 'q_125_air',
        type: 'air',
        name: 'Air Freight',
        carrierName: 'Nippon Cargo Airlines',
        transitDays: '4–6 business days',
        estimatedDeliveryDate: '2026-08-31',
        partCostNZD: 2100.0,
        freightCostNZD: 250.0,
        procurementServiceNZD: 100.0,
        dutiesAndBiosecurityNZD: 0,
        gstNZD: 0,
        localCourierNZD: 0,
        totalLandedCostNZD: 2450.0,
        isRecommended: true,
      },
    ],
    approvedQuoteId: 'q_125_air',
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    paymentStatus: 'Payment Received',
  },

  // 7. Delivered: AH-P-000118 (Subaru Outback 2018)
  {
    id: 'req_118',
    referenceNumber: 'AH-P-000118',
    title: 'Rear Axle Differential Assembly',
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-27T16:15:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: {
      vin: 'JF1BS99C8K0182741',
      year: 2018,
      make: 'Subaru',
      model: 'Outback',
      regoNumber: 'LQE384',
      subModel: '2.5i Premium AWD',
      engineCode: 'FB25',
      chassisCode: 'BS9',
      transmission: 'Automatic',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_118',
        name: 'Rear Axle Differential Assembly',
        partNumber: '28411-AL010',
        category: 'Transmission & Drivetrain',
        quantity: 1,
        conditionRequired: 'Grade A Used',
      },
    ],
    quoteOptions: [
      {
        id: 'q_118_air',
        type: 'air',
        name: 'Air Freight',
        carrierName: 'Air NZ Cargo Flight NZ90',
        transitDays: '4 business days',
        estimatedDeliveryDate: '2026-08-27',
        partCostNZD: 680.0,
        freightCostNZD: 110.0,
        procurementServiceNZD: 50.0,
        dutiesAndBiosecurityNZD: 0,
        gstNZD: 0,
        localCourierNZD: 0,
        totalLandedCostNZD: 840.0,
        isRecommended: true,
      },
    ],
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    paymentStatus: 'Payment Received',
  },

  // 8. Delivered: AH-P-000124 (Ford Ranger 2022)
  {
    id: 'req_124',
    referenceNumber: 'AH-P-000124',
    title: 'Bi-Turbo Intercooler Assembly',
    createdAt: '2026-08-27T11:45:00Z',
    updatedAt: '2026-08-28T10:00:00Z',
    status: 'Customer Approved',
    urgency: 'Standard',
    vehicle: {
      vin: 'MNAEY0FF8NW601934',
      year: 2022,
      make: 'Ford',
      model: 'Ranger',
      regoNumber: 'PRG902',
      subModel: 'Wildtrak Bi-Turbo 4x4',
      engineCode: 'YN2X',
      chassisCode: 'PY20',
      transmission: 'Automatic',
      originMarket: 'Australia',
    },
    parts: [
      {
        id: 'p_124',
        name: 'Bi-Turbo Intercooler Core & Boost Hose Kit',
        partNumber: 'JB3G-9L440-BD',
        category: 'Cooling & Climate Control (Radiators/Condensers)',
        quantity: 1,
        conditionRequired: 'New OEM',
      },
    ],
    quoteOptions: [
      {
        id: 'q_124_air',
        type: 'air',
        name: 'Air Freight',
        carrierName: 'Qantas Direct Freight',
        transitDays: '3–5 business days',
        estimatedDeliveryDate: '2026-09-02',
        partCostNZD: 1100.0,
        freightCostNZD: 120.0,
        procurementServiceNZD: 60.0,
        dutiesAndBiosecurityNZD: 0,
        gstNZD: 0,
        localCourierNZD: 0,
        totalLandedCostNZD: 1280.0,
        isRecommended: true,
      },
    ],
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    paymentStatus: 'Credit Approved',
  },
];

export const INITIAL_ORDERS: ProcurementOrder[] = [
  {
    id: 'ord_123',
    orderNumber: 'ORD-000123',
    requestId: 'req_123',
    requestNumber: 'AH-P-000123',
    vehicle: {
      vin: 'JTEBR32P10029384',
      year: 2019,
      make: 'Toyota',
      model: 'Hiace',
      regoNumber: 'KMR892',
      engineCode: '1KD-FTV',
      transmission: 'Automatic',
      originMarket: 'Japan',
    },
    part: {
      id: 'p_123',
      name: 'Left Front Lower Control Arm',
      partNumber: '48069-26150',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      conditionRequired: 'New OEM',
    },
    quantity: 1,
    totalAmountNZD: 485.0,
    status: 'Ordered From Supplier',
    createdAt: '2026-08-28T10:45:00Z',
    estimatedDeliveryDate: '2026-09-04',
    freightMethod: 'Air Freight (Express)',
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    timeline: [
      { stage: 'Customer Approved', timestamp: '28 Aug · 10:42 AM', status: 'completed', description: 'Quotation verified and approved by James Wilson.' },
      { stage: 'Payment Received', timestamp: '28 Aug · 10:44 AM', status: 'completed', description: 'Trade account billing verified and authorized.' },
      { stage: 'Ordered From Supplier', timestamp: '28 Aug · 11:00 AM', status: 'in-progress', description: 'PO transmitted to Toyota OEM central hub in Japan.' },
      { stage: 'Received at Shipping Facility', timestamp: 'Pending', status: 'pending', description: 'Scheduled arrival at Tokyo export warehouse.' },
      { stage: 'Shipment', timestamp: 'Pending', status: 'pending', description: 'Air freight dispatch via Air NZ Flight NZ90.' },
      { stage: 'Delivered', timestamp: 'Pending', status: 'pending', description: 'Workshop handover at 12 Example Street.' },
    ],
  },
  {
    id: 'ord_121',
    orderNumber: 'ORD-000121',
    requestId: 'req_121',
    requestNumber: 'AH-P-000121',
    vehicle: {
      vin: 'MNAEY0FF8NW601934',
      year: 2020,
      make: 'Ford',
      model: 'Ranger',
      regoNumber: 'FRD720',
      engineCode: 'P5AT',
      transmission: 'Automatic',
      originMarket: 'Australia',
    },
    part: {
      id: 'p_121',
      name: 'Door Mirror (RHS Power Folding)',
      partNumber: 'EB3B-17682-BD',
      quantity: 1,
      conditionRequired: 'New OEM',
    },
    quantity: 1,
    totalAmountNZD: 720.0,
    status: 'In Transit',
    createdAt: '2026-08-25T11:00:00Z',
    estimatedDeliveryDate: '2026-09-01',
    freightMethod: 'Air Freight',
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    timeline: [
      { stage: 'Customer Approved', timestamp: '25 Aug · 11:00 AM', status: 'completed', description: 'Quote confirmed.' },
      { stage: 'Payment Received', timestamp: '25 Aug · 11:05 AM', status: 'completed', description: 'Payment recorded.' },
      { stage: 'Ordered From Supplier', timestamp: '25 Aug · 01:30 PM', status: 'completed', description: 'Ford Australia parts depot.' },
      { stage: 'Received at Shipping Facility', timestamp: '26 Aug · 09:00 AM', status: 'completed', description: 'Sydney logistics facility.' },
      { stage: 'Shipment', timestamp: '27 Aug · 04:00 PM', status: 'in-progress', description: 'Qantas Freight AWB-081-4921049.' },
      { stage: 'Delivered', timestamp: 'Pending', status: 'pending', description: 'Expected 1 Sep.' },
    ],
  },
  {
    id: 'ord_120',
    orderNumber: 'ORD-000120',
    requestId: 'req_120',
    requestNumber: 'AH-P-000120',
    vehicle: {
      vin: 'JHMFK8870MU102948',
      year: 2021,
      make: 'Honda',
      model: 'Civic Type-R',
      regoNumber: 'VTC918',
      engineCode: 'K20C1',
      transmission: 'Manual',
      originMarket: 'Japan',
    },
    part: {
      id: 'p_120',
      name: 'Electric Power Steering Rack & Pinion Assembly',
      partNumber: '53600-TGH-A02',
      quantity: 1,
      conditionRequired: 'New OEM',
    },
    quantity: 1,
    totalAmountNZD: 1980.0,
    status: 'Received At Shipping Facility',
    createdAt: '2026-08-24T09:00:00Z',
    estimatedDeliveryDate: '2026-09-02',
    freightMethod: 'Air Freight',
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    timeline: [
      { stage: 'Customer Approved', timestamp: '24 Aug · 09:00 AM', status: 'completed', description: 'Approved.' },
      { stage: 'Payment Received', timestamp: '24 Aug · 09:10 AM', status: 'completed', description: 'Payment verified.' },
      { stage: 'Ordered From Supplier', timestamp: '24 Aug · 02:00 PM', status: 'completed', description: 'Honda OEM Japan depot.' },
      { stage: 'Received at Shipping Facility', timestamp: '27 Aug · 11:30 AM', status: 'completed', description: 'Yokohama Hub fitment QA inspected.' },
      { stage: 'Shipment', timestamp: 'Pending', status: 'in-progress', description: 'Export packing & crate strapping.' },
      { stage: 'Delivered', timestamp: 'Pending', status: 'pending', description: 'Expected 2 Sep.' },
    ],
  },
  {
    id: 'ord_118',
    orderNumber: 'ORD-000118',
    requestId: 'req_118',
    requestNumber: 'AH-P-000118',
    vehicle: {
      vin: 'JF1BS99C8K0182741',
      year: 2018,
      make: 'Subaru',
      model: 'Outback',
      regoNumber: 'LQE384',
      engineCode: 'FB25',
      transmission: 'Automatic',
      originMarket: 'Japan',
    },
    part: {
      id: 'p_118',
      name: 'Rear Axle Differential Assembly',
      partNumber: '28411-AL010',
      quantity: 1,
      conditionRequired: 'Grade A Used',
    },
    quantity: 1,
    totalAmountNZD: 840.0,
    status: 'Delivered',
    createdAt: '2026-08-20T10:00:00Z',
    estimatedDeliveryDate: '2026-08-27',
    freightMethod: 'Air Freight',
    deliveryAddress: {
      businessName: 'AutoCare Auckland',
      street: '12 Example Street',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    timeline: [
      { stage: 'Customer Approved', timestamp: '20 Aug · 10:00 AM', status: 'completed', description: 'Approved.' },
      { stage: 'Payment Received', timestamp: '20 Aug · 10:05 AM', status: 'completed', description: 'Paid.' },
      { stage: 'Ordered From Supplier', timestamp: '20 Aug · 03:00 PM', status: 'completed', description: 'Nagoya dismantling depot.' },
      { stage: 'Received at Shipping Facility', timestamp: '22 Aug · 09:00 AM', status: 'completed', description: 'Tokyo export crate.' },
      { stage: 'Shipment', timestamp: '24 Aug · 08:00 PM', status: 'completed', description: 'Air NZ Cargo Flight NZ90.' },
      { stage: 'Delivered', timestamp: '27 Aug · 04:15 PM', status: 'completed', description: 'Signed by Workshop foreman.' },
    ],
  },
];

export const INITIAL_SHIPMENTS: ShipmentTracking[] = [
  {
    id: 'shp_123',
    shipmentNumber: 'SHP-000123',
    requestId: 'req_123',
    requestNumber: 'AH-P-000123',
    orderNumber: 'ORD-000123',
    carrier: 'Air New Zealand Cargo / Autohub Express',
    carrierTrackingCode: 'AWB-086-94810291',
    vehicle: {
      vin: 'JTEBR32P10029384',
      year: 2019,
      make: 'Toyota',
      model: 'Hiace',
      regoNumber: 'KMR892',
    },
    partName: 'Left Front Lower Control Arm',
    status: 'In Transit',
    dispatchedAt: '2026-08-28T06:00:00Z',
    estimatedArrival: '18 September 2026',
    originHub: 'Tokyo Narita Hub (NRT)',
    destinationHub: 'Ports of Auckland / Penrose Hub',
    currentLocation: 'In transit - Air Cargo Flight NZ90',
    freightType: 'Air Freight',
    milestones: [
      { stage: 'Order placed', location: 'AutoCare Auckland Portal', timestamp: '28 Aug · 08:30 AM', status: 'completed', description: 'Procurement order locked and supplier verified.' },
      { stage: 'Supplier processing', location: 'Tokyo Toyota Depot, JP', timestamp: '28 Aug · 09:15 AM', status: 'completed', description: 'Genuine parts package released from factory rack.' },
      { stage: 'Received at shipping facility', location: 'Narita International Cargo Hub', timestamp: '28 Aug · 11:00 AM', status: 'completed', description: 'Export security scan and weight calibration completed.' },
      { stage: 'Dispatched', location: 'Narita International Airport (NRT)', timestamp: '28 Aug · 02:30 PM', status: 'completed', description: 'Departed Narita on Air NZ Flight NZ90.' },
      { stage: 'In transit', location: 'Pacific Sky Route', timestamp: '28 Aug · 04:00 PM', status: 'in-progress', description: 'En route to Auckland International Airport (AKL).' },
      { stage: 'Arrived in New Zealand', location: 'Auckland Airport (AKL)', timestamp: 'Pending', status: 'pending', description: 'Scheduled arrival Auckland cargo terminal.' },
      { stage: 'Customs clearance', location: 'Penrose Customs Depot', timestamp: 'Pending', status: 'pending', description: 'MPI Biosecurity green-lane pre-clearance.' },
      { stage: 'Out for delivery', location: 'Autohub Metro Express Van', timestamp: 'Pending', status: 'pending', description: 'Final mile courier dispatch.' },
      { stage: 'Delivered', location: '12 Example Street, Penrose', timestamp: 'Pending', status: 'pending', description: 'Direct workshop delivery signature.' },
    ],
  },
  {
    id: 'shp_121',
    shipmentNumber: 'SHP-000121',
    requestId: 'req_121',
    requestNumber: 'AH-P-000121',
    orderNumber: 'ORD-000121',
    carrier: 'Qantas Freight Direct',
    carrierTrackingCode: 'QF-7592-AKL',
    vehicle: {
      vin: 'MNAEY0FF8NW601934',
      year: 2020,
      make: 'Ford',
      model: 'Ranger',
      regoNumber: 'FRD720',
    },
    partName: 'Ford Ranger · Door Mirror',
    status: 'Arrived in New Zealand',
    dispatchedAt: '2026-08-27T16:00:00Z',
    estimatedArrival: '01 September 2026',
    originHub: 'Sydney Kingsford Smith Airport (SYD)',
    destinationHub: 'Auckland International Airport (AKL)',
    currentLocation: 'Auckland Inward Cargo Facility',
    freightType: 'Air Freight',
    milestones: [
      { stage: 'Order placed', location: 'Portal', timestamp: '25 Aug', status: 'completed', description: 'Order confirmed.' },
      { stage: 'Supplier processing', location: 'Melbourne, AU', timestamp: '26 Aug', status: 'completed', description: 'Packaged.' },
      { stage: 'Received at shipping facility', location: 'Sydney Cargo Hub', timestamp: '26 Aug', status: 'completed', description: 'Consolidated.' },
      { stage: 'Dispatched', location: 'Sydney SYD', timestamp: '27 Aug', status: 'completed', description: 'Flight QF141.' },
      { stage: 'In transit', location: 'Tasman Sea', timestamp: '27 Aug', status: 'completed', description: 'Trans-Tasman flight.' },
      { stage: 'Arrived in New Zealand', location: 'Auckland AKL', timestamp: '28 Aug · 07:30 AM', status: 'in-progress', description: 'Unloading at cargo hangar.' },
      { stage: 'Customs clearance', location: 'MPI Quarantine Hub', timestamp: 'Pending', status: 'pending', description: 'Customs clearance.' },
      { stage: 'Out for delivery', location: 'Auckland Metro', timestamp: 'Pending', status: 'pending', description: 'Courier run.' },
      { stage: 'Delivered', location: '12 Example Street', timestamp: 'Pending', status: 'pending', description: 'Delivery.' },
    ],
  },
  {
    id: 'shp_125',
    shipmentNumber: 'SHP-000125',
    requestId: 'req_125',
    requestNumber: 'AH-P-000125',
    orderNumber: 'ORD-000125',
    carrier: 'Nippon Cargo / Autohub Logistics',
    carrierTrackingCode: 'NCA-91823-NZ',
    vehicle: {
      vin: 'ZE1-0428910000000',
      year: 2020,
      make: 'Nissan',
      model: 'Leaf',
      regoNumber: 'MKF302',
    },
    partName: 'Nissan Leaf · EV Charger Module',
    status: 'Customs Clearance',
    dispatchedAt: '2026-08-24T12:00:00Z',
    estimatedArrival: '31 August 2026',
    originHub: 'Yokohama Hub, JP',
    destinationHub: 'Autohub Penrose Logistics Depot',
    currentLocation: 'Penrose MPI Biosecurity Terminal',
    freightType: 'Express Air',
    milestones: [
      { stage: 'Order placed', location: 'Portal', timestamp: '22 Aug', status: 'completed', description: 'Order verified.' },
      { stage: 'Supplier processing', location: 'Yokohama, JP', timestamp: '23 Aug', status: 'completed', description: 'Class 9 EV battery packaging.' },
      { stage: 'Received at shipping facility', location: 'Narita NRT', timestamp: '24 Aug', status: 'completed', description: 'Dangerous goods certification.' },
      { stage: 'Dispatched', location: 'Narita NRT', timestamp: '25 Aug', status: 'completed', description: 'Flight NCA89.' },
      { stage: 'In transit', location: 'International Airspace', timestamp: '26 Aug', status: 'completed', description: 'In flight.' },
      { stage: 'Arrived in New Zealand', location: 'Auckland AKL', timestamp: '27 Aug · 06:15 AM', status: 'completed', description: 'Arrived.' },
      { stage: 'Customs clearance', location: 'Penrose MPI Station', timestamp: '28 Aug · 08:00 AM', status: 'in-progress', description: 'Biosecurity inspection clearance.' },
      { stage: 'Out for delivery', location: 'Express Van', timestamp: 'Pending', status: 'pending', description: 'Final leg.' },
      { stage: 'Delivered', location: '12 Example Street', timestamp: 'Pending', status: 'pending', description: 'Handover.' },
    ],
  },
];

export const INITIAL_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'pay_123',
    paymentNumber: 'PAY-000123',
    requestId: 'req_123',
    requestNumber: 'AH-P-000123',
    orderNumber: 'ORD-000123',
    vehicleSummary: 'Toyota Hiace · 2019',
    partSummary: 'Left Front Lower Control Arm',
    amountNZD: 485.0,
    status: 'Awaiting Payment',
    dueDate: '2026-08-30',
  },
  {
    id: 'pay_119',
    paymentNumber: 'PAY-000119',
    requestId: 'req_119',
    requestNumber: 'AH-P-000119',
    vehicleSummary: 'Mazda CX-5 · 2021',
    partSummary: 'Front Headlamp (RHS)',
    amountNZD: 650.0,
    status: 'Payment Failed',
    dueDate: '2026-08-28',
  },
  {
    id: 'pay_121',
    paymentNumber: 'PAY-000121',
    requestId: 'req_121',
    requestNumber: 'AH-P-000121',
    orderNumber: 'ORD-000121',
    vehicleSummary: 'Ford Ranger · 2020',
    partSummary: 'Door Mirror (RHS Power Folding)',
    amountNZD: 720.0,
    status: 'Payment Received',
    dueDate: '2026-08-25',
    paidAt: '2026-08-25T11:05:00Z',
    paymentMethod: 'Approved Trade Credit (20th Mth Following)',
    receiptNumber: 'RCP-2026-0825-121',
  },
  {
    id: 'pay_124',
    paymentNumber: 'PAY-000124',
    requestId: 'req_124',
    requestNumber: 'AH-P-000124',
    vehicleSummary: 'Ford Ranger · 2022',
    partSummary: 'Bi-Turbo Intercooler Assembly',
    amountNZD: 1280.0,
    status: 'Credit Approved',
    dueDate: '2026-09-20',
    paidAt: '2026-08-28T10:00:00Z',
    paymentMethod: 'Approved Trade Credit (20th Mth Following)',
  },
  {
    id: 'pay_118',
    paymentNumber: 'PAY-000118',
    requestId: 'req_118',
    requestNumber: 'AH-P-000118',
    orderNumber: 'ORD-000118',
    vehicleSummary: 'Subaru Outback · 2018',
    partSummary: 'Rear Axle Differential Assembly',
    amountNZD: 840.0,
    status: 'Payment Received',
    dueDate: '2026-08-20',
    paidAt: '2026-08-20T10:05:00Z',
    paymentMethod: 'Account2Account Bank Transfer',
    receiptNumber: 'RCP-2026-0820-118',
  },
  {
    id: 'pay_115',
    paymentNumber: 'PAY-000115',
    requestId: 'req_115',
    requestNumber: 'AH-P-000115',
    vehicleSummary: 'Nissan Leaf · 2019',
    partSummary: 'Front Strut Mounts (Pair)',
    amountNZD: 310.0,
    status: 'Refunded',
    dueDate: '2026-08-15',
    paidAt: '2026-08-15T14:00:00Z',
    paymentMethod: 'Account2Account Bank Transfer',
    receiptNumber: 'REF-2026-0818-115',
  },
];

export const INITIAL_DOCUMENTS: PortalDocument[] = [
  {
    id: 'doc_123_quote',
    title: 'Quotation — AH-P-000123',
    category: 'Quotes',
    requestId: 'req_123',
    requestNumber: 'AH-P-000123',
    date: '28 Aug 2026',
    fileFormat: 'PDF',
    fileSizeBytes: 245000,
    fileSizeFormatted: '245 KB',
    documentType: 'Quotation',
    previewData: {
      quoteNumber: 'AH-Q-2026-000123',
      customerName: 'AutoCare Auckland (James Wilson)',
      vehicleDetails: '2019 Toyota Hiace ZX Grand Cabin (VIN: JTEBR32P10029384)',
      partDetails: 'Left Front Lower Control Arm (OEM: 48069-26150)',
      items: [
        { desc: 'Left Front Lower Control Arm (Genuine OEM Toyota)', qty: 1, unitPrice: 350.0, total: 350.0 },
        { desc: 'International Air Freight (Priority Express)', qty: 1, unitPrice: 85.0, total: 85.0 },
        { desc: 'Autohub Verified Procurement & Logistics Service', qty: 1, unitPrice: 50.0, total: 50.0 },
      ],
      subtotal: 485.0,
      gst: 0.0,
      total: 485.0,
    },
  },
  {
    id: 'doc_121_inv',
    title: 'Tax Invoice — INV-2026-0825',
    category: 'Invoices',
    requestId: 'req_121',
    requestNumber: 'AH-P-000121',
    date: '25 Aug 2026',
    fileFormat: 'PDF',
    fileSizeBytes: 310000,
    fileSizeFormatted: '310 KB',
    documentType: 'Tax Invoice',
    previewData: {
      invoiceNumber: 'INV-2026-0825',
      customerName: 'AutoCare Auckland',
      vehicleDetails: '2020 Ford Ranger Wildtrak (VIN: MNAEY0FF8NW601934)',
      partDetails: 'Door Mirror RHS Power Folding (OEM: EB3B-17682-BD)',
      items: [
        { desc: 'Ford Ranger Power Folding Mirror Assembly', qty: 1, unitPrice: 580.0, total: 580.0 },
        { desc: 'Trans-Tasman Express Freight', qty: 1, unitPrice: 90.0, total: 90.0 },
        { desc: 'Procurement Management', qty: 1, unitPrice: 50.0, total: 50.0 },
      ],
      subtotal: 720.0,
      gst: 0.0,
      total: 720.0,
    },
  },
  {
    id: 'doc_118_rcp',
    title: 'Payment Receipt — RCP-2026-0820',
    category: 'Payment Receipts',
    requestId: 'req_118',
    requestNumber: 'AH-P-000118',
    date: '20 Aug 2026',
    fileFormat: 'PDF',
    fileSizeBytes: 180000,
    fileSizeFormatted: '180 KB',
    documentType: 'Receipt',
  },
  {
    id: 'doc_120_proc',
    title: 'Procurement & Fitment Verification — AH-P-000120',
    category: 'Procurement Documents',
    requestId: 'req_120',
    requestNumber: 'AH-P-000120',
    date: '24 Aug 2026',
    fileFormat: 'PDF',
    fileSizeBytes: 420000,
    fileSizeFormatted: '420 KB',
    documentType: 'Inspection Certificate',
  },
  {
    id: 'doc_125_ship',
    title: 'Biosecurity Clearance & Air Waybill — AWB-NCA-91823',
    category: 'Shipping Documents',
    requestId: 'req_125',
    requestNumber: 'AH-P-000125',
    date: '27 Aug 2026',
    fileFormat: 'PDF',
    fileSizeBytes: 512000,
    fileSizeFormatted: '512 KB',
    documentType: 'Biosecurity Clearance',
  },
];

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'team_1',
    name: 'James Wilson',
    email: 'james@example.com',
    phone: '021 555 8921',
    role: 'Administrator',
    status: 'Active',
    lastActive: 'Just now',
    avatarInitials: 'JW',
    permissions: ['Full Access', 'Submit Requests', 'Approve Quotes', 'Authorize Payments', 'Manage Team'],
  },
  {
    id: 'team_2',
    name: 'Sarah Jenkins',
    email: 'accounts@autocareauckland.co.nz',
    phone: '09 525 6810',
    role: 'Accounts Contact',
    status: 'Active',
    lastActive: '2 hours ago',
    avatarInitials: 'SJ',
    permissions: ['Billing & Invoices', 'Authorize Payments', 'View Requests'],
  },
  {
    id: 'team_3',
    name: 'Mike Chen',
    email: 'mike.chen@autocareauckland.co.nz',
    phone: '027 884 1920',
    role: 'Workshop Manager',
    status: 'Active',
    lastActive: '35 mins ago',
    avatarInitials: 'MC',
    permissions: ['Submit Requests', 'Review Quotes', 'Track Shipments', 'Messaging'],
  },
  {
    id: 'team_4',
    name: 'Dave Taylor',
    email: 'dave.t@autocareauckland.co.nz',
    role: 'Senior Technician',
    status: 'Active',
    lastActive: 'Yesterday',
    avatarInitials: 'DT',
    permissions: ['Submit Requests', 'Track Shipments', 'View Vehicles'],
  },
  {
    id: 'team_5',
    name: 'Liam Cooper',
    email: 'liam.c@autocareauckland.co.nz',
    role: 'Technician',
    status: 'Invited',
    lastActive: 'Never',
    avatarInitials: 'LC',
    permissions: ['Submit Requests', 'View Parts'],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    type: 'QUOTE_AVAILABLE',
    title: 'Quote Available',
    description: 'AH-P-000123 is ready for review (Toyota Hiace · NZ$485.00).',
    timeGroup: 'Today',
    timestamp: '2026-08-28T10:42:00Z',
    timeAgo: '10:42 AM',
    isRead: false,
    requestId: 'req_123',
    requestNumber: 'AH-P-000123',
    linkUrl: '/requests/req_123',
  },
  {
    id: 'notif_2',
    type: 'PAYMENT_RECEIVED',
    title: 'Payment Received',
    description: 'Payment for AH-P-000120 was successfully received.',
    timeGroup: 'Today',
    timestamp: '2026-08-28T09:20:00Z',
    timeAgo: '09:20 AM',
    isRead: false,
    requestId: 'req_120',
    requestNumber: 'AH-P-000120',
    linkUrl: '/requests/req_120',
  },
  {
    id: 'notif_3',
    type: 'SHIPMENT_DISPATCHED',
    title: 'Shipment Dispatched',
    description: 'AH-P-000118 has been dispatched from Tokyo Narita.',
    timeGroup: 'Yesterday',
    timestamp: '2026-08-27T16:15:00Z',
    timeAgo: 'Yesterday · 04:15 PM',
    isRead: true,
    requestId: 'req_118',
    requestNumber: 'AH-P-000118',
    linkUrl: '/shipments/shp_118',
  },
  {
    id: 'notif_4',
    type: 'ORDER_PLACED',
    title: 'Order Placed with Supplier',
    description: 'ORD-000121 confirmed with supplier in Melbourne.',
    timeGroup: 'Yesterday',
    timestamp: '2026-08-27T13:00:00Z',
    timeAgo: 'Yesterday · 01:00 PM',
    isRead: true,
    requestId: 'req_121',
    requestNumber: 'AH-P-000121',
    linkUrl: '/orders/ord_121',
  },
  {
    id: 'notif_5',
    type: 'INFORMATION_REQUIRED',
    title: 'Information Required',
    description: 'Specialist requested VIN plate clarification on AH-P-000122.',
    timeGroup: 'Older',
    timestamp: '2026-08-26T11:00:00Z',
    timeAgo: '26 Aug',
    isRead: true,
    requestId: 'req_122',
    requestNumber: 'AH-P-000122',
    linkUrl: '/requests/req_122',
  },
  {
    id: 'notif_6',
    type: 'DELIVERED',
    title: 'Delivered to Workshop',
    description: 'Consignment AH-P-000118 safely delivered to Auckland workshop.',
    timeGroup: 'Older',
    timestamp: '2026-08-27T16:15:00Z',
    timeAgo: '27 Aug',
    isRead: true,
    requestId: 'req_118',
    requestNumber: 'AH-P-000118',
    linkUrl: '/requests/req_118',
  },
];
