import { PartRequest, TradeAccount } from '@/types';

export const INITIAL_TRADE_ACCOUNT: TradeAccount = {
  id: 'acc_nz_88291',
  legalBusinessName: 'Apex Precision Automotive Group Ltd',
  tradingName: 'Apex Euro & Japanese Specialists',
  businessType: 'Collision Repairer',
  nzbn: '9429048291034',
  gstNumber: '128-492-910',
  primaryContact: {
    name: 'Marcus Henderson',
    email: 'marcus.h@apexautocraft.co.nz',
    phone: '021 849 2039',
    role: 'Lead Parts & Workshop Manager',
  },
  accountsPayableEmail: 'accounts@apexautocraft.co.nz',
  branchCount: 3,
  deliverySetup: {
    street: '18 Church Street',
    suburb: 'Onehunga',
    city: 'Auckland',
    postcode: '1061',
    hasForklift: true,
    hasLoadingDock: true,
    gateCode: '9842',
    openingHours: 'Mon-Fri 7:00 AM - 5:30 PM, Sat 8:00 AM - 1:00 PM',
  },
  creditStatus: 'Approved - 20th Month Following',
  memberSince: 'March 2022',
  activeRequestsCount: 4,
  totalOrdersCount: 47,
};

export const INITIAL_REQUESTS: PartRequest[] = [
  {
    id: 'req_101',
    referenceNumber: 'AH-P-000123',
    title: 'Front Right LED Headlamp & Bumper Reinforcement Beam',
    createdAt: '2026-08-25T08:30:00Z',
    updatedAt: '2026-08-28T09:15:00Z',
    status: 'In Transit - Air',
    urgency: 'Urgent',
    vehicle: {
      vin: 'JTEBX3EJ9K1208941',
      year: 2021,
      make: 'Toyota',
      model: 'Hilux',
      subModel: 'SR5 Cruiser 4WD Double Cab',
      engineCode: '1GD-FTV 2.8L Turbo Diesel',
      chassisCode: 'GUN126R',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_01',
        name: 'Right Hand LED Headlight Assembly (OEM Projector)',
        partNumber: '81110-0KP70',
        category: 'Headlights, Tail Lights & Lighting',
        quantity: 1,
        conditionRequired: 'New OEM',
        vehicleSide: 'Right (Driver)',
        description: 'Auto-leveling LED type with integrated DRL. Must include factory ballast and rear sealing cap.',
      },
      {
        id: 'p_02',
        name: 'Front Bumper Impact Reinforcement Crossmember',
        partNumber: '52021-0K150',
        category: 'Body Panels & Structural Panels',
        quantity: 1,
        conditionRequired: 'New OEM',
        vehicleSide: 'Front',
        description: 'High-strength steel crossmember with factory crush brackets.',
      },
    ],
    selectedFreight: 'Air Freight (Express)',
    approvedQuoteId: 'q_101_air',
    quoteOptions: [
      {
        id: 'q_101_air',
        type: 'air_express',
        carrierName: 'Air New Zealand Cargo / DHL Express',
        transitDays: '3-5 Business Days',
        estimatedDeliveryDate: '2026-08-30',
        partCostNZD: 1850.00,
        freightCostNZD: 340.00,
        dutiesAndBiosecurityNZD: 65.00,
        gstNZD: 338.25,
        localCourierNZD: 45.00,
        totalLandedCostNZD: 2638.25,
        isRecommended: true,
        notes: 'Guaranteed OEM parts sourced direct from Tokyo export depot. Pre-cleared for NZ customs.',
      },
      {
        id: 'q_101_sea',
        type: 'sea_freight',
        carrierName: 'Autohub Dedicated FCL Logistics',
        transitDays: '18-24 Days',
        estimatedDeliveryDate: '2026-09-18',
        partCostNZD: 1850.00,
        freightCostNZD: 110.00,
        dutiesAndBiosecurityNZD: 65.00,
        gstNZD: 303.75,
        localCourierNZD: 45.00,
        totalLandedCostNZD: 2373.75,
        isRecommended: false,
        notes: 'Consolidated sea container via Ports of Auckland.',
      },
    ],
    assignedSpecialist: {
      name: 'Brendon Davies',
      role: 'Senior Sourcing & Logistics Specialist',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      directPhone: '09 525 6814',
      email: 'brendon.d@autohub.co.nz',
    },
    trackingMilestones: [
      {
        id: 'm_1',
        title: 'Request Sourced & Verified',
        location: 'Tokyo Supplier Depot, JP',
        timestamp: '2026-08-25 14:20',
        status: 'completed',
        description: 'Parts inspected, physical VIN fitment certified, and protective foam palletized.',
        carrier: 'Autohub Japan Hub',
      },
      {
        id: 'm_2',
        title: 'Dispatched to Narita Airport',
        location: 'Narita International (NRT), JP',
        timestamp: '2026-08-26 18:40',
        status: 'completed',
        description: 'Export customs cleared. Loaded onto Air NZ flight NZ90.',
        carrier: 'Air New Zealand Cargo',
        referenceNumber: 'AWB-086-94810291',
      },
      {
        id: 'm_3',
        title: 'Arrived at Auckland Airport & MPI Biosecurity Cleared',
        location: 'Auckland Cargo Terminal (AKL), NZ',
        timestamp: '2026-08-28 07:15',
        status: 'completed',
        description: 'Primary NZ Customs clearance completed. Biosecurity green-lane released.',
        carrier: 'Autohub Customs Brokerage',
      },
      {
        id: 'm_4',
        title: 'Dispatched to Penrose Distribution Centre',
        location: 'Autohub Logistics Hub, Penrose, Auckland',
        timestamp: '2026-08-28 09:15',
        status: 'in-progress',
        description: 'Sorted for express final-mile courier delivery to workshop.',
        carrier: 'Mainstream / CourierPost Direct',
      },
      {
        id: 'm_5',
        title: 'Workshop Delivery & Sign-off',
        location: 'Apex Euro & Japanese, Onehunga, Auckland',
        timestamp: 'Estimated: 2026-08-29 11:30',
        status: 'pending',
        description: 'Direct handover to workshop foreman with delivery docket.',
      },
    ],
    deliveryAddress: {
      businessName: 'Apex Precision Automotive Group Ltd',
      street: '18 Church Street',
      suburb: 'Onehunga',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
      deliveryNotes: 'Please ring the buzzer at Bay 2 parts delivery entrance.',
    },
    messages: [
      {
        id: 'msg_1',
        sender: 'specialist',
        senderName: 'Brendon Davies',
        timestamp: '2026-08-25 10:15',
        text: 'Kia ora Marcus, we matched the factory OEM part number 81110-0KP70 for your 2021 Hilux. The Japanese export warehouse has it in stock. Express air quote is ready for your review.',
      },
      {
        id: 'msg_2',
        sender: 'user',
        senderName: 'Marcus Henderson',
        timestamp: '2026-08-25 11:00',
        text: 'Thanks Brendon. We have approved the Express Air option. The vehicle is on our hoist waiting for panel assembly.',
      },
      {
        id: 'msg_3',
        sender: 'specialist',
        senderName: 'Brendon Davies',
        timestamp: '2026-08-28 07:30',
        text: 'Flight arrived at Auckland early this morning! Biosecurity cleared without inspection delay. It is on the courier van out of Penrose shortly.',
      },
    ],
  },
  {
    id: 'req_102',
    referenceNumber: 'AH-P-000124',
    title: 'Bi-Turbo Intercooler Assembly & High Pressure Boost Hose',
    createdAt: '2026-08-27T11:45:00Z',
    updatedAt: '2026-08-28T10:00:00Z',
    status: 'Quote Ready',
    urgency: 'Standard',
    vehicle: {
      vin: 'MNAEY0FF8NW601934',
      year: 2022,
      make: 'Ford',
      model: 'Ranger',
      subModel: 'Wildtrak Bi-Turbo 4x4',
      engineCode: 'YN2X 2.0L Bi-Turbo Diesel',
      chassisCode: 'PY20',
      originMarket: 'Australia',
    },
    parts: [
      {
        id: 'p_03',
        name: 'Charge Air Cooler / Intercooler Core Assembly',
        partNumber: 'JB3G-9L440-BD',
        category: 'Cooling & Climate Control (Radiators/Condensers)',
        quantity: 1,
        conditionRequired: 'New OEM',
        vehicleSide: 'Front',
        description: 'Complete intercooler core with reinforced end-tanks and bracket mounting rubbers.',
      },
      {
        id: 'p_04',
        name: 'Intercooler Cold Side Outlet Hose with Sensors',
        partNumber: 'JB3G-6C646-AC',
        category: 'Engine & Mechanical',
        quantity: 1,
        conditionRequired: 'New OEM',
        vehicleSide: 'Engine Bay',
        description: 'Reinforced 5-ply silicone/fluorocarbon boost hose with factory quick clips.',
      },
    ],
    quoteOptions: [
      {
        id: 'q_102_air',
        type: 'air_express',
        carrierName: 'Qantas Freight Direct Trans-Tasman',
        transitDays: '2-4 Business Days',
        estimatedDeliveryDate: '2026-09-02',
        partCostNZD: 1280.00,
        freightCostNZD: 195.00,
        dutiesAndBiosecurityNZD: 48.00,
        gstNZD: 228.45,
        localCourierNZD: 35.00,
        totalLandedCostNZD: 1786.45,
        isRecommended: true,
        notes: 'Sourced from Melbourne distribution centre. In stock ready for same-day dispatch.',
      },
      {
        id: 'q_102_sea',
        type: 'sea_freight',
        carrierName: 'Coastal & Trans-Tasman Maritime Express',
        transitDays: '12-16 Days',
        estimatedDeliveryDate: '2026-09-14',
        partCostNZD: 1280.00,
        freightCostNZD: 75.00,
        dutiesAndBiosecurityNZD: 48.00,
        gstNZD: 210.45,
        localCourierNZD: 35.00,
        totalLandedCostNZD: 1648.45,
        isRecommended: false,
        notes: 'Weekly consolidated sea freight container.',
      },
    ],
    assignedSpecialist: {
      name: 'Sarah Chen',
      role: 'Trans-Tasman & Asian Procurement Lead',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
      directPhone: '09 525 6822',
      email: 'sarah.c@autohub.co.nz',
    },
    deliveryAddress: {
      businessName: 'Apex Precision Automotive Group Ltd',
      street: '18 Church Street',
      suburb: 'Onehunga',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    messages: [
      {
        id: 'msg_10',
        sender: 'specialist',
        senderName: 'Sarah Chen',
        timestamp: '2026-08-28 10:05',
        text: 'Hi Marcus, both quotes have been prepared for the Ranger Wildtrak intercooler. Air freight is only $138 more and will arrive in Auckland by early next week.',
      },
    ],
  },
  {
    id: 'req_103',
    referenceNumber: 'AH-P-000125',
    title: 'EV On-Board Charger (OBC) Module & High-Voltage Relay Assembly',
    createdAt: '2026-08-22T14:10:00Z',
    updatedAt: '2026-08-28T08:00:00Z',
    status: 'Customs Clearance',
    urgency: 'Critical (Vehicle Off Road)',
    vehicle: {
      vin: 'ZE1-042891',
      year: 2020,
      make: 'Nissan',
      model: 'Leaf',
      subModel: 'e+ G 62kWh',
      engineCode: 'EM57 Electric Motor',
      chassisCode: 'ZE1',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_05',
        name: 'Gen 3 High-Voltage On-Board Charger (6.6kW / ChaDeMo Controller)',
        partNumber: '292C4-5SA0A',
        category: 'EV / Hybrid Battery & Inverters',
        quantity: 1,
        conditionRequired: 'Grade A Used',
        vehicleSide: 'Underbody',
        description: 'Verified donor vehicle (24,000km, undamaged battery casing). Full diagnostic bench test passed.',
      },
    ],
    selectedFreight: 'Air Freight (Express)',
    approvedQuoteId: 'q_103_air',
    quoteOptions: [
      {
        id: 'q_103_air',
        type: 'air_express',
        carrierName: 'Nippon Cargo Airlines / Autohub Priority',
        transitDays: '4-6 Days',
        estimatedDeliveryDate: '2026-08-29',
        partCostNZD: 2450.00,
        freightCostNZD: 420.00,
        dutiesAndBiosecurityNZD: 95.00,
        gstNZD: 444.75,
        localCourierNZD: 55.00,
        totalLandedCostNZD: 3464.75,
        isRecommended: true,
        notes: 'Hazardous Class 9 lithium protocol compliant air freight packaging.',
      },
    ],
    assignedSpecialist: {
      name: 'Kenji Takahashi',
      role: 'Japanese Auction & OEM Procurement Specialist',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      directPhone: '+81 45 680 9182',
      email: 'kenji.t@autohub.co.jp',
    },
    trackingMilestones: [
      {
        id: 'm_301',
        title: 'Diagnostic Test Passed & Packaged',
        location: 'Yokohama EV Specialist Facility, JP',
        timestamp: '2026-08-23 11:00',
        status: 'completed',
        description: 'Passed insulation resistance test and full CAN-bus communication check.',
      },
      {
        id: 'm_302',
        title: 'Export Documentation & Air Freight Transit',
        location: 'Haneda International Airport, JP',
        timestamp: '2026-08-25 22:30',
        status: 'completed',
        description: 'Cleared Japanese Ministry of Economy export clearance.',
      },
      {
        id: 'm_303',
        title: 'Customs & Hazardous Goods Inspection',
        location: 'Customs Bonded Warehouse, Auckland Airport',
        timestamp: '2026-08-28 06:45',
        status: 'in-progress',
        description: 'Customs tariff verification code 8504.40. Final biosecurity clearance underway.',
      },
      {
        id: 'm_304',
        title: 'Specialist Dangerous Goods Courier to Onehunga',
        location: 'Auckland Metro',
        timestamp: 'Scheduled 2026-08-29 09:00',
        status: 'pending',
        description: 'Dedicated transport to workshop.',
      },
    ],
    deliveryAddress: {
      businessName: 'Apex Precision Automotive Group Ltd',
      street: '18 Church Street',
      suburb: 'Onehunga',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },
  {
    id: 'req_104',
    referenceNumber: 'AH-P-000126',
    title: 'Adaptive M-Sport Front Suspension Struts & Control Arm Kit',
    createdAt: '2026-08-14T09:00:00Z',
    updatedAt: '2026-08-21T15:30:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: {
      vin: 'WBA8E12040K918234',
      year: 2020,
      make: 'BMW',
      model: '3 Series',
      subModel: 'M340i xDrive Sedan',
      engineCode: 'B58B30 3.0L Turbo',
      chassisCode: 'G20',
      originMarket: 'Europe',
    },
    parts: [
      {
        id: 'p_06',
        name: 'Left & Right Electronic Damping Control Front Struts',
        partNumber: '31316888497 / 31316888498',
        category: 'Steering & Suspension',
        quantity: 2,
        conditionRequired: 'New OEM',
        vehicleSide: 'Front',
        description: 'Genuine BMW factory EDC electronic struts in original boxes.',
      },
    ],
    selectedFreight: 'Air Freight (Express)',
    approvedQuoteId: 'q_104_air',
    quoteOptions: [
      {
        id: 'q_104_air',
        type: 'air_express',
        carrierName: 'Lufthansa Cargo / DHL Global Forwarding',
        transitDays: '5 Business Days',
        estimatedDeliveryDate: '2026-08-21',
        partCostNZD: 3100.00,
        freightCostNZD: 480.00,
        dutiesAndBiosecurityNZD: 85.00,
        gstNZD: 549.75,
        localCourierNZD: 45.00,
        totalLandedCostNZD: 4259.75,
        isRecommended: true,
        notes: 'Direct from BMW Central Parts Distribution in Munich.',
      },
    ],
    assignedSpecialist: {
      name: 'Oliver Krause',
      role: 'European OEM Procurement Lead',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      directPhone: '+49 89 2488 190',
      email: 'oliver.k@autohub.de',
    },
    trackingMilestones: [
      {
        id: 'm_401',
        title: 'Munich Central Depot Dispatch',
        location: 'Munich, Germany',
        timestamp: '2026-08-16 16:00',
        status: 'completed',
        description: 'Original BMW factory parts dispatched via air freight.',
      },
      {
        id: 'm_402',
        title: 'Auckland Airport Customs Cleared',
        location: 'Auckland, NZ',
        timestamp: '2026-08-20 10:30',
        status: 'completed',
        description: 'Duties and GST paid under Autohub direct credit.',
      },
      {
        id: 'm_403',
        title: 'Delivered & Signed for by Workshop',
        location: 'Apex Euro & Japanese, Onehunga',
        timestamp: '2026-08-21 14:15',
        status: 'completed',
        description: 'Received in pristine condition. Signed by Marcus H.',
      },
    ],
    deliveryAddress: {
      businessName: 'Apex Precision Automotive Group Ltd',
      street: '18 Church Street',
      suburb: 'Onehunga',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },
  {
    id: 'req_105',
    referenceNumber: 'AH-P-000127',
    title: 'EJ207 Cylinder Heads & Twin-Scroll VF49 Turbocharger',
    createdAt: '2026-08-28T07:15:00Z',
    updatedAt: '2026-08-28T10:45:00Z',
    status: 'Sourcing',
    urgency: 'Standard',
    vehicle: {
      vin: 'JF1VAG09489201948',
      year: 2019,
      make: 'Subaru',
      model: 'WRX STI',
      subModel: 'Type S Premium',
      engineCode: 'EJ207 2.0L Twin Scroll Turbo',
      chassisCode: 'VAB',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_07',
        name: 'Genuine IHI VF49 Twin-Scroll Turbocharger Sub-Assembly',
        partNumber: '14411AA760',
        category: 'Engine & Mechanical',
        quantity: 1,
        conditionRequired: 'New OEM',
        vehicleSide: 'Engine Bay',
        description: 'Factory JDM STI specification VF49 turbo with all oil/water feed banjo fittings.',
      },
    ],
    assignedSpecialist: {
      name: 'Kenji Takahashi',
      role: 'Japanese Auction & OEM Procurement Specialist',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      directPhone: '+81 45 680 9182',
      email: 'kenji.t@autohub.co.jp',
    },
    deliveryAddress: {
      businessName: 'Apex Precision Automotive Group Ltd',
      street: '18 Church Street',
      suburb: 'Onehunga',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },
];
