import { PartRequest, TradeAccount } from '@/types';

export const INITIAL_TRADE_ACCOUNT: TradeAccount = {
  id: 'acc_nz_premier_01',
  legalBusinessName: 'Premier Motors NZ Ltd',
  tradingName: 'Premier Motors NZ',
  businessType: 'Mechanical Workshop',
  nzbn: '9429048291034',
  gstNumber: '128-492-910',
  primaryContact: {
    name: 'Dave Morrison',
    email: 'dave@premiermotors.co.nz',
    phone: '021 555 8921',
    role: 'Procurement & Workshop Director',
  },
  accountsPayableEmail: 'accounts@premiermotors.co.nz',
  branchCount: 2,
  deliverySetup: {
    street: '45 Great South Rd',
    suburb: 'Penrose',
    city: 'Auckland',
    postcode: '1061',
    hasForklift: true,
    hasLoadingDock: true,
    gateCode: '4500',
    openingHours: 'Mon-Fri 7:30 AM - 5:30 PM, Sat 8:00 AM - 12:30 PM',
  },
  creditStatus: 'Approved - 20th Month Following',
  memberSince: 'January 2021',
  activeRequestsCount: 8,
  totalOrdersCount: 52,
};

export const INITIAL_REQUESTS: PartRequest[] = [
  // 1. Quoted Item (AH-P-000123) - Toyota Hiace 2019
  {
    id: 'req_123',
    referenceNumber: 'AH-P-000123',
    title: 'Left Front Lower Control Arm (Genuine OEM)',
    createdAt: '2026-08-28T08:30:00Z',
    updatedAt: '2026-08-28T09:15:00Z',
    status: 'Quoted',
    urgency: 'Urgent',
    vehicle: {
      vin: 'JTEBR32P10029384',
      year: 2019,
      make: 'Toyota',
      model: 'Hiace',
      regoNumber: 'KMR892',
      subModel: 'ZX Grand Cabin 3.0L Diesel',
      engineCode: '1KD-FTV',
      chassisCode: 'KDH201',
      transmission: 'Automatic',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_123',
        name: 'Left Front Lower Control Arm',
        partNumber: '48069-26150',
        category: 'Steering & Suspension',
        quantity: 1,
        qualityPreference: 'Genuine OEM',
        conditionPreference: 'New Only',
        conditionRequired: 'New OEM',
        vehicleSide: 'Left (Passenger)',
        description: 'Must include factory rubber bushings and lower ball joint assembly.',
        damagePhotos: [
          'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=400&q=80',
        ],
      },
    ],
    selectedFreight: 'Air Freight (Express)',
    quoteOptions: [
      {
        id: 'q_123_air',
        type: 'air_express',
        carrierName: 'Air New Zealand Cargo Flight NZ90',
        transitDays: '3-5 Business Days',
        estimatedDeliveryDate: '2026-09-02',
        partCostNZD: 260.00,
        freightCostNZD: 65.00,
        dutiesAndBiosecurityNZD: 15.00,
        gstNZD: 45.00,
        localCourierNZD: 0.00,
        totalLandedCostNZD: 385.00,
        isRecommended: true,
        notes: 'AIR FREIGHT - FASTEST (Inc. Freight, Customs, GST)',
      },
      {
        id: 'q_123_sea',
        type: 'sea_freight',
        carrierName: 'Autohub Consolidated Sea Freight',
        transitDays: '18-22 Business Days',
        estimatedDeliveryDate: '2026-09-18',
        partCostNZD: 180.00,
        freightCostNZD: 25.00,
        dutiesAndBiosecurityNZD: 10.00,
        gstNZD: 25.00,
        localCourierNZD: 0.00,
        totalLandedCostNZD: 240.00,
        isRecommended: false,
        notes: 'SEA FREIGHT - ECONOMY (Inc. Freight, Customs, GST)',
      },
    ],
    assignedSpecialist: {
      name: 'Brendon Davies',
      role: 'Senior Sourcing & Logistics Specialist',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      directPhone: '09 525 6814',
      email: 'brendon.d@autohub.co.nz',
    },
    trackingMilestones: [
      {
        id: 'm_123_1',
        title: 'Request Sourced & Verified',
        location: 'Tokyo Toyota Parts Hub, JP',
        timestamp: '2026-08-28 08:45',
        status: 'completed',
        description: 'OEM fitment checked against VIN JTEBR32P10029384. Direct factory stock confirmed.',
      },
      {
        id: 'm_123_2',
        title: 'Landed Quotation Issued',
        location: 'Autohub Auckland Hub',
        timestamp: '2026-08-28 09:15',
        status: 'completed',
        description: 'Air Freight ($385.00 NZD) and Sea Freight ($240.00 NZD) landed options calculated.',
      },
    ],
    deliveryAddress: {
      businessName: 'Premier Motors NZ',
      street: '45 Great South Rd',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
      deliveryNotes: 'Deliver to rear parts counter. Ask for Dave.',
    },
    messages: [
      {
        id: 'msg_123_1',
        sender: 'specialist',
        senderName: 'Brendon Davies',
        timestamp: '2026-08-28 09:20',
        text: 'Kia ora Dave, your quote for the 2019 Hiace lower control arm is ready. Air freight will have it on the hoist next Wednesday.',
      },
    ],
  },

  // 2. Sourcing Item (AH-P-000128) - Nissan Leaf 2021
  {
    id: 'req_128',
    referenceNumber: 'AH-P-000128',
    title: 'Headlight Assembly (RHS)',
    createdAt: '2026-08-27T10:15:00Z',
    updatedAt: '2026-08-28T07:45:00Z',
    status: 'Sourcing',
    urgency: 'Standard',
    vehicle: {
      vin: 'ZE1-042891',
      year: 2021,
      make: 'Nissan',
      model: 'Leaf',
      regoNumber: 'NPL419',
      subModel: 'e+ G 62kWh',
      engineCode: 'EM57 Electric Motor',
      chassisCode: 'ZE1',
      transmission: 'EV / Direct Drive',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_128',
        name: 'Headlight Assembly (RHS)',
        partNumber: '26010-5SK0A',
        category: 'Headlights, Tail Lights & Lighting',
        quantity: 1,
        qualityPreference: 'Genuine OEM',
        conditionPreference: 'New Only',
        conditionRequired: 'New OEM',
        vehicleSide: 'Right (Driver)',
        description: 'Auto-leveling LED type with integrated DRL. Lens and tabs must be pristine.',
      },
    ],
    assignedSpecialist: {
      name: 'Kenji Takahashi',
      role: 'Japanese OEM Procurement Specialist',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      directPhone: '+81 45 680 9182',
      email: 'kenji.t@autohub.co.jp',
    },
    trackingMilestones: [
      {
        id: 'm_128_1',
        title: 'Sourcing Initiated in Japan',
        location: 'Yokohama Hub, JP',
        timestamp: '2026-08-27 11:30',
        status: 'completed',
        description: 'Checking Nissan factory central depot and grade-A certified dismantlers.',
      },
    ],
    deliveryAddress: {
      businessName: 'Premier Motors NZ',
      street: '45 Great South Rd',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
    messages: [
      {
        id: 'msg_128_1',
        sender: 'specialist',
        senderName: 'Kenji Takahashi',
        timestamp: '2026-08-28 07:50',
        text: 'Konichiwa Dave, our Tokyo team is currently inspecting 2 genuine OEM units with verified Nissan part # 26010-5SK0A. Landed quote will be uploaded shortly.',
      },
    ],
  },

  // 3. Shipped / In Transit Item (AH-P-000119) - Subaru Outback 2018
  {
    id: 'req_119',
    referenceNumber: 'AH-P-000119',
    title: 'Rear Axle Assembly',
    createdAt: '2026-08-24T14:20:00Z',
    updatedAt: '2026-08-28T06:30:00Z',
    status: 'Shipped',
    urgency: 'Urgent',
    vehicle: {
      vin: 'JF1BS99C8K0182741',
      year: 2018,
      make: 'Subaru',
      model: 'Outback',
      regoNumber: 'LQE384',
      subModel: '2.5i Premium AWD',
      engineCode: 'FB25 2.5L Boxer',
      chassisCode: 'BS9',
      transmission: 'Lineartronic CVT',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_119',
        name: 'Rear Axle Assembly',
        partNumber: '28411-AL010',
        category: 'Transmission & Drivetrain',
        quantity: 1,
        qualityPreference: 'Reconditioned / Used',
        conditionPreference: 'Used Acceptable',
        conditionRequired: 'Grade A Used',
        vehicleSide: 'Rear',
        description: 'Complete rear axle differential assembly with CV stubs and hub carriers. Zero backlash.',
      },
    ],
    selectedFreight: 'Air Freight (Express)',
    approvedQuoteId: 'q_119_air',
    quoteOptions: [
      {
        id: 'q_119_air',
        type: 'air_express',
        carrierName: 'Air NZ Cargo Flight NZ90',
        transitDays: '3-5 Business Days',
        estimatedDeliveryDate: '2026-08-29',
        partCostNZD: 620.00,
        freightCostNZD: 120.00,
        dutiesAndBiosecurityNZD: 35.00,
        gstNZD: 65.00,
        localCourierNZD: 0.00,
        totalLandedCostNZD: 840.00,
        isRecommended: true,
        notes: 'Priority Air Freight Consignment AWB-086-94810291',
      },
    ],
    assignedSpecialist: {
      name: 'Brendon Davies',
      role: 'Senior Sourcing & Logistics Specialist',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      directPhone: '09 525 6814',
      email: 'brendon.d@autohub.co.nz',
    },
    trackingMilestones: [
      {
        id: 'm_119_1',
        title: 'Procured & Crated',
        location: 'Nagoya Export Depot, JP',
        timestamp: '2026-08-25 10:00',
        status: 'completed',
        description: 'Inspection certified, drained, and strapped to timber export pallet.',
      },
      {
        id: 'm_119_2',
        title: 'Export Customs Cleared & Departed Narita',
        location: 'Narita International Airport (NRT)',
        timestamp: '2026-08-26 19:30',
        status: 'completed',
        description: 'Air NZ Flight NZ90 departed on schedule.',
        carrier: 'Air New Zealand Cargo',
        referenceNumber: 'AWB-086-94810291',
      },
      {
        id: 'm_119_3',
        title: 'Auckland Airport Inward & Biosecurity Green-Lane',
        location: 'Auckland International Airport (AKL)',
        timestamp: '2026-08-28 06:15',
        status: 'completed',
        description: 'MPI Biosecurity released without quarantine holds.',
      },
      {
        id: 'm_119_4',
        title: 'Final Mile Courier Out for Delivery',
        location: 'Autohub Penrose Hub to 45 Great South Rd',
        timestamp: '2026-08-28 09:00',
        status: 'in-progress',
        description: 'Loaded onto express metro delivery van for Premier Motors workshop.',
      },
    ],
    deliveryAddress: {
      businessName: 'Premier Motors NZ',
      street: '45 Great South Rd',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },

  // 4. Second Awaiting Approval Item (AH-P-000124) - Ford Ranger 2022
  {
    id: 'req_124',
    referenceNumber: 'AH-P-000124',
    title: 'Bi-Turbo Intercooler Assembly & High Pressure Boost Hose',
    createdAt: '2026-08-27T11:45:00Z',
    updatedAt: '2026-08-28T10:00:00Z',
    status: 'Quoted',
    urgency: 'Standard',
    vehicle: {
      vin: 'MNAEY0FF8NW601934',
      year: 2022,
      make: 'Ford',
      model: 'Ranger',
      regoNumber: 'PRG902',
      subModel: 'Wildtrak Bi-Turbo 4x4',
      engineCode: 'YN2X 2.0L Bi-Turbo Diesel',
      chassisCode: 'PY20',
      transmission: '10-Speed Automatic',
      originMarket: 'Australia',
    },
    parts: [
      {
        id: 'p_124',
        name: 'Charge Air Cooler / Intercooler Core Assembly',
        partNumber: 'JB3G-9L440-BD',
        category: 'Cooling & Climate Control (Radiators/Condensers)',
        quantity: 1,
        qualityPreference: 'Genuine OEM',
        conditionPreference: 'New Only',
        conditionRequired: 'New OEM',
        vehicleSide: 'Front',
        description: 'Complete intercooler core with reinforced end-tanks and bracket mounting rubbers.',
      },
    ],
    quoteOptions: [
      {
        id: 'q_124_air',
        type: 'air_express',
        carrierName: 'Qantas Freight Direct Trans-Tasman',
        transitDays: '2-4 Business Days',
        estimatedDeliveryDate: '2026-09-02',
        partCostNZD: 1280.00,
        freightCostNZD: 195.00,
        dutiesAndBiosecurityNZD: 48.00,
        gstNZD: 228.45,
        localCourierNZD: 35.00,
        totalLandedCostNZD: 1786.45,
        isRecommended: true,
        notes: 'AIR FREIGHT - FASTEST (Inc. Freight, Customs, GST)',
      },
      {
        id: 'q_124_sea',
        type: 'sea_freight',
        carrierName: 'Coastal & Trans-Tasman Maritime Express',
        transitDays: '12-16 Days',
        estimatedDeliveryDate: '2026-09-14',
        partCostNZD: 1280.00,
        freightCostNZD: 75.00,
        dutiesAndBiosecurityNZD: 48.00,
        gstNZD: 210.45,
        localCourierNZD: 35.00,
        totalLandedCostNZD: 1648.45,
        isRecommended: false,
        notes: 'SEA FREIGHT - ECONOMY (Inc. Freight, Customs, GST)',
      },
    ],
    assignedSpecialist: {
      name: 'Sarah Chen',
      role: 'Trans-Tasman Procurement Lead',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
      directPhone: '09 525 6822',
      email: 'sarah.c@autohub.co.nz',
    },
    deliveryAddress: {
      businessName: 'Premier Motors NZ',
      street: '45 Great South Rd',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },

  // 5. In Transit (AH-P-000121) - Toyota Hilux 2021
  {
    id: 'req_121',
    referenceNumber: 'AH-P-000121',
    title: 'Front Right LED Headlamp & Bumper Reinforcement',
    createdAt: '2026-08-25T08:30:00Z',
    updatedAt: '2026-08-28T09:15:00Z',
    status: 'In Transit - Air',
    urgency: 'Urgent',
    vehicle: {
      vin: 'JTEBX3EJ9K1208941',
      year: 2021,
      make: 'Toyota',
      model: 'Hilux',
      regoNumber: 'HLX881',
      subModel: 'SR5 Cruiser 4WD Double Cab',
      engineCode: '1GD-FTV 2.8L Turbo Diesel',
      chassisCode: 'GUN126R',
      transmission: 'Automatic',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_121',
        name: 'Right Hand LED Headlight Assembly (OEM Projector)',
        partNumber: '81110-0KP70',
        category: 'Headlights, Tail Lights & Lighting',
        quantity: 1,
        conditionRequired: 'New OEM',
        vehicleSide: 'Right (Driver)',
      },
    ],
    selectedFreight: 'Air Freight (Express)',
    approvedQuoteId: 'q_121_air',
    quoteOptions: [
      {
        id: 'q_121_air',
        type: 'air_express',
        carrierName: 'Air New Zealand Cargo Flight NZ90',
        transitDays: '3-5 Business Days',
        estimatedDeliveryDate: '2026-08-30',
        partCostNZD: 1850.00,
        freightCostNZD: 340.00,
        dutiesAndBiosecurityNZD: 65.00,
        gstNZD: 338.25,
        localCourierNZD: 45.00,
        totalLandedCostNZD: 2638.25,
        isRecommended: true,
        notes: 'Air Cargo Narita to Auckland',
      },
    ],
    assignedSpecialist: {
      name: 'Brendon Davies',
      role: 'Senior Sourcing Lead',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      directPhone: '09 525 6814',
      email: 'brendon.d@autohub.co.nz',
    },
    deliveryAddress: {
      businessName: 'Premier Motors NZ',
      street: '45 Great South Rd',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },

  // 6. In Transit (AH-P-000125) - Nissan Leaf 2020 (Customs Clearance)
  {
    id: 'req_125',
    referenceNumber: 'AH-P-000125',
    title: 'EV On-Board Charger (OBC) Module 6.6kW',
    createdAt: '2026-08-22T14:10:00Z',
    updatedAt: '2026-08-28T08:00:00Z',
    status: 'Customs Clearance',
    urgency: 'Critical (Vehicle Off Road)',
    vehicle: {
      vin: 'ZE1-042891',
      year: 2020,
      make: 'Nissan',
      model: 'Leaf',
      regoNumber: 'MKF302',
      subModel: 'e+ G 62kWh',
      engineCode: 'EM57 Electric Motor',
      chassisCode: 'ZE1',
      transmission: 'EV / Direct Drive',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_125',
        name: 'Gen 3 High-Voltage On-Board Charger Module',
        partNumber: '292C4-5SA0A',
        category: 'EV / Hybrid Battery & Inverters',
        quantity: 1,
        conditionRequired: 'Grade A Used',
      },
    ],
    selectedFreight: 'Air Freight (Express)',
    approvedQuoteId: 'q_125_air',
    quoteOptions: [
      {
        id: 'q_125_air',
        type: 'air_express',
        carrierName: 'Nippon Cargo Airlines',
        transitDays: '4-6 Days',
        estimatedDeliveryDate: '2026-08-29',
        partCostNZD: 2450.00,
        freightCostNZD: 420.00,
        dutiesAndBiosecurityNZD: 95.00,
        gstNZD: 444.75,
        localCourierNZD: 55.00,
        totalLandedCostNZD: 3464.75,
        isRecommended: true,
        notes: 'Dangerous Goods Class 9 packaging',
      },
    ],
    deliveryAddress: {
      businessName: 'Premier Motors NZ',
      street: '45 Great South Rd',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },

  // 7. In Transit (AH-P-000120) - Honda Civic Type-R 2021
  {
    id: 'req_120',
    referenceNumber: 'AH-P-000120',
    title: 'Electric Power Steering Rack & Pinion Assembly',
    createdAt: '2026-08-23T09:30:00Z',
    updatedAt: '2026-08-28T05:00:00Z',
    status: 'In Transit - Air',
    urgency: 'Standard',
    vehicle: {
      vin: 'JHMFK8870MU102948',
      year: 2021,
      make: 'Honda',
      model: 'Civic Type-R',
      regoNumber: 'VTC918',
      subModel: 'FK8 2.0L Turbo',
      engineCode: 'K20C1 VTEC Turbo',
      chassisCode: 'FK8',
      transmission: '6-Speed Manual',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_120',
        name: 'EPS Steering Gear Box Assembly',
        partNumber: '53600-TGH-A02',
        category: 'Steering & Suspension',
        quantity: 1,
        conditionRequired: 'New OEM',
      },
    ],
    selectedFreight: 'Air Freight (Express)',
    approvedQuoteId: 'q_120_air',
    quoteOptions: [
      {
        id: 'q_120_air',
        type: 'air_express',
        carrierName: 'Singapore Airlines Cargo',
        transitDays: '4-5 Days',
        estimatedDeliveryDate: '2026-08-30',
        partCostNZD: 1980.00,
        freightCostNZD: 290.00,
        dutiesAndBiosecurityNZD: 70.00,
        gstNZD: 351.00,
        localCourierNZD: 40.00,
        totalLandedCostNZD: 2731.00,
        isRecommended: true,
        notes: 'Factory Honda Japan crate',
      },
    ],
    deliveryAddress: {
      businessName: 'Premier Motors NZ',
      street: '45 Great South Rd',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },

  // 8. In Transit (AH-P-000122) - Mazda CX-5 2020 (Consolidated Sea)
  {
    id: 'req_122',
    referenceNumber: 'AH-P-000122',
    title: 'Diesel Particulate Filter (DPF) & Catalytic Sub-Assembly',
    createdAt: '2026-08-18T16:00:00Z',
    updatedAt: '2026-08-28T04:20:00Z',
    status: 'In Transit - Sea',
    urgency: 'Standard',
    vehicle: {
      vin: 'JM7KF2W7A00192837',
      year: 2020,
      make: 'Mazda',
      model: 'CX-5',
      regoNumber: 'DPF400',
      subModel: 'Limited 2.2D AWD',
      engineCode: 'SH-VPTS 2.2L Diesel',
      chassisCode: 'KF2W',
      transmission: 'Automatic',
      originMarket: 'Japan',
    },
    parts: [
      {
        id: 'p_122',
        name: 'Genuine Mazda DPF Exhaust System with EGT Sensors',
        partNumber: 'SH17-20-50X',
        category: 'Engine & Mechanical',
        quantity: 1,
        conditionRequired: 'New OEM',
      },
    ],
    selectedFreight: 'Sea Freight (Consolidated)',
    approvedQuoteId: 'q_122_sea',
    quoteOptions: [
      {
        id: 'q_122_sea',
        type: 'sea_freight',
        carrierName: 'Toyofuji Dedicated Car Carrier & Container',
        transitDays: '18-22 Days',
        estimatedDeliveryDate: '2026-09-08',
        partCostNZD: 2150.00,
        freightCostNZD: 110.00,
        dutiesAndBiosecurityNZD: 60.00,
        gstNZD: 348.00,
        localCourierNZD: 40.00,
        totalLandedCostNZD: 2708.00,
        isRecommended: true,
        notes: 'In transit to Ports of Auckland',
      },
    ],
    deliveryAddress: {
      businessName: 'Premier Motors NZ',
      street: '45 Great South Rd',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },

  // Completed Items (14 Delivered Requests for this Month)
  {
    id: 'req_126',
    referenceNumber: 'AH-P-000126',
    title: 'Adaptive M-Sport Front Suspension Struts',
    createdAt: '2026-08-14T09:00:00Z',
    updatedAt: '2026-08-21T15:30:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: {
      vin: 'WBA8E12040K918234',
      year: 2020,
      make: 'BMW',
      model: '3 Series',
      regoNumber: 'BMW340',
      subModel: 'M340i xDrive Sedan',
      engineCode: 'B58B30 3.0L Turbo',
      chassisCode: 'G20',
      transmission: 'Sport Automatic',
      originMarket: 'Europe',
    },
    parts: [
      {
        id: 'p_126',
        name: 'Left & Right Electronic Damping Control Front Struts',
        partNumber: '31316888497',
        category: 'Steering & Suspension',
        quantity: 2,
        conditionRequired: 'New OEM',
      },
    ],
    quoteOptions: [
      {
        id: 'q_126_air',
        type: 'air_express',
        carrierName: 'Lufthansa Cargo / DHL',
        transitDays: '5 Business Days',
        estimatedDeliveryDate: '2026-08-21',
        partCostNZD: 3100.00,
        freightCostNZD: 480.00,
        dutiesAndBiosecurityNZD: 85.00,
        gstNZD: 549.75,
        localCourierNZD: 45.00,
        totalLandedCostNZD: 4259.75,
        isRecommended: true,
        notes: 'Delivered to Premier Motors workshop',
      },
    ],
    deliveryAddress: {
      businessName: 'Premier Motors NZ',
      street: '45 Great South Rd',
      suburb: 'Penrose',
      city: 'Auckland',
      postcode: '1061',
      hasForklift: true,
      hasLoadingDock: true,
    },
  },
  {
    id: 'req_110',
    referenceNumber: 'AH-P-000110',
    title: 'Dual Clutch Mechatronics Transmission Unit',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-18T14:00:00Z',
    status: 'Delivered',
    urgency: 'Urgent',
    vehicle: {
      vin: 'WVWZZZ3CZWE098214',
      year: 2019,
      make: 'Volkswagen',
      model: 'Golf R',
      regoNumber: 'VWR800',
      subModel: 'MK7.5 4Motion DSG',
      engineCode: 'EA888 2.0 TSI',
      chassisCode: '5G',
      transmission: 'Dual-Clutch / DSG',
      originMarket: 'Europe',
    },
    parts: [{ id: 'p_110', name: 'DQ381 7-Speed DSG Mechatronics Unit', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_111',
    referenceNumber: 'AH-P-000111',
    title: 'Front Quarter Panel & Bi-LED Headlamp (Left)',
    createdAt: '2026-08-08T11:00:00Z',
    updatedAt: '2026-08-16T16:20:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: { vin: 'MR0BA3CD400192847', year: 2021, make: 'Toyota', model: 'RAV4', regoNumber: 'RAV210', subModel: 'GXL Hybrid', transmission: 'e-CVT', originMarket: 'Japan' },
    parts: [{ id: 'p_111', name: 'Left Front Fender & LED Headlamp', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_112',
    referenceNumber: 'AH-P-000112',
    title: 'Turbocharger & Exhaust Manifold Gasket Kit',
    createdAt: '2026-08-05T09:15:00Z',
    updatedAt: '2026-08-12T11:45:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: { vin: 'JF1VAB09482019481', year: 2019, make: 'Subaru', model: 'WRX STI', regoNumber: 'STI999', subModel: 'Type S', transmission: '6-Speed Manual', originMarket: 'Japan' },
    parts: [{ id: 'p_112', name: 'VF49 Twin Scroll Turbo', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_113',
    referenceNumber: 'AH-P-000113',
    title: 'Brembo 6-Piston Front Brake Calipers & 380mm Rotors',
    createdAt: '2026-08-04T08:00:00Z',
    updatedAt: '2026-08-11T15:10:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: { vin: 'WP0AB2A98KS192847', year: 2019, make: 'Porsche', model: 'Macan', regoNumber: 'PCN911', subModel: 'GTS 3.0T', transmission: 'PDK Dual-Clutch', originMarket: 'Europe' },
    parts: [{ id: 'p_113', name: 'Front Caliper Kit Pair', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_114',
    referenceNumber: 'AH-P-000114',
    title: 'High Pressure Common Rail Fuel Pump',
    createdAt: '2026-08-03T14:30:00Z',
    updatedAt: '2026-08-10T10:20:00Z',
    status: 'Delivered',
    urgency: 'Urgent',
    vehicle: { vin: 'KM8K12BA9KU192837', year: 2020, make: 'Hyundai', model: 'Santa Fe', regoNumber: 'HFE401', subModel: 'Limited 2.2 CRDi', transmission: '8-Speed Automatic', originMarket: 'Domestic NZ' },
    parts: [{ id: 'p_114', name: 'CP4 Bosch Fuel Pump', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_115',
    referenceNumber: 'AH-P-000115',
    title: 'AC Compressor & Condenser Kit',
    createdAt: '2026-08-02T13:00:00Z',
    updatedAt: '2026-08-09T14:40:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: { vin: 'JTEBU4BF200192847', year: 2018, make: 'Toyota', model: 'Land Cruiser Prado', regoNumber: 'PRD891', subModel: 'VX Limited', transmission: 'Automatic', originMarket: 'Japan' },
    parts: [{ id: 'p_115', name: 'Denso AC Compressor 10S17C', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_116',
    referenceNumber: 'AH-P-000116',
    title: 'Panoramic Sunroof Glass Panel & Track Assembly',
    createdAt: '2026-08-01T10:45:00Z',
    updatedAt: '2026-08-08T16:00:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: { vin: 'WAUZZZ4M8KD019284', year: 2019, make: 'Audi', model: 'Q7', regoNumber: 'Q7AUD', subModel: 'S-Line 3.0 TDI', transmission: 'Tiptronic', originMarket: 'Europe' },
    parts: [{ id: 'p_116', name: 'Sunroof Glass Panel', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_107',
    referenceNumber: 'AH-P-000107',
    title: 'Rear Subframe & Multi-Link Suspension Arms',
    createdAt: '2026-07-28T09:00:00Z',
    updatedAt: '2026-08-07T12:00:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: { vin: 'WDC2050042F192837', year: 2018, make: 'Mercedes-Benz', model: 'C-Class', regoNumber: 'MBZ205', subModel: 'C200 AMG Line', transmission: '9G-Tronic', originMarket: 'Europe' },
    parts: [{ id: 'p_107', name: 'Rear Axle Crossmember', quantity: 1, conditionRequired: 'Grade A Used' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_108',
    referenceNumber: 'AH-P-000108',
    title: 'Electric Tailgate Struts & Controller Module',
    createdAt: '2026-07-26T11:20:00Z',
    updatedAt: '2026-08-06T15:30:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: { vin: 'JHMCR6840GC192847', year: 2017, make: 'Honda', model: 'Accord Hybrid', regoNumber: 'HCR601', subModel: 'Touring', transmission: 'e-CVT', originMarket: 'Japan' },
    parts: [{ id: 'p_108', name: 'Left/Right Power Tailgate Actuators', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_109',
    referenceNumber: 'AH-P-000109',
    title: 'Starter Generator (MHEV 48V ISG Module)',
    createdAt: '2026-07-24T14:15:00Z',
    updatedAt: '2026-08-05T17:00:00Z',
    status: 'Delivered',
    urgency: 'Critical (Vehicle Off Road)',
    vehicle: { vin: 'WBA11AK06P8192847', year: 2021, make: 'BMW', model: 'X5', regoNumber: 'X5X500', subModel: 'xDrive40i M-Sport', transmission: 'Steptronic', originMarket: 'Europe' },
    parts: [{ id: 'p_109', name: '48V Belt Starter Generator', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_106',
    referenceNumber: 'AH-P-000106',
    title: 'Front Radiator Support Core & Hood Latch Assembly',
    createdAt: '2026-07-22T08:30:00Z',
    updatedAt: '2026-08-04T13:45:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: { vin: 'KNADH4129L5192847', year: 2020, make: 'Kia', model: 'Sportage', regoNumber: 'KIA920', subModel: 'EX 2.0 AWD', transmission: '6-Speed Automatic', originMarket: 'Domestic NZ' },
    parts: [{ id: 'p_106', name: 'Radiator Support Panel Assembly', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_105_b',
    referenceNumber: 'AH-P-000105',
    title: 'Engine ECU Control Unit & Immobilizer Set',
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-08-03T11:00:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: { vin: 'JTMHU01E500192847', year: 2018, make: 'Toyota', model: 'Corolla', regoNumber: 'COR180', subModel: 'GX 1.8L Hatch', transmission: 'Super CVT-i', originMarket: 'Japan' },
    parts: [{ id: 'p_105', name: 'Denso ECM Engine Module', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
  {
    id: 'req_104_b',
    referenceNumber: 'AH-P-000104',
    title: 'Rear Bumper Reinforcement Bar & Parking Sensors',
    createdAt: '2026-07-18T15:30:00Z',
    updatedAt: '2026-08-02T14:15:00Z',
    status: 'Delivered',
    urgency: 'Standard',
    vehicle: { vin: 'MM7DJ2H1200192847', year: 2019, make: 'Mazda', model: 'Mazda 2', regoNumber: 'MZD201', subModel: 'GSX 1.5L', transmission: 'Skyactiv-Drive', originMarket: 'Japan' },
    parts: [{ id: 'p_104', name: 'Rear Impact Beam & 4x Ultrasonic Sensors', quantity: 1, conditionRequired: 'New OEM' }],
    deliveryAddress: { businessName: 'Premier Motors NZ', street: '45 Great South Rd', suburb: 'Penrose', city: 'Auckland', postcode: '1061', hasForklift: true, hasLoadingDock: true },
  },
];
