// PROCURly Operations Portal Mock Data Repository
import {
  OperationsStaffUser,
  OperationalPartRequest,
  OperationalException,
  OperationalCustomer,
  OperationalAuditEntry,
  OperationalTask,
  OperationalReportMetrics,
} from '@/types/operations';

export const INITIAL_STAFF_USERS: OperationsStaffUser[] = [
  {
    id: 'usr_michael_chen',
    name: 'Michael Chen',
    email: 'michael.chen@autohub.co.nz',
    role: 'Operations',
    roleTitle: 'Operations Manager',
    avatar: 'MC',
    department: 'Operations Command',
    phone: '+64 21 889 421',
    permissions: {
      canManageRequests: true,
      canAssignStaff: true,
      canSourceParts: true,
      canAddSupplierQuotes: true,
      canCreateCustomerQuotes: true,
      canManageProcurementOrders: true,
      canUpdateShipments: true,
      canManageExceptions: true,
      canManagePayments: true,
      canIssueRefunds: false,
      canApproveCustomers: true,
      canManageUsers: false,
      canConfigureSystem: false,
      canViewAuditLogs: true,
      canViewFinancialReports: true,
    },
  },
  {
    id: 'usr_sarah_wilson',
    name: 'Sarah Wilson',
    email: 'sarah.wilson@autohub.co.nz',
    role: 'Procurement',
    roleTitle: 'Senior Procurement Specialist',
    avatar: 'SW',
    department: 'Procurement & Sourcing',
    phone: '+64 21 554 982',
    permissions: {
      canManageRequests: true,
      canAssignStaff: false,
      canSourceParts: true,
      canAddSupplierQuotes: true,
      canCreateCustomerQuotes: true,
      canManageProcurementOrders: true,
      canUpdateShipments: true,
      canManageExceptions: true,
      canManagePayments: false,
      canIssueRefunds: false,
      canApproveCustomers: false,
      canManageUsers: false,
      canConfigureSystem: false,
      canViewAuditLogs: true,
      canViewFinancialReports: false,
    },
  },
  {
    id: 'usr_james_taylor',
    name: 'James Taylor',
    email: 'james.taylor@autohub.co.nz',
    role: 'Finance',
    roleTitle: 'Finance & Accounts Controller',
    avatar: 'JT',
    department: 'Finance & Trade Credit',
    phone: '+64 21 332 119',
    permissions: {
      canManageRequests: true,
      canAssignStaff: false,
      canSourceParts: false,
      canAddSupplierQuotes: false,
      canCreateCustomerQuotes: false,
      canManageProcurementOrders: false,
      canUpdateShipments: false,
      canManageExceptions: true,
      canManagePayments: true,
      canIssueRefunds: true,
      canApproveCustomers: true,
      canManageUsers: false,
      canConfigureSystem: false,
      canViewAuditLogs: true,
      canViewFinancialReports: true,
    },
  },
  {
    id: 'usr_admin',
    name: 'Admin User',
    email: 'admin@autohub.co.nz',
    role: 'Administrator',
    roleTitle: 'Systems Administrator',
    avatar: 'AD',
    department: 'Executive / IT',
    phone: '+64 9 525 0000',
    permissions: {
      canManageRequests: true,
      canAssignStaff: true,
      canSourceParts: true,
      canAddSupplierQuotes: true,
      canCreateCustomerQuotes: true,
      canManageProcurementOrders: true,
      canUpdateShipments: true,
      canManageExceptions: true,
      canManagePayments: true,
      canIssueRefunds: true,
      canApproveCustomers: true,
      canManageUsers: true,
      canConfigureSystem: true,
      canViewAuditLogs: true,
      canViewFinancialReports: true,
    },
  },
];

export const INITIAL_CUSTOMERS: OperationalCustomer[] = [
  {
    id: 'cust_autocare',
    businessName: 'AutoCare Auckland Limited',
    tradingName: 'AutoCare Auckland',
    nzbn: '9429041234567',
    businessType: 'Independent Service Centre & Fleet Repairer',
    status: 'Approved',
    submittedDate: '2024-03-15',
    approvedDate: '2024-03-16',
    primaryContact: {
      name: 'James Wilson',
      email: 'james@autocareauckland.co.nz',
      phone: '021 555 8921',
      role: 'Managing Director / Workshop Owner',
    },
    accountsContact: {
      name: 'Sarah Jenkins',
      email: 'accounts@autocareauckland.co.nz',
      phone: '09 525 6810',
    },
    deliveryContact: {
      name: 'Workshop Parts Team',
      phone: '09 525 1100',
    },
    creditStatus: 'Approved Trade Account (20th Month Following)',
    creditLimitNZD: 50000,
    outstandingBalanceNZD: 485,
    activeRequestsCount: 8,
    openOrdersCount: 4,
    branches: [
      {
        id: 'br_1',
        name: 'Auckland Main Workshop',
        street: '12 Example Street',
        suburb: 'Penrose',
        city: 'Auckland',
        postcode: '1061',
        isPrimary: true,
      },
      {
        id: 'br_2',
        name: 'North Shore Service Hub',
        street: '88 Bush Road',
        suburb: 'Rosedale',
        city: 'Auckland',
        postcode: '0632',
        isPrimary: false,
      },
      {
        id: 'br_3',
        name: 'Manukau Fleet Facility',
        street: '14 Cavendish Drive',
        suburb: 'Manukau',
        city: 'Auckland',
        postcode: '2104',
        isPrimary: false,
      },
    ],
  },
  {
    id: 'cust_central',
    businessName: 'Central Motors Wellington Ltd',
    tradingName: 'Central Motors',
    nzbn: '9429049876543',
    businessType: 'Franchised Dealership Group Service',
    status: 'Approved',
    submittedDate: '2024-05-10',
    approvedDate: '2024-05-11',
    primaryContact: {
      name: 'John Smith',
      email: 'john.smith@centralmotors.co.nz',
      phone: '027 444 9912',
      role: 'Service Operations Director',
    },
    accountsContact: {
      name: 'Emma Watson',
      email: 'accounts@centralmotors.co.nz',
      phone: '04 801 5500',
    },
    deliveryContact: {
      name: 'Central Parts Inwards',
      phone: '04 801 5520',
    },
    creditStatus: 'Approved Trade Account (20th Month Following)',
    creditLimitNZD: 35000,
    outstandingBalanceNZD: 720,
    activeRequestsCount: 5,
    openOrdersCount: 2,
    branches: [
      {
        id: 'br_cm_1',
        name: 'Wellington Central Hub',
        street: '142 Vivian Street',
        suburb: 'Te Aro',
        city: 'Wellington',
        postcode: '6011',
        isPrimary: true,
      },
    ],
  },
  {
    id: 'cust_west',
    businessName: 'West Auto Commercial Group Ltd',
    tradingName: 'West Auto',
    nzbn: '9429045551234',
    businessType: 'Heavy & Light Commercial Fleet Specialist',
    status: 'Approved',
    submittedDate: '2023-11-20',
    approvedDate: '2023-11-21',
    primaryContact: {
      name: 'Liam Vance',
      email: 'liam@westauto.co.nz',
      phone: '021 777 4321',
      role: 'Fleet Maintenance Manager',
    },
    accountsContact: {
      name: 'Finance Desk',
      email: 'finance@westauto.co.nz',
      phone: '09 838 9000',
    },
    deliveryContact: {
      name: 'Bay 4 Reception',
      phone: '09 838 9015',
    },
    creditStatus: 'Approved Trade Account (20th Month Following)',
    creditLimitNZD: 60000,
    outstandingBalanceNZD: 310,
    activeRequestsCount: 11,
    openOrdersCount: 6,
    branches: [
      {
        id: 'br_wa_1',
        name: 'Henderson Fleet Facility',
        street: '340 Lincoln Road',
        suburb: 'Henderson',
        city: 'Auckland',
        postcode: '0610',
        isPrimary: true,
      },
    ],
  },
  {
    id: 'cust_northshore',
    businessName: 'North Shore European Specialist Ltd',
    tradingName: 'North Shore Automotive',
    nzbn: '9429048889999',
    businessType: 'European & Japanese Prestige Repairer',
    status: 'Approved',
    submittedDate: '2024-02-01',
    approvedDate: '2024-02-02',
    primaryContact: {
      name: 'Dave Stewart',
      email: 'dave@northshoreauto.co.nz',
      phone: '021 998 1234',
      role: 'Head of Workshop',
    },
    accountsContact: {
      name: 'Accounts Team',
      email: 'payables@northshoreauto.co.nz',
      phone: '09 489 1230',
    },
    deliveryContact: {
      name: 'Parts Desk',
      phone: '09 489 1234',
    },
    creditStatus: 'Approved Trade Account (20th Month Following)',
    creditLimitNZD: 25000,
    outstandingBalanceNZD: 1150,
    activeRequestsCount: 4,
    openOrdersCount: 1,
    branches: [
      {
        id: 'br_ns_1',
        name: 'Takapuna Service Workshop',
        street: '15 Barrys Point Road',
        suburb: 'Takapuna',
        city: 'Auckland',
        postcode: '0622',
        isPrimary: true,
      },
    ],
  },
  {
    id: 'cust_wellington',
    businessName: 'Wellington Commercial Motors Ltd',
    tradingName: 'Wellington Commercial Motors',
    nzbn: '9429043334444',
    businessType: 'Commercial Van & Light Truck Repair Centre',
    status: 'Approved',
    submittedDate: '2024-04-18',
    approvedDate: '2024-04-19',
    primaryContact: {
      name: 'Craig Miller',
      email: 'craig@wcmotors.co.nz',
      phone: '027 555 1290',
      role: 'General Manager',
    },
    accountsContact: {
      name: 'Accounts Office',
      email: 'accounts@wcmotors.co.nz',
      phone: '04 568 2000',
    },
    deliveryContact: {
      name: 'Inwards Goods Bay',
      phone: '04 568 2005',
    },
    creditStatus: 'Approved Trade Account (20th Month Following)',
    creditLimitNZD: 40000,
    outstandingBalanceNZD: 5155,
    activeRequestsCount: 7,
    openOrdersCount: 3,
    branches: [
      {
        id: 'br_wcm_1',
        name: 'Petone Heavy Commercial Hub',
        street: '89 Hutt Road',
        suburb: 'Petone',
        city: 'Lower Hutt',
        postcode: '5012',
        isPrimary: true,
      },
    ],
  },
  // Pending Approval Customers
  {
    id: 'cust_pending_apex',
    businessName: 'Apex Fleet Logistics & Repairs Ltd',
    tradingName: 'Apex Fleet Services',
    nzbn: '9429047771122',
    businessType: 'National Logistics Fleet Repairer',
    status: 'Pending Approval',
    submittedDate: '2026-08-28',
    primaryContact: {
      name: 'Mark Davies',
      email: 'mark.davies@apexfleet.co.nz',
      phone: '021 889 0011',
      role: 'Chief Technical Officer',
    },
    accountsContact: {
      name: 'Helen Ross',
      email: 'accounts@apexfleet.co.nz',
      phone: '09 276 4000',
    },
    deliveryContact: {
      name: 'Goods Inward Dept',
      phone: '09 276 4010',
    },
    creditStatus: 'Pending Review',
    creditLimitNZD: 50000,
    outstandingBalanceNZD: 0,
    activeRequestsCount: 0,
    openOrdersCount: 0,
    branches: [
      {
        id: 'br_apex_1',
        name: 'Airport Logistics Hub',
        street: '5 Freight Place',
        suburb: 'Mangere',
        city: 'Auckland',
        postcode: '2022',
        isPrimary: true,
      },
    ],
    notes: 'Submitted trade credit application for NZ$50,000. 3 trade references attached.',
  },
  {
    id: 'cust_pending_euro',
    businessName: 'Southern Euro Diagnostics Ltd',
    tradingName: 'EuroTech Christchurch',
    nzbn: '9429046663344',
    businessType: 'Specialist European Auto Workshop',
    status: 'Pending Approval',
    submittedDate: '2026-08-27',
    primaryContact: {
      name: 'Klaus Richter',
      email: 'klaus@eurotechchch.co.nz',
      phone: '027 123 9876',
      role: 'Workshop Principal',
    },
    accountsContact: {
      name: 'Finance Desk',
      email: 'accounts@eurotechchch.co.nz',
      phone: '03 365 4000',
    },
    deliveryContact: {
      name: 'Parts Desk',
      phone: '03 365 4005',
    },
    creditStatus: 'Pending Review',
    creditLimitNZD: 30000,
    outstandingBalanceNZD: 0,
    activeRequestsCount: 0,
    openOrdersCount: 0,
    branches: [
      {
        id: 'br_euro_1',
        name: 'Christchurch Central Workshop',
        street: '210 Moorhouse Avenue',
        suburb: 'Sydenham',
        city: 'Christchurch',
        postcode: '8011',
        isPrimary: true,
      },
    ],
    notes: 'Specialises in VAG / BMW / Mercedes procurement. Awaiting credit check verification.',
  },
];

export const INITIAL_REQUESTS: OperationalPartRequest[] = [
  // 1. Primary Highlight Request: AH-P-000123
  {
    id: 'req_000123',
    referenceNumber: 'AH-P-000123',
    customerName: 'AutoCare Auckland',
    customerId: 'cust_autocare',
    customerEmail: 'james@autocareauckland.co.nz',
    customerPhone: '021 555 8921',
    deliveryBranch: 'Auckland Main Workshop (Penrose)',
    submittedDate: '2026-08-28 08:30',
    updatedAt: '2026-08-28 10:42',
    status: 'Awaiting Customer Approval',
    priority: 'Normal',
    ownerName: 'Michael Chen',
    ownerId: 'usr_michael_chen',
    vehicle: {
      vin: 'TRH200-0198421',
      year: 2019,
      make: 'Toyota',
      model: 'Hiace',
      rego: 'NZE412',
      subModel: 'DX Long Wheelbase 2.0L Petrol',
      engineCode: '1TR-FE',
      chassisCode: 'TRH200V',
      transmission: '6-Speed Automatic',
    },
    part: {
      name: 'Left Front Lower Control Arm',
      partNumber: '48069-26150',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      conditionPreference: 'New',
      vehicleSide: 'Left (Passenger)',
      description: 'Complete lower arm assembly with pre-pressed heavy-duty ball joint and rear compliance bush.',
      images: [
        'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&auto=format&fit=crop&q=60',
      ],
    },
    sourcing: {
      status: 'Supplier Selected',
      selectedSupplierQuoteId: 'sq_123_a',
      supplierQuotes: [
        {
          id: 'sq_123_a',
          supplierId: 'sup_tokyo_parts',
          supplierName: 'Supplier A (Tokyo Auto Spares)',
          supplierCode: 'TAS-JP',
          partDescription: 'Toyota OEM Left Front Lower Arm Assembly (48069-26150)',
          partCostNZD: 280,
          availability: '1–3 Days',
          estimatedDispatchDays: '3 days',
          supplierFreightNZD: 70,
          supplierHandlingNZD: 20,
          totalSupplierCostNZD: 370,
          notes: 'Factory sealed Toyota packaging. Yokohama export hub dispatch.',
          isSelected: true,
          quotedAt: '2026-08-28 09:45',
          quotedBy: 'Sarah Wilson',
          validUntil: '2026-09-04',
        },
        {
          id: 'sq_123_b',
          supplierId: 'sup_osaka_autoparts',
          supplierName: 'Supplier B (Osaka Genuine Components)',
          supplierCode: 'OGC-JP',
          partDescription: 'Toyota OEM Genuine Lower Arm L/H',
          partCostNZD: 310,
          availability: 'In Stock',
          estimatedDispatchDays: 'Same day',
          supplierFreightNZD: 55,
          supplierHandlingNZD: 15,
          totalSupplierCostNZD: 380,
          notes: 'Immediate dispatch available via Kansai Air Hub.',
          isSelected: false,
          quotedAt: '2026-08-28 09:50',
          quotedBy: 'Sarah Wilson',
          validUntil: '2026-09-02',
        },
        {
          id: 'sq_123_c',
          supplierId: 'sup_nagoya_distribution',
          supplierName: 'Supplier C (Nagoya Parts Distribution)',
          supplierCode: 'NPD-JP',
          partDescription: 'OEM Spec Lower Control Arm LHS Complete',
          partCostNZD: 260,
          availability: '4–7 Days',
          estimatedDispatchDays: '7 days',
          supplierFreightNZD: 90,
          supplierHandlingNZD: 25,
          totalSupplierCostNZD: 375,
          notes: 'Requires consolidation at central Nagoya depot.',
          isSelected: false,
          quotedAt: '2026-08-28 10:05',
          quotedBy: 'Sarah Wilson',
          validUntil: '2026-09-01',
        },
      ],
    },
    landedCost: {
      supplierCostNZD: 280,
      supplierFreightNZD: 70,
      handlingCostNZD: 20,
      otherCostsNZD: 15,
      totalInternalCostNZD: 385,
      marginPercentage: 12.99,
      marginAmountNZD: 50,
      finalCustomerPriceNZD: 485,
      dutiesAndBiosecurityNZD: 0,
      localCourierNZD: 15,
      gstNZD: 63.26,
    },
    customerQuote: {
      quoteNumber: 'QUO-000123-v3',
      version: 3,
      status: 'Sent',
      validUntil: '2026-09-15',
      createdAt: '2026-08-28 10:40',
      sentAt: '2026-08-28 10:42',
      sentBy: 'Michael Chen',
      items: [
        {
          id: 'qi_1',
          description: 'Toyota Genuine OEM Left Front Lower Control Arm (TRH200 Hiace)',
          quantity: 1,
          unitPriceNZD: 350,
          totalPriceNZD: 350,
        },
        {
          id: 'qi_2',
          description: 'Priority Air Freight & Express Transit Handling (Japan to NZ)',
          quantity: 1,
          unitPriceNZD: 85,
          totalPriceNZD: 85,
        },
        {
          id: 'qi_3',
          description: 'Autohub Verified Fitment & Biosecurity Surcharge',
          quantity: 1,
          unitPriceNZD: 50,
          totalPriceNZD: 50,
        },
      ],
      freightOptions: [
        {
          id: 'fo_air',
          freightType: 'Air Freight',
          transitEstimate: '5–8 business days',
          isRecommended: true,
          partCostNZD: 350,
          freightCostNZD: 85,
          procurementServiceNZD: 50,
          totalNZD: 485,
        },
        {
          id: 'fo_sea',
          freightType: 'Sea Freight',
          transitEstimate: '18–30 business days',
          isRecommended: false,
          partCostNZD: 350,
          freightCostNZD: 35,
          procurementServiceNZD: 25,
          totalNZD: 410,
        },
      ],
      selectedFreightId: 'fo_air',
      totalAmountNZD: 485,
      termsVersion: 'v1.2',
    },
    payment: {
      paymentNumber: 'PAY-00123',
      amountNZD: 485,
      status: 'Awaiting Payment',
      dueDate: '2026-09-20',
      invoiceNumber: 'INV-2026-0941',
      creditApproved: true,
    },
    timeline: [
      {
        id: 'tl_1',
        stage: 'Request Submitted',
        timestamp: '2026-08-28 08:30',
        user: 'James Wilson (AutoCare)',
        action: 'Customer submitted procurement request via Trade Portal',
        isCompleted: true,
      },
      {
        id: 'tl_2',
        stage: 'Assigned',
        timestamp: '2026-08-28 08:45',
        user: 'Michael Chen (Operations)',
        action: 'Request assigned to Michael Chen',
        note: 'High priority customer with urgent fleet commitment.',
        isCompleted: true,
      },
      {
        id: 'tl_3',
        stage: 'Sourcing Initiated',
        timestamp: '2026-08-28 09:15',
        user: 'Sarah Wilson (Procurement)',
        action: 'Dispatched RFQ to Tokyo Auto Spares & Osaka Genuine Hubs',
        isCompleted: true,
      },
      {
        id: 'tl_4',
        stage: 'Supplier Quotes Added',
        timestamp: '2026-08-28 10:10',
        user: 'Sarah Wilson (Procurement)',
        action: 'Compared 3 supplier options. Selected Supplier A (TAS-JP) at NZ$370 total landed internal cost.',
        isCompleted: true,
      },
      {
        id: 'tl_5',
        stage: 'Customer Quote Created & Sent',
        timestamp: '2026-08-28 10:42',
        user: 'Michael Chen (Operations)',
        action: 'Generated Quote QUO-000123-v3 for NZ$485.00. Sent to James Wilson.',
        isCompleted: true,
      },
      {
        id: 'tl_6',
        stage: 'Awaiting Customer Approval',
        timestamp: '2026-08-28 10:42',
        user: 'System',
        action: 'Quote pending customer authorization on Trade Portal',
        isCompleted: false,
        isCurrent: true,
      },
      {
        id: 'tl_7',
        stage: 'Payment & Trade Settlement',
        timestamp: 'Pending',
        user: 'Finance Desk',
        action: 'Trade account billing or card checkout confirmation',
        isCompleted: false,
      },
      {
        id: 'tl_8',
        stage: 'Procurement Order',
        timestamp: 'Pending',
        user: 'Procurement Desk',
        action: 'Purchase Order dispatch to Tokyo Auto Spares',
        isCompleted: false,
      },
      {
        id: 'tl_9',
        stage: 'International Shipping & Customs',
        timestamp: 'Pending',
        user: 'Logistics Control',
        action: 'Air freight dispatch via Narita Air Hub',
        isCompleted: false,
      },
      {
        id: 'tl_10',
        stage: 'Final Delivery',
        timestamp: 'Pending',
        user: 'Local Courier',
        action: 'Courier delivery to Penrose workshop',
        isCompleted: false,
      },
    ],
    messages: [
      {
        id: 'msg_1',
        requestId: 'req_000123',
        authorId: 'cust_autocare',
        authorName: 'James Wilson',
        authorRole: 'Customer',
        timestamp: '2026-08-28 08:35',
        content: 'Hi Autohub team, can you please confirm whether this lower control arm comes with the rear compliance bush pre-installed? Vehicle is off-road awaiting parts.',
        isInternalOnly: false,
      },
      {
        id: 'msg_2',
        requestId: 'req_000123',
        authorId: 'usr_sarah_wilson',
        authorName: 'Sarah Wilson',
        authorRole: 'Procurement',
        timestamp: '2026-08-28 09:30',
        content: 'Tokyo supplier TAS-JP confirmed OEM Toyota assembly 48069-26150 has full factory pre-pressed bush and ball joint included. Stock is ready to ship.',
        isInternalOnly: true, // INTERNAL NOTE
      },
      {
        id: 'msg_3',
        requestId: 'req_000123',
        authorId: 'usr_michael_chen',
        authorName: 'Michael Chen',
        authorRole: 'Operations',
        timestamp: '2026-08-28 09:40',
        content: 'Hi James, confirmed that this is the factory complete assembly with pre-pressed heavy-duty ball joint and rear bush. We have prepared the quote for your review.',
        isInternalOnly: false,
      },
    ],
    documents: [
      {
        id: 'doc_1',
        title: 'Customer Quotation QUO-000123-v3.pdf',
        category: 'Customer Quotes',
        requestId: 'req_000123',
        requestNumber: 'AH-P-000123',
        customerName: 'AutoCare Auckland',
        date: '2026-08-28',
        fileFormat: 'PDF',
        fileSizeBytes: 245000,
        fileSizeFormatted: '245 KB',
        uploadedBy: 'Michael Chen',
        isInternalOnly: false,
      },
      {
        id: 'doc_2',
        title: 'Supplier_TAS_Tokyo_Quote_48069.pdf',
        category: 'Supplier Quotes',
        requestId: 'req_000123',
        requestNumber: 'AH-P-000123',
        supplierName: 'Tokyo Auto Spares',
        date: '2026-08-28',
        fileFormat: 'PDF',
        fileSizeBytes: 180000,
        fileSizeFormatted: '180 KB',
        uploadedBy: 'Sarah Wilson',
        isInternalOnly: true, // Internal only
      },
      {
        id: 'doc_3',
        title: 'VIN_Plate_TRH200_Inspection.jpg',
        category: 'Customer Attachments',
        requestId: 'req_000123',
        requestNumber: 'AH-P-000123',
        date: '2026-08-28',
        fileFormat: 'JPG',
        fileSizeBytes: 1420000,
        fileSizeFormatted: '1.4 MB',
        uploadedBy: 'James Wilson',
        isInternalOnly: false,
      },
    ],
  },

  // 2. Request AH-P-000122: Mazda CX-5 Headlamp (Sourcing in progress)
  {
    id: 'req_000122',
    referenceNumber: 'AH-P-000122',
    customerName: 'Central Motors',
    customerId: 'cust_central',
    customerEmail: 'john.smith@centralmotors.co.nz',
    customerPhone: '027 444 9912',
    deliveryBranch: 'Wellington Central Hub',
    submittedDate: '2026-08-28 09:10',
    updatedAt: '2026-08-28 09:30',
    status: 'Sourcing',
    priority: 'Urgent',
    ownerName: 'Sarah Wilson',
    ownerId: 'usr_sarah_wilson',
    vehicle: {
      vin: 'KF2P-204199',
      year: 2021,
      make: 'Mazda',
      model: 'CX-5',
      rego: 'MZD991',
      subModel: 'Limited AWD 2.2L Diesel Turbo',
      engineCode: 'SH-VPTS',
      chassisCode: 'KF2P',
    },
    part: {
      name: 'Left Front Adaptive LED Headlamp Assembly',
      partNumber: 'KB8A-51-041B',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      conditionPreference: 'New',
      vehicleSide: 'Left (Passenger)',
      description: 'Full Adaptive LED headlamp unit with integrated control module and AFS sensor harness.',
    },
    sourcing: {
      status: 'In Progress',
      supplierQuotes: [
        {
          id: 'sq_122_a',
          supplierId: 'sup_hiroshima_oem',
          supplierName: 'Hiroshima Genuine Spares',
          supplierCode: 'HGS-JP',
          partDescription: 'Mazda OEM AFS Headlamp Left Hand (KB8A-51-041B)',
          partCostNZD: 640,
          availability: '1–3 Days',
          estimatedDispatchDays: '2 days',
          supplierFreightNZD: 85,
          supplierHandlingNZD: 25,
          totalSupplierCostNZD: 750,
          quotedAt: '2026-08-28 09:25',
          quotedBy: 'Sarah Wilson',
          validUntil: '2026-09-03',
        },
      ],
    },
    payment: {
      paymentNumber: 'PAY-00122',
      amountNZD: 720,
      status: 'Payment Pending',
      dueDate: '2026-09-20',
      creditApproved: true,
    },
    timeline: [
      {
        id: 'tl_122_1',
        stage: 'Request Submitted',
        timestamp: '2026-08-28 09:10',
        user: 'John Smith (Central Motors)',
        action: 'Urgent request for insurance repair customer',
        isCompleted: true,
      },
      {
        id: 'tl_122_2',
        stage: 'Sourcing In Progress',
        timestamp: '2026-08-28 09:30',
        user: 'Sarah Wilson',
        action: 'Checking stock across Japan and Singapore distributor networks',
        isCompleted: false,
        isCurrent: true,
      },
    ],
    messages: [
      {
        id: 'msg_122_1',
        requestId: 'req_000122',
        authorId: 'usr_sarah_wilson',
        authorName: 'Sarah Wilson',
        authorRole: 'Procurement',
        timestamp: '2026-08-28 09:32',
        content: 'Contacting Hiroshima supplier to verify if daytime running light ballast module is included.',
        isInternalOnly: true,
      },
    ],
    documents: [],
  },

  // 3. Request AH-P-000121: Ford Ranger Door Mirror (In Transit)
  {
    id: 'req_000121',
    referenceNumber: 'AH-P-000121',
    customerName: 'West Auto',
    customerId: 'cust_west',
    customerEmail: 'liam@westauto.co.nz',
    customerPhone: '021 777 4321',
    deliveryBranch: 'Henderson Fleet Facility',
    submittedDate: '2026-08-27 11:20',
    updatedAt: '2026-08-28 08:15',
    status: 'In Transit',
    priority: 'Normal',
    ownerName: 'James Taylor',
    ownerId: 'usr_james_taylor',
    vehicle: {
      vin: 'MNBUMFF50LW129481',
      year: 2020,
      make: 'Ford',
      model: 'Ranger',
      rego: 'WST401',
      subModel: 'Wildtrak 4x4 2.0L Bi-Turbo',
      engineCode: 'YN2X',
    },
    part: {
      name: 'Right Hand Power Heated Door Mirror (Chrome / Indicator / Blind Spot)',
      partNumber: 'JB3B-17682-CE',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      conditionPreference: 'New',
      vehicleSide: 'Right (Driver)',
    },
    sourcing: {
      status: 'Supplier Selected',
      selectedSupplierQuoteId: 'sq_121_a',
      supplierQuotes: [
        {
          id: 'sq_121_a',
          supplierId: 'sup_bangkok_oem',
          supplierName: 'Bangkok Ford Auto Hub',
          supplierCode: 'BFA-TH',
          partDescription: 'Ford OEM Wildtrak RH Mirror Assembly with BLIS',
          partCostNZD: 410,
          availability: 'In Stock',
          estimatedDispatchDays: '1 day',
          supplierFreightNZD: 65,
          supplierHandlingNZD: 20,
          totalSupplierCostNZD: 495,
          isSelected: true,
          quotedAt: '2026-08-27 13:00',
          quotedBy: 'Sarah Wilson',
          validUntil: '2026-09-10',
        },
      ],
    },
    landedCost: {
      supplierCostNZD: 410,
      supplierFreightNZD: 65,
      handlingCostNZD: 20,
      otherCostsNZD: 15,
      totalInternalCostNZD: 510,
      marginPercentage: 15,
      marginAmountNZD: 90,
      finalCustomerPriceNZD: 720,
      dutiesAndBiosecurityNZD: 0,
      localCourierNZD: 15,
      gstNZD: 93.91,
    },
    procurementOrder: {
      orderNumber: 'ORD-000121',
      supplierName: 'Bangkok Ford Auto Hub',
      status: 'Dispatched',
      orderedAt: '2026-08-27 15:30',
      expectedShippingFacilityDate: '2026-08-28',
      supplierOrderRef: 'BFA-ORD-9921',
    },
    shipment: {
      shipmentNumber: 'SHP-000121',
      carrier: 'DHL Express',
      trackingCode: 'DHL-NZ-9428-1192',
      freightMethod: 'Air Freight',
      status: 'In Transit',
      originHub: 'Suvarnabhumi BKK Hub (Thailand)',
      destinationHub: 'Auckland Gateway Hub (AKL)',
      etaDate: '2026-09-02',
      milestones: [
        {
          title: 'Procurement Completed',
          location: 'Bangkok Distribution Centre',
          timestamp: '2026-08-27 16:00',
          status: 'completed',
        },
        {
          title: 'Received at Shipping Facility',
          location: 'Autohub Bangkok Export Hub',
          timestamp: '2026-08-28 04:30',
          status: 'completed',
        },
        {
          title: 'Dispatched on Flight TG491',
          location: 'Suvarnabhumi International Airport',
          timestamp: '2026-08-28 08:15',
          status: 'completed',
        },
        {
          title: 'In Transit to Auckland',
          location: 'Pacific Trans-Air Corridor',
          timestamp: '2026-08-28 11:00',
          status: 'in-progress',
          note: 'ETA AKL Airport: 2026-08-29 06:45 AM',
        },
        {
          title: 'Arrived in New Zealand',
          location: 'Auckland International Airport (AKL)',
          timestamp: 'Pending',
          status: 'pending',
        },
        {
          title: 'Customs & MPI Biosecurity Clearance',
          location: 'Auckland Customs Freight Inspection Facility',
          timestamp: 'Pending',
          status: 'pending',
        },
        {
          title: 'Out for Delivery (CourierPost Express)',
          location: 'West Auckland Delivery Depot',
          timestamp: 'Pending',
          status: 'pending',
        },
        {
          title: 'Delivered',
          location: 'West Auto Henderson Facility',
          timestamp: 'Pending',
          status: 'pending',
        },
      ],
    },
    payment: {
      paymentNumber: 'PAY-00121',
      amountNZD: 720,
      status: 'Payment Received',
      dueDate: '2026-09-20',
      paidAt: '2026-08-27 14:00',
      method: 'Approved Trade Credit (20th Mth Following)',
      invoiceNumber: 'INV-2026-0938',
      creditApproved: true,
    },
    timeline: [
      {
        id: 'tl_121_1',
        stage: 'Request Submitted',
        timestamp: '2026-08-27 11:20',
        user: 'Liam Vance',
        action: 'Submitted mirror replacement request',
        isCompleted: true,
      },
      {
        id: 'tl_121_2',
        stage: 'Customer Approved & In Transit',
        timestamp: '2026-08-27 14:15',
        user: 'Liam Vance',
        action: 'Accepted quote online. Express air dispatch underway.',
        isCompleted: true,
      },
    ],
    messages: [],
    documents: [],
  },

  // 4. Request AH-P-000118: Hilux Turbocharger (Quote Expiring Attention!)
  {
    id: 'req_000118',
    referenceNumber: 'AH-P-000118',
    customerName: 'North Shore Automotive',
    customerId: 'cust_northshore',
    customerEmail: 'dave@northshoreauto.co.nz',
    customerPhone: '021 998 1234',
    deliveryBranch: 'Takapuna Service Workshop',
    submittedDate: '2026-08-26 14:00',
    updatedAt: '2026-08-28 09:45',
    status: 'Quote Ready',
    priority: 'High',
    ownerName: 'Sarah Wilson',
    ownerId: 'usr_sarah_wilson',
    vehicle: {
      vin: 'GUN126-5019283',
      year: 2022,
      make: 'Toyota',
      model: 'Hilux',
      rego: 'HLX920',
      subModel: 'SR5 Cruiser 4WD Double Cab 2.8L',
      engineCode: '1GD-FTV',
    },
    part: {
      name: 'Genuine Variable Nozzle Turbocharger (VNT) Assembly',
      partNumber: '17201-11080',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      conditionPreference: 'New',
    },
    sourcing: {
      status: 'Supplier Selected',
      selectedSupplierQuoteId: 'sq_118_a',
      supplierQuotes: [
        {
          id: 'sq_118_a',
          supplierId: 'sup_tokyo_parts',
          supplierName: 'Tokyo Auto Spares',
          supplierCode: 'TAS-JP',
          partDescription: 'Toyota 1GD-FTV OEM Turbocharger with Actuator',
          partCostNZD: 1450,
          availability: 'In Stock',
          estimatedDispatchDays: '1 day',
          supplierFreightNZD: 120,
          supplierHandlingNZD: 35,
          totalSupplierCostNZD: 1605,
          notes: 'Special promotional batch rate. Supplier quote locks expire at 5:00 PM today.',
          isSelected: true,
          quotedAt: '2026-08-26 16:00',
          quotedBy: 'Sarah Wilson',
          validUntil: '2026-08-28', // Expiring today!
        },
      ],
    },
    landedCost: {
      supplierCostNZD: 1450,
      supplierFreightNZD: 120,
      handlingCostNZD: 35,
      otherCostsNZD: 25,
      totalInternalCostNZD: 1630,
      marginPercentage: 14.7,
      marginAmountNZD: 250,
      finalCustomerPriceNZD: 2150,
      dutiesAndBiosecurityNZD: 0,
      localCourierNZD: 25,
      gstNZD: 280.43,
    },
    customerQuote: {
      quoteNumber: 'QUO-000118-v1',
      version: 1,
      status: 'Sent',
      validUntil: '2026-08-28',
      createdAt: '2026-08-27 09:00',
      items: [
        {
          id: 'qi_118_1',
          description: 'Toyota Genuine OEM 1GD-FTV Turbocharger Unit',
          quantity: 1,
          unitPriceNZD: 1850,
          totalPriceNZD: 1850,
        },
        {
          id: 'qi_118_2',
          description: 'Express Air Freight with Heavy Component Protection',
          quantity: 1,
          unitPriceNZD: 200,
          totalPriceNZD: 200,
        },
        {
          id: 'qi_118_3',
          description: 'Autohub Import Compliance & Biosecurity Fee',
          quantity: 1,
          unitPriceNZD: 100,
          totalPriceNZD: 100,
        },
      ],
      freightOptions: [
        {
          id: 'fo_air_118',
          freightType: 'Air Freight',
          transitEstimate: '4–6 business days',
          isRecommended: true,
          partCostNZD: 1850,
          freightCostNZD: 200,
          procurementServiceNZD: 100,
          totalNZD: 2150,
        },
      ],
      totalAmountNZD: 2150,
      termsVersion: 'v1.2',
    },
    payment: {
      paymentNumber: 'PAY-00118',
      amountNZD: 2150,
      status: 'Awaiting Payment',
      dueDate: '2026-09-20',
      creditApproved: true,
    },
    timeline: [
      {
        id: 'tl_118_1',
        stage: 'Supplier Quote Expiring Alert',
        timestamp: '2026-08-28 09:00',
        user: 'System Alert',
        action: 'Supplier quote locking price NZ$1,605 expires in 7 hours.',
        isCompleted: false,
        isCurrent: true,
      },
    ],
    messages: [],
    documents: [],
  },

  // 5. Request AH-P-000104: Mazda CX-5 Tailgate (Logistics Exception LOG-00042)
  {
    id: 'req_000104',
    referenceNumber: 'AH-P-000104',
    customerName: 'Wellington Commercial Motors',
    customerId: 'cust_wellington',
    customerEmail: 'craig@wcmotors.co.nz',
    customerPhone: '027 555 1290',
    deliveryBranch: 'Petone Heavy Commercial Hub',
    submittedDate: '2026-08-22 10:00',
    updatedAt: '2026-08-28 07:30',
    status: 'Logistics Exception',
    priority: 'High',
    ownerName: 'Sarah Wilson',
    ownerId: 'usr_sarah_wilson',
    vehicle: {
      vin: 'KF5P-119401',
      year: 2021,
      make: 'Mazda',
      model: 'CX-5',
      rego: 'WCM504',
      subModel: '2.5L Turbo AWD',
    },
    part: {
      name: 'Rear Tailgate Assembly with Power Struts & Camera Harness',
      partNumber: 'KB7W-62-020H',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      conditionPreference: 'New',
      vehicleSide: 'Rear',
    },
    sourcing: {
      status: 'Supplier Selected',
      selectedSupplierQuoteId: 'sq_104_a',
      supplierQuotes: [
        {
          id: 'sq_104_a',
          supplierId: 'sup_hiroshima_oem',
          supplierName: 'Hiroshima Genuine Spares',
          supplierCode: 'HGS-JP',
          partDescription: 'Mazda OEM CX-5 Power Tailgate Bare Shell + Loom',
          partCostNZD: 1120,
          availability: 'In Stock',
          estimatedDispatchDays: '2 days',
          supplierFreightNZD: 180,
          totalSupplierCostNZD: 1300,
          isSelected: true,
          quotedAt: '2026-08-23 11:00',
          quotedBy: 'Sarah Wilson',
          validUntil: '2026-09-05',
        },
      ],
    },
    procurementOrder: {
      orderNumber: 'ORD-000104',
      supplierName: 'Hiroshima Genuine Spares',
      status: 'Received At Shipping Facility',
      orderedAt: '2026-08-24 10:00',
      expectedShippingFacilityDate: '2026-08-26',
    },
    shipment: {
      shipmentNumber: 'SHP-000104',
      carrier: 'Mainfreight Air & Ocean',
      trackingCode: 'MFR-NZ-881920',
      freightMethod: 'Air Freight',
      status: 'Received at shipping facility',
      originHub: 'Osaka Kansai Air Cargo Depot (KIX)',
      destinationHub: 'Wellington Gateway (WLG)',
      etaDate: '2026-09-04',
      milestones: [
        {
          title: 'Received at Shipping Facility',
          location: 'Autohub Kansai Logistics Centre',
          timestamp: '2026-08-26 14:00',
          status: 'completed',
        },
        {
          title: 'Carrier Flight Consolidation Exception',
          location: 'Osaka Kansai Terminal 2',
          timestamp: '2026-08-28 07:30',
          status: 'in-progress',
          note: 'Oversize cargo crate requires alternative wide-body freighter booking. Air freight delayed by 48 hours.',
        },
      ],
    },
    exceptions: [
      {
        id: 'exc_log_00042',
        code: 'LOG-00042',
        title: 'Air Cargo Flight Rebooking — Oversize Tailgate Crate',
        category: 'Logistics',
        severity: 'High',
        status: 'Investigating',
        description: 'Kansai cargo terminal flagged custom wooden crate as exceeding standard pallet height for scheduled flight NZ90. Rebooking onto Cathay Pacific Cargo Boeing 747 freighter.',
        owner: 'Sarah Wilson',
        createdAt: '2026-08-28 07:30',
      },
    ],
    payment: {
      paymentNumber: 'PAY-00104',
      amountNZD: 1890,
      status: 'Payment Received',
      dueDate: '2026-09-20',
      paidAt: '2026-08-24 09:30',
      method: 'Approved Trade Credit (20th Mth Following)',
      invoiceNumber: 'INV-2026-0899',
      creditApproved: true,
    },
    timeline: [
      {
        id: 'tl_104_exc',
        stage: 'Logistics Exception Detected',
        timestamp: '2026-08-28 07:30',
        user: 'Mainfreight EDI Gateway',
        action: 'LOG-00042 logged. Flight rebooking in progress.',
        isCompleted: false,
        isCurrent: true,
      },
    ],
    messages: [],
    documents: [],
  },

  // 6. Request AH-P-000108: Hyundai Santa Fe (Payment Failed)
  {
    id: 'req_000108',
    referenceNumber: 'AH-P-000108',
    customerName: 'AutoCare Auckland',
    customerId: 'cust_autocare',
    customerEmail: 'james@autocareauckland.co.nz',
    customerPhone: '021 555 8921',
    deliveryBranch: 'Manukau Fleet Facility',
    submittedDate: '2026-08-27 16:30',
    updatedAt: '2026-08-28 08:20',
    status: 'Payment Failed',
    priority: 'Urgent',
    ownerName: 'Michael Chen',
    ownerId: 'usr_michael_chen',
    vehicle: {
      vin: 'KMHSU81W9LU192841',
      year: 2020,
      make: 'Hyundai',
      model: 'Santa Fe',
      rego: 'HYU812',
      subModel: 'TM 2.2L CRDi Diesel AWD',
    },
    part: {
      name: 'Electronic Brake Booster & Master Cylinder Integrated Unit',
      partNumber: '58500-S1100',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      conditionPreference: 'New',
    },
    sourcing: {
      status: 'Supplier Selected',
      selectedSupplierQuoteId: 'sq_108_a',
      supplierQuotes: [
        {
          id: 'sq_108_a',
          supplierId: 'sup_seoul_mobis',
          supplierName: 'Seoul Mobis Direct',
          supplierCode: 'SMD-KR',
          partDescription: 'Hyundai Mobis OEM Electronic Booster',
          partCostNZD: 620,
          availability: 'In Stock',
          estimatedDispatchDays: '1 day',
          supplierFreightNZD: 75,
          totalSupplierCostNZD: 695,
          isSelected: true,
          quotedAt: '2026-08-27 17:00',
          quotedBy: 'Sarah Wilson',
          validUntil: '2026-09-03',
        },
      ],
    },
    payment: {
      paymentNumber: 'PAY-00108',
      amountNZD: 920,
      status: 'Payment Failed',
      dueDate: '2026-08-28',
      invoiceNumber: 'INV-2026-0950',
      creditApproved: false,
    },
    exceptions: [
      {
        id: 'exc_pay_00019',
        code: 'PAY-00019',
        title: 'Credit Card Payment Gateway Timeout / 3DS Error',
        category: 'Payment',
        severity: 'Critical',
        status: 'Action Required',
        description: 'Customer attempted checkout with company credit card. Bank gateway returned 3D-Secure authentication failure.',
        owner: 'Michael Chen',
        createdAt: '2026-08-28 08:20',
      },
    ],
    timeline: [
      {
        id: 'tl_108_1',
        stage: 'Payment Failed Exception',
        timestamp: '2026-08-28 08:20',
        user: 'Stripe / TradePay Gateway',
        action: 'Payment declined. Notification sent to customer.',
        isCompleted: false,
        isCurrent: true,
      },
    ],
    messages: [
      {
        id: 'msg_108_1',
        requestId: 'req_000108',
        authorId: 'usr_michael_chen',
        authorName: 'Michael Chen',
        authorRole: 'Operations',
        timestamp: '2026-08-28 08:25',
        content: 'Contacting Sarah Jenkins at AutoCare accounts to switch invoice to 20th month trade credit account.',
        isInternalOnly: true,
      },
    ],
    documents: [],
  },

  // 7. Request AH-P-000120: Nissan Navara Alternator (Payment Received -> Ordered)
  {
    id: 'req_000120',
    referenceNumber: 'AH-P-000120',
    customerName: 'AutoCare Auckland',
    customerId: 'cust_autocare',
    customerEmail: 'james@autocareauckland.co.nz',
    customerPhone: '021 555 8921',
    deliveryBranch: 'Auckland Main Workshop (Penrose)',
    submittedDate: '2026-08-27 10:15',
    updatedAt: '2026-08-28 10:18',
    status: 'Payment Received',
    priority: 'Normal',
    ownerName: 'Michael Chen',
    ownerId: 'usr_michael_chen',
    vehicle: {
      vin: 'MNBUMD2300091823',
      year: 2019,
      make: 'Nissan',
      model: 'Navara',
      rego: 'NAV219',
      subModel: 'D23 NP300 2.3L Twin Turbo',
    },
    part: {
      name: 'High Output Alternator 130A (Genuine Hitachi/Nissan)',
      partNumber: '23100-EB300',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      conditionPreference: 'New',
    },
    sourcing: {
      status: 'Supplier Selected',
      selectedSupplierQuoteId: 'sq_120_a',
      supplierQuotes: [
        {
          id: 'sq_120_a',
          supplierId: 'sup_tokyo_parts',
          supplierName: 'Tokyo Auto Spares',
          supplierCode: 'TAS-JP',
          partDescription: 'Hitachi OEM Nissan D23 Alternator 130A',
          partCostNZD: 240,
          availability: 'In Stock',
          estimatedDispatchDays: '1 day',
          supplierFreightNZD: 55,
          totalSupplierCostNZD: 295,
          isSelected: true,
          quotedAt: '2026-08-27 14:00',
          quotedBy: 'Sarah Wilson',
          validUntil: '2026-09-10',
        },
      ],
    },
    payment: {
      paymentNumber: 'PAY-00120',
      amountNZD: 420,
      status: 'Payment Received',
      dueDate: '2026-09-20',
      paidAt: '2026-08-28 10:18',
      method: 'Account2Account Bank Transfer',
      invoiceNumber: 'INV-2026-0940',
      creditApproved: true,
    },
    timeline: [
      {
        id: 'tl_120_1',
        stage: 'Payment Received',
        timestamp: '2026-08-28 10:18',
        user: 'James Taylor (Finance)',
        action: 'Bank transfer verified NZ$420.00. Ready for PO creation.',
        isCompleted: true,
        isCurrent: true,
      },
    ],
    messages: [],
    documents: [],
  },

  // 8. Request AH-P-000117: Subaru Outback Steering Rack (Ordered From Supplier)
  {
    id: 'req_000117',
    referenceNumber: 'AH-P-000117',
    customerName: 'Central Motors',
    customerId: 'cust_central',
    customerEmail: 'john.smith@centralmotors.co.nz',
    customerPhone: '027 444 9912',
    deliveryBranch: 'Wellington Central Hub',
    submittedDate: '2026-08-25 11:00',
    updatedAt: '2026-08-28 09:20',
    status: 'Ordered From Supplier',
    priority: 'Normal',
    ownerName: 'Sarah Wilson',
    ownerId: 'usr_sarah_wilson',
    vehicle: {
      vin: 'BS9-041928',
      year: 2020,
      make: 'Subaru',
      model: 'Outback',
      rego: 'SUB882',
      subModel: '2.5i Premium Lineartronic AWD',
    },
    part: {
      name: 'Electric Power Steering (EPS) Gearbox & Rack Assembly',
      partNumber: '34110-AL011',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      conditionPreference: 'New',
    },
    sourcing: {
      status: 'Supplier Selected',
      selectedSupplierQuoteId: 'sq_117_a',
      supplierQuotes: [
        {
          id: 'sq_117_a',
          supplierId: 'sup_tokyo_parts',
          supplierName: 'Tokyo Auto Spares',
          supplierCode: 'TAS-JP',
          partDescription: 'Subaru OEM EPS Steering Rack Complete',
          partCostNZD: 780,
          availability: '1–3 Days',
          estimatedDispatchDays: '2 days',
          supplierFreightNZD: 95,
          totalSupplierCostNZD: 875,
          isSelected: true,
          quotedAt: '2026-08-26 09:00',
          quotedBy: 'Sarah Wilson',
          validUntil: '2026-09-08',
        },
      ],
    },
    procurementOrder: {
      orderNumber: 'ORD-000117',
      supplierName: 'Tokyo Auto Spares',
      status: 'Ordered From Supplier',
      orderedAt: '2026-08-28 09:15',
      expectedShippingFacilityDate: '2026-08-30',
      supplierOrderRef: 'TAS-PO-88192',
    },
    payment: {
      paymentNumber: 'PAY-00117',
      amountNZD: 1250,
      status: 'Payment Received',
      dueDate: '2026-09-20',
      paidAt: '2026-08-27 16:45',
      method: 'Approved Trade Credit (20th Mth Following)',
      invoiceNumber: 'INV-2026-0932',
      creditApproved: true,
    },
    timeline: [
      {
        id: 'tl_117_1',
        stage: 'Ordered From Supplier',
        timestamp: '2026-08-28 09:20',
        user: 'Sarah Wilson',
        action: 'Purchase Order ORD-000117 dispatched to Tokyo Auto Spares.',
        isCompleted: true,
        isCurrent: true,
      },
    ],
    messages: [],
    documents: [],
  },

  // 9. Request AH-P-000115: Mitsubishi Triton Injectors (Customs Clearance)
  {
    id: 'req_000115',
    referenceNumber: 'AH-P-000115',
    customerName: 'West Auto',
    customerId: 'cust_west',
    customerEmail: 'liam@westauto.co.nz',
    customerPhone: '021 777 4321',
    deliveryBranch: 'Henderson Fleet Facility',
    submittedDate: '2026-08-20 09:00',
    updatedAt: '2026-08-28 06:45',
    status: 'Customs Clearance',
    priority: 'Normal',
    ownerName: 'Michael Chen',
    ownerId: 'usr_michael_chen',
    vehicle: {
      vin: 'MMAJRKL10JH129841',
      year: 2021,
      make: 'Mitsubishi',
      model: 'Triton',
      rego: 'TRT410',
      subModel: 'GLS 4WD 2.4L Diesel 4N15',
    },
    part: {
      name: 'Common Rail Fuel Injector Set (4x Genuine Denso)',
      partNumber: '1465A439',
      quantity: 4,
      qualityPreference: 'Genuine OEM',
      conditionPreference: 'New',
    },
    sourcing: {
      status: 'Supplier Selected',
      supplierQuotes: [],
    },
    shipment: {
      shipmentNumber: 'SHP-000115',
      carrier: 'Freightways / NZ Post Priority',
      trackingCode: 'FTW-AKL-991284',
      freightMethod: 'Air Freight',
      status: 'Customs Clearance',
      originHub: 'Nagoya Air Freight Depot',
      destinationHub: 'Auckland Customs Gateway',
      etaDate: '2026-08-30',
      milestones: [
        {
          title: 'Arrived at Auckland International Airport',
          location: 'AKL Air Cargo Terminal',
          timestamp: '2026-08-28 05:30',
          status: 'completed',
        },
        {
          title: 'NZ Customs & MPI Biosecurity Clearance',
          location: 'Customs Examination Bay 3',
          timestamp: '2026-08-28 06:45',
          status: 'in-progress',
          note: 'Electronic clearance documents lodged. Awaiting MPI clearance release.',
        },
      ],
    },
    payment: {
      paymentNumber: 'PAY-00115',
      amountNZD: 1680,
      status: 'Payment Received',
      dueDate: '2026-09-20',
      paidAt: '2026-08-21 11:00',
      method: 'Approved Trade Credit (20th Mth Following)',
      invoiceNumber: 'INV-2026-0881',
      creditApproved: true,
    },
    timeline: [],
    messages: [],
    documents: [],
  },

  // 10. Request AH-P-000112: VW Amarok EGR Valve (Delivered)
  {
    id: 'req_000112',
    referenceNumber: 'AH-P-000112',
    customerName: 'North Shore Automotive',
    customerId: 'cust_northshore',
    customerEmail: 'dave@northshoreauto.co.nz',
    customerPhone: '021 998 1234',
    deliveryBranch: 'Takapuna Service Workshop',
    submittedDate: '2026-08-15 14:00',
    updatedAt: '2026-08-27 16:30',
    status: 'Delivered',
    priority: 'Normal',
    ownerName: 'Michael Chen',
    ownerId: 'usr_michael_chen',
    vehicle: {
      vin: 'WV1ZZZ2HZJH019284',
      year: 2018,
      make: 'Volkswagen',
      model: 'Amarok',
      rego: 'AMR118',
      subModel: '3.0L V6 TDI 580 Highline',
    },
    part: {
      name: 'EGR Valve & Cooler Module (Genuine Pierburg / VW)',
      partNumber: '059 131 515 EL',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      conditionPreference: 'New',
    },
    sourcing: {
      status: 'Supplier Selected',
      supplierQuotes: [],
    },
    shipment: {
      shipmentNumber: 'SHP-000112',
      carrier: 'NZ Post Courier',
      trackingCode: 'NZP-DEL-119284',
      freightMethod: 'Air Freight',
      status: 'Delivered',
      originHub: 'Frankfurt Hub (Germany)',
      destinationHub: 'Takapuna Workshop',
      etaDate: '2026-08-27',
      milestones: [
        {
          title: 'Delivered and Signed',
          location: 'Takapuna Workshop Goods Inward',
          timestamp: '2026-08-27 16:30',
          status: 'completed',
          note: 'Signed by Dave Stewart (Workshop Head)',
        },
      ],
    },
    payment: {
      paymentNumber: 'PAY-00112',
      amountNZD: 890,
      status: 'Payment Received',
      dueDate: '2026-09-20',
      paidAt: '2026-08-16 10:00',
      invoiceNumber: 'INV-2026-0840',
      creditApproved: true,
    },
    timeline: [],
    messages: [],
    documents: [],
  },
];

export const INITIAL_EXCEPTIONS: OperationalException[] = [
  {
    id: 'exc_1',
    code: 'LOG-00042',
    title: 'Shipment Delayed at Origin Facility',
    category: 'Logistics',
    severity: 'High',
    status: 'Investigating',
    description: 'Shipment SHP-000104 (Mazda CX-5 Tailgate) delayed at Kansai origin hub due to oversize wooden crate requiring dedicated wide-body cargo flight booking.',
    requestId: 'req_000104',
    requestNumber: 'AH-P-000104',
    customerName: 'Wellington Commercial Motors',
    vehicleSummary: 'Mazda CX-5 · 2021',
    partSummary: 'Rear Tailgate Assembly',
    shipmentNumber: 'SHP-000104',
    owner: 'Sarah Wilson',
    createdAt: '2026-08-28 07:30',
    updatedAt: '2026-08-28 09:15',
    resolutionNote: 'Mainfreight booked onto Cathay Pacific 747-8F flight CX082 arriving Auckland Saturday morning. Re-estimated delivery Petone Tuesday.',
    actionsHistory: [
      {
        timestamp: '2026-08-28 07:30',
        user: 'Mainfreight API',
        action: 'Exception detected automatically via shipment scan',
      },
      {
        timestamp: '2026-08-28 08:00',
        user: 'Sarah Wilson',
        action: 'Assigned exception to Sarah Wilson',
      },
      {
        timestamp: '2026-08-28 09:15',
        user: 'Sarah Wilson',
        action: 'Updated tracking ETA and sent operational note to customer service desk',
      },
    ],
  },
  {
    id: 'exc_2',
    code: 'PAY-00019',
    title: 'Customer Payment Declined / 3DS Timeout',
    category: 'Payment',
    severity: 'Critical',
    status: 'Action Required',
    description: 'Customer payment for AH-P-000108 (Hyundai Santa Fe Booster NZ$920.00) failed due to bank 3D-Secure verification timeout.',
    requestId: 'req_000108',
    requestNumber: 'AH-P-000108',
    customerName: 'AutoCare Auckland',
    vehicleSummary: 'Hyundai Santa Fe · 2020',
    partSummary: 'Electronic Brake Booster Unit',
    owner: 'Michael Chen',
    createdAt: '2026-08-28 08:20',
    updatedAt: '2026-08-28 08:40',
    actionsHistory: [
      {
        timestamp: '2026-08-28 08:20',
        user: 'Payment Gateway',
        action: 'Card processing transaction failed',
      },
      {
        timestamp: '2026-08-28 08:40',
        user: 'Michael Chen',
        action: 'Telephoned accounts contact Sarah Jenkins to switch order to trade credit invoice',
      },
    ],
  },
  {
    id: 'exc_3',
    code: 'SUP-00014',
    title: 'Supplier Quote Expiring in 7 Hours',
    category: 'Supplier',
    severity: 'High',
    status: 'Action Required',
    description: 'Tokyo Auto Spares promotional wholesale price for 1GD-FTV Hilux Turbocharger (NZ$1,605 total landed) expires at 5:00 PM today.',
    requestId: 'req_000118',
    requestNumber: 'AH-P-000118',
    customerName: 'North Shore Automotive',
    vehicleSummary: 'Toyota Hilux · 2022',
    partSummary: 'VNT Turbocharger Assembly',
    owner: 'Sarah Wilson',
    createdAt: '2026-08-28 09:00',
    updatedAt: '2026-08-28 09:45',
    actionsHistory: [
      {
        timestamp: '2026-08-28 09:00',
        user: 'System Bot',
        action: 'Automated 8-hour expiry reminder triggered',
      },
      {
        timestamp: '2026-08-28 09:45',
        user: 'Sarah Wilson',
        action: 'Sent SMS follow-up prompt to workshop head Dave Stewart',
      },
    ],
  },
  {
    id: 'exc_4',
    code: 'CUS-00008',
    title: 'Customs MPI Biosecurity Phytosanitary Check',
    category: 'Customs',
    severity: 'Medium',
    status: 'Investigating',
    description: 'Ministry for Primary Industries requested timber treatment certification for pallet packing on shipment SHP-000115.',
    requestId: 'req_000115',
    requestNumber: 'AH-P-000115',
    customerName: 'West Auto',
    vehicleSummary: 'Mitsubishi Triton · 2021',
    partSummary: 'Fuel Injector Set (4x)',
    shipmentNumber: 'SHP-000115',
    owner: 'James Taylor',
    createdAt: '2026-08-28 06:45',
    updatedAt: '2026-08-28 08:30',
    actionsHistory: [
      {
        timestamp: '2026-08-28 06:45',
        user: 'MPI Border Gateway',
        action: 'Phytosanitary documentation requested',
      },
      {
        timestamp: '2026-08-28 08:30',
        user: 'James Taylor',
        action: 'Forwarded ISPM-15 heat-treatment stamp certificate from Nagoya freight agent',
      },
    ],
  },
];

export const INITIAL_TASKS: OperationalTask[] = [
  {
    id: 'tsk_1',
    title: 'Review and Confirm Payment Exception for AH-P-000108',
    requestId: 'req_000108',
    requestNumber: 'AH-P-000108',
    vehicleSummary: 'Hyundai Santa Fe 2020 · Brake Booster',
    customerName: 'AutoCare Auckland',
    assignedTo: 'Michael Chen',
    priority: 'Urgent',
    dueDate: '2026-08-28',
    dueLabel: 'Due Today',
    type: 'Resolve Payment',
    status: 'Open',
    targetUrl: '/operations/requests/AH-P-000108',
  },
  {
    id: 'tsk_2',
    title: 'Lock in Expiring Supplier Quote for Hilux Turbocharger',
    requestId: 'req_000118',
    requestNumber: 'AH-P-000118',
    vehicleSummary: 'Toyota Hilux 2022 · Turbocharger',
    customerName: 'North Shore Automotive',
    assignedTo: 'Sarah Wilson',
    priority: 'High',
    dueDate: '2026-08-28',
    dueLabel: 'Due Today',
    type: 'Review Supplier Quote',
    status: 'Open',
    targetUrl: '/operations/requests/AH-P-000118',
  },
  {
    id: 'tsk_3',
    title: 'Resolve Logistics Exception LOG-00042 (Mazda CX-5 Tailgate)',
    requestId: 'req_000104',
    requestNumber: 'AH-P-000104',
    vehicleSummary: 'Mazda CX-5 2021 · Tailgate',
    customerName: 'Wellington Commercial Motors',
    assignedTo: 'Sarah Wilson',
    priority: 'High',
    dueDate: '2026-08-28',
    dueLabel: 'Due Today',
    type: 'Resolve Exception',
    status: 'In Progress',
    targetUrl: '/operations/exceptions/LOG-00042',
  },
  {
    id: 'tsk_4',
    title: 'Create Purchase Order for Paid Navara Alternator',
    requestId: 'req_000120',
    requestNumber: 'AH-P-000120',
    vehicleSummary: 'Nissan Navara 2019 · Alternator',
    customerName: 'AutoCare Auckland',
    assignedTo: 'Michael Chen',
    priority: 'Normal',
    dueDate: '2026-08-28',
    dueLabel: 'Due Today',
    type: 'Dispatch PO',
    status: 'Open',
    targetUrl: '/operations/requests/AH-P-000120',
  },
  {
    id: 'tsk_5',
    title: 'Complete Sourcing for Mazda CX-5 Headlamp (KB8A-51-041B)',
    requestId: 'req_000122',
    requestNumber: 'AH-P-000122',
    vehicleSummary: 'Mazda CX-5 2021 · LED Headlamp',
    customerName: 'Central Motors',
    assignedTo: 'Sarah Wilson',
    priority: 'Urgent',
    dueDate: '2026-08-28',
    dueLabel: 'Due Today',
    type: 'Prepare Customer Quote',
    status: 'In Progress',
    targetUrl: '/operations/requests/AH-P-000122',
  },
  {
    id: 'tsk_6',
    title: 'Review Trade Credit Application for Apex Fleet Logistics',
    requestId: 'cust_pending_apex',
    requestNumber: 'NZBN-9429047771122',
    vehicleSummary: 'National Fleet Account Review',
    customerName: 'Apex Fleet Logistics & Repairs Ltd',
    assignedTo: 'James Taylor',
    priority: 'Normal',
    dueDate: '2026-08-29',
    dueLabel: 'Due Tomorrow',
    type: 'Follow Up Approval',
    status: 'Open',
    targetUrl: '/operations/customers/pending',
  },
];

export const INITIAL_AUDIT_LOG: OperationalAuditEntry[] = [
  {
    id: 'aud_1',
    timestamp: '2026-08-28 11:20:45',
    timeFormatted: '11:20 AM',
    user: 'Michael Chen',
    userRole: 'Operations',
    action: 'Customer Quote Sent',
    objectType: 'Quote',
    objectId: 'AH-P-000123',
    details: 'Dispatched Quote QUO-000123-v3 (NZ$485.00) to James Wilson at AutoCare Auckland',
    oldValue: 'Draft',
    newValue: 'Sent',
  },
  {
    id: 'aud_2',
    timestamp: '2026-08-28 11:15:10',
    timeFormatted: '11:15 AM',
    user: 'Sarah Wilson',
    userRole: 'Procurement',
    action: 'Status Changed',
    objectType: 'Request',
    objectId: 'AH-P-000123',
    details: 'Completed supplier quote evaluation and advanced request status',
    oldValue: 'Sourcing',
    newValue: 'Quote Ready',
  },
  {
    id: 'aud_3',
    timestamp: '2026-08-28 10:50:22',
    timeFormatted: '10:50 AM',
    user: 'James Taylor',
    userRole: 'Finance',
    action: 'Payment Updated',
    objectType: 'Payment',
    objectId: 'PAY-00120',
    details: 'Reconciled Account2Account bank transfer of NZ$420.00 for Nissan Navara Alternator',
    oldValue: 'Payment Pending',
    newValue: 'Payment Received',
  },
  {
    id: 'aud_4',
    timestamp: '2026-08-28 10:18:00',
    timeFormatted: '10:18 AM',
    user: 'Sarah Wilson',
    userRole: 'Procurement',
    action: 'Supplier Quote Selected',
    objectType: 'Quote',
    objectId: 'AH-P-000123',
    details: 'Selected Supplier A (Tokyo Auto Spares) at NZ$370 landed cost',
    newValue: 'Tokyo Auto Spares (TAS-JP)',
  },
  {
    id: 'aud_5',
    timestamp: '2026-08-28 09:45:12',
    timeFormatted: '09:45 AM',
    user: 'Sarah Wilson',
    userRole: 'Procurement',
    action: 'Supplier Quote Added',
    objectType: 'Quote',
    objectId: 'AH-P-000118',
    details: 'Added Tokyo Auto Spares quotation of NZ$1,450 + freight NZ$120',
  },
  {
    id: 'aud_6',
    timestamp: '2026-08-28 09:20:05',
    timeFormatted: '09:20 AM',
    user: 'Michael Chen',
    userRole: 'Operations',
    action: 'Staff Reassignment',
    objectType: 'Request',
    objectId: 'AH-P-000117',
    details: 'Assigned request for Subaru Outback Steering Rack to Sarah Wilson',
    oldValue: 'Unassigned',
    newValue: 'Sarah Wilson',
  },
  {
    id: 'aud_7',
    timestamp: '2026-08-28 08:30:19',
    timeFormatted: '08:30 AM',
    user: 'System Gateway',
    userRole: 'Administrator',
    action: 'Request Received',
    objectType: 'Request',
    objectId: 'AH-P-000123',
    details: 'New procurement request submitted via Customer Portal',
  },
  {
    id: 'aud_8',
    timestamp: '2026-08-28 07:30:00',
    timeFormatted: '07:30 AM',
    user: 'Mainfreight EDI',
    userRole: 'Administrator',
    action: 'Exception Created',
    objectType: 'Exception',
    objectId: 'LOG-00042',
    details: 'Origin facility congestion delayed air cargo booking for CX-5 Tailgate',
  },
];

export const INITIAL_REPORT_METRICS: OperationalReportMetrics = {
  openRequestsCount: 48,
  awaitingQuotesCount: 12,
  awaitingApprovalCount: 9,
  awaitingPaymentCount: 7,
  procurementInProgressCount: 24,
  activeShipmentsCount: 18,
  exceptionsCount: 4,
  avgProcessingDays: 2.4,
  quoteConversionRate: 72,
  paymentConversionRate: 89,
  activeProcurementValueNZD: 28450,
  outstandingPaymentsNZD: 7820,
  monthlyRevenueNZD: 184500,
  sourcingTimeDays: 0.6,
  quotePreparationDays: 0.3,
  approvalTimeDays: 0.8,
  procurementTimeDays: 0.4,
  deliveryTimeDays: 4.8,
  requestsByStatus: [
    { status: 'Submitted', count: 48, valueNZD: 38400 },
    { status: 'Sourcing', count: 21, valueNZD: 24500 },
    { status: 'Quote Ready', count: 12, valueNZD: 16800 },
    { status: 'Customer Approval', count: 9, valueNZD: 11200 },
    { status: 'Paid', count: 7, valueNZD: 4850 },
    { status: 'Procurement', count: 24, valueNZD: 28450 },
    { status: 'Shipping', count: 18, valueNZD: 22100 },
    { status: 'Delivered', count: 31, valueNZD: 41800 },
  ],
};
