// PROCURly Procurement Portal Mock Data Repository
import {
  ProcurementStaffUser,
  ProcurementRequest,
  SupplierSummary,
  SupplierQuoteItem,
  PurchaseOrderItem,
  ProcurementTaskItem,
  ProcurementExceptionItem,
  SupplierConversation,
  ProcurementDocumentItem,
  ShipmentDispatchItem,
  ProcurementNotificationItem,
} from '@/types/procurement';

export const INITIAL_STAFF_USERS: ProcurementStaffUser[] = [
  {
    id: 'usr_sarah_wilson',
    name: 'Sarah Wilson',
    email: 'sarah.wilson@autohub.co.nz',
    role: 'Senior Procurement Specialist',
    avatar: 'SW',
    phone: '+64 21 554 982',
    specialization: ['Toyota OEM', 'Subaru', 'German Powertrains', 'JDM Performance'],
    activeRegions: ['Japan (Nagoya/Tokyo)', 'Europe (Munich)', 'Australia (Melbourne)'],
  },
  {
    id: 'usr_michael_chen',
    name: 'Michael Chen',
    email: 'michael.chen@autohub.co.nz',
    role: 'Procurement Lead',
    avatar: 'MC',
    phone: '+64 21 889 421',
    specialization: ['Heavy Commercial', 'Suspension & Chassis', 'EV / Hybrid Battery Modules'],
    activeRegions: ['Japan', 'USA (California)', 'Singapore Hub'],
  },
  {
    id: 'usr_liam_evans',
    name: 'Liam Evans',
    email: 'liam.evans@autohub.co.nz',
    role: 'Sourcing Officer',
    avatar: 'LE',
    phone: '+64 22 109 432',
    specialization: ['Body Panels', 'Lighting & Glass', 'Aftermarket Aero'],
    activeRegions: ['Japan', 'Taiwan', 'NZ Domestic'],
  },
  {
    id: 'usr_elena_rostova',
    name: 'Elena Rostova',
    email: 'elena.rostova@autohub.co.nz',
    role: 'Logistics Coordinator',
    avatar: 'ER',
    phone: '+64 27 651 890',
    specialization: ['Air Freight Consolidation', 'MPI Customs Clearance', 'DG Battery Logistics'],
    activeRegions: ['Auckland Airport Hub', 'Ports of Auckland', 'Yokohama Depot'],
  },
];

export const INITIAL_SUPPLIERS: SupplierSummary[] = [
  {
    id: 'sup_tokyo_oem',
    name: 'Tokyo Auto Spares Co., Ltd.',
    code: 'TAS-JP',
    location: 'Yokohama, Kanagawa',
    country: 'Japan',
    specialization: ['Toyota', 'Lexus', 'Subaru', 'Nissan OEM'],
    contactName: 'Kenji Takahashi',
    contactEmail: 'kenji.t@tokyoautospares.jp',
    contactPhone: '+81 45 671 9022',
    activeOrdersCount: 8,
    responseRatePct: 98,
    avgLeadTimeDays: 2.5,
    avgResponseTimeHours: 1.8,
    orderCompletionPct: 99.4,
    exceptionRatePct: 0.8,
    status: 'Preferred',
    operatingRegions: ['Japan', 'Asia-Pacific'],
    preferredCategories: ['Engine Components', 'Transmissions', 'OEM Electrical'],
    reliabilityScore: 97,
    notes: 'Primary Japanese OEM partner with direct factory warehouse access in Nagoya and Yokohama.',
  },
  {
    id: 'sup_nagoya_distrib',
    name: 'Nagoya JDM Hub Supply',
    code: 'NJH-JP',
    location: 'Nagoya, Aichi',
    country: 'Japan',
    specialization: ['Subaru STI', 'Honda Type-R', 'Mitsubishi Ralliart'],
    contactName: 'Shinji Ogawa',
    contactEmail: 's.ogawa@nagoyajdmhub.co.jp',
    contactPhone: '+81 52 890 1144',
    activeOrdersCount: 5,
    responseRatePct: 94,
    avgLeadTimeDays: 3.2,
    avgResponseTimeHours: 3.5,
    orderCompletionPct: 97.8,
    exceptionRatePct: 2.1,
    status: 'Active',
    operatingRegions: ['Japan'],
    preferredCategories: ['Drivetrain', 'Turbochargers', 'Grade A Used Engines'],
    reliabilityScore: 92,
    notes: 'Specialist in low-km JDM performance engines and assemblies.',
  },
  {
    id: 'sup_munich_euro',
    name: 'Bavaria EuroParts GmbH',
    code: 'BEP-DE',
    location: 'Munich, Bavaria',
    country: 'Germany',
    specialization: ['BMW', 'Mercedes-Benz', 'Audi', 'Porsche OEM'],
    contactName: 'Markus Weber',
    contactEmail: 'm.weber@bavaria-europarts.de',
    contactPhone: '+49 89 452 9901',
    activeOrdersCount: 4,
    responseRatePct: 96,
    avgLeadTimeDays: 4.0,
    avgResponseTimeHours: 4.2,
    orderCompletionPct: 98.5,
    exceptionRatePct: 1.2,
    status: 'Preferred',
    operatingRegions: ['Europe', 'UK'],
    preferredCategories: ['Control Modules', 'Steering Racks', 'Headlamps', 'Air Suspension'],
    reliabilityScore: 95,
    notes: 'Direct European parts distributor with air freight direct to Auckland.',
  },
  {
    id: 'sup_melbourne_aftermarket',
    name: 'Trans-Tasman Auto Wholesale',
    code: 'TTA-AU',
    location: 'Dandenong, Melbourne',
    country: 'Australia',
    specialization: ['4WD Accessories', 'Ford Ranger', 'Toyota Hilux', 'Aftermarket Cooling'],
    contactName: 'Brett Henderson',
    contactEmail: 'bhenderson@transtasmanauto.com.au',
    contactPhone: '+61 3 9700 8123',
    activeOrdersCount: 3,
    responseRatePct: 91,
    avgLeadTimeDays: 1.5,
    avgResponseTimeHours: 2.0,
    orderCompletionPct: 96.2,
    exceptionRatePct: 3.5,
    status: 'Active',
    operatingRegions: ['Australia', 'New Zealand'],
    preferredCategories: ['Radiators', 'Alternators', 'Starter Motors', 'Brake Rotors'],
    reliabilityScore: 89,
    notes: 'Fast 24-48h air courier across the Tasman.',
  },
  {
    id: 'sup_osaka_rebuild',
    name: 'Kansai Precision Remanufacturing',
    code: 'KPR-JP',
    location: 'Osaka',
    country: 'Japan',
    specialization: ['Hybrid Batteries', 'Steering Gears', 'Reman Injectors'],
    contactName: 'Hitoshi Morimoto',
    contactEmail: 'morimoto@kansaiprecision.jp',
    contactPhone: '+81 6 6201 4455',
    activeOrdersCount: 2,
    responseRatePct: 88,
    avgLeadTimeDays: 5.0,
    avgResponseTimeHours: 6.0,
    orderCompletionPct: 94.0,
    exceptionRatePct: 4.8,
    status: 'Under Review',
    operatingRegions: ['Japan'],
    preferredCategories: ['Reman Parts', 'Batteries'],
    reliabilityScore: 84,
    notes: 'Specialized reman testing facility with 12-month warranty certificate included.',
  },
];

export const INITIAL_REQUESTS: ProcurementRequest[] = [
  {
    id: 'req_123',
    requestNumber: 'AH-P-000123',
    customerName: 'AutoCare Auckland',
    customerId: 'cust_autocare',
    customerEmail: 'james@autocareauckland.co.nz',
    customerPhone: '021 555 8921',
    customerBranch: 'Auckland Main Workshop (Penrose)',
    vehicle: {
      make: 'Toyota',
      model: 'Hiace',
      year: 2019,
      vin: 'JTEBR32P10029384',
      rego: 'KMR892',
      engineCode: '1KD-FTV',
      chassisCode: 'KDH201',
      transmission: 'Automatic',
    },
    part: {
      name: 'Left Front Lower Control Arm',
      partNumber: '48069-26150',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      condition: 'New OEM',
      notes: 'Complete lower control arm assembly with factory rubber bushings and lower ball joint.',
      images: ['https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&auto=format&fit=crop&q=60'],
    },
    priority: 'Urgent',
    status: 'Quote Ready',
    sourcingStatus: 'Sourcing Complete',
    assignedTo: 'Brendon Davies',
    assignedStaffId: 'usr_michael_chen',
    createdAt: '2026-08-28T08:30:00Z',
    updatedAt: '2026-08-28T10:42:00Z',
    targetBudgetNZD: 485,
    quotesCount: 2,
    timeline: [
      {
        title: 'Request Received from AutoCare Auckland',
        timestamp: '2026-08-28T08:30:00Z',
        actor: 'James Wilson',
        description: 'Chassis VIN JTEBR32P10029384 submitted for OEM Left Front Lower Arm.',
      },
      {
        title: 'Supplier RFQ Dispatched to Tokyo OEM Hub',
        timestamp: '2026-08-28T09:15:00Z',
        actor: 'Brendon Davies',
        description: 'Part # 48069-26150 confirmed in stock at Toyota Japan distribution.',
      },
      {
        title: 'Landed Quotes Ready (Air & Sea options)',
        timestamp: '2026-08-28T10:42:00Z',
        actor: 'Brendon Davies',
        description: 'NZ$485 Air Freight (Express 5-8d) and NZ$410 Sea Freight (18-30d) calculated.',
      },
    ],
    internalNotes: [
      {
        id: 'note_123',
        author: 'Brendon Davies',
        timestamp: '2026-08-28T10:40:00Z',
        text: 'Verified genuine OEM item with factory packaging. Green-lane biosecurity cleared.',
      },
    ],
    customerAttachments: [],
    documents: [
      { id: 'doc_123_q', title: 'Quotation — AH-P-000123', type: 'Quotation', date: '2026-08-28', size: '245 KB' },
    ],
  },
  {
    id: 'req_001',
    requestNumber: 'PR-10048',
    customerName: 'Auckland EuroTech Ltd',
    customerId: 'cust_eurotech_01',
    customerEmail: 'service@eurotechakld.co.nz',
    customerPhone: '+64 9 520 1144',
    customerBranch: 'Penrose, Auckland',
    vehicle: {
      make: 'Toyota',
      model: 'Hilux GR Sport',
      year: 2023,
      vin: 'MR0BA3CD200847192',
      rego: 'NKT912',
      engineCode: '1GD-FTV 2.8L Turbo Diesel',
      chassisCode: 'GUN126R',
      transmission: '6-Speed Automatic',
    },
    part: {
      name: 'Turbocharger Assembly with Stepper Motor',
      partNumber: '17201-11080',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      condition: 'New',
      notes: 'Customer requires genuine Toyota factory packaged unit with electronic actuator attached. Off-road fleet vehicle grounded.',
      images: ['/images/parts/turbo_sample.jpg'],
    },
    priority: 'Urgent',
    status: 'Sourcing',
    sourcingStatus: 'Quote Received',
    assignedTo: 'Sarah Wilson',
    assignedStaffId: 'usr_sarah_wilson',
    createdAt: '2026-08-27T09:15:00Z',
    updatedAt: '2026-08-28T04:20:00Z',
    targetBudgetNZD: 1850,
    quotesCount: 3,
    timeline: [
      {
        title: 'Request Assigned to Procurement',
        timestamp: '2026-08-27T09:30:00Z',
        actor: 'Michael Chen',
        description: 'Assigned to Sarah Wilson for urgent OEM JDM sourcing.',
      },
      {
        title: 'RFQs Dispatched to 3 Suppliers',
        timestamp: '2026-08-27T10:15:00Z',
        actor: 'Sarah Wilson',
        description: 'Sent specifications to Tokyo Auto Spares, Nagoya JDM Hub, and Trans-Tasman.',
      },
      {
        title: 'Supplier Quotes Received',
        timestamp: '2026-08-28T03:45:00Z',
        actor: 'Sarah Wilson',
        description: 'Received 3 competitive quotes. Ready for comparison and supplier selection.',
      },
    ],
    internalNotes: [
      {
        id: 'note_1',
        author: 'Sarah Wilson',
        timestamp: '2026-08-27T11:00:00Z',
        text: 'Tokyo Auto Spares confirmed immediate shelf stock in Yokohama warehouse.',
      },
      {
        id: 'note_2',
        author: 'Sarah Wilson',
        timestamp: '2026-08-28T04:00:00Z',
        text: 'Trans-Tasman quote is slightly faster on air freight but $120 higher base unit cost.',
      },
    ],
    customerAttachments: [
      { name: 'Hilux_VIN_Plate.jpg', size: '2.4 MB', url: '/docs/hilux_vin.jpg' },
      { name: 'Diagnostic_Fault_Code_Report.pdf', size: '480 KB', url: '/docs/dtc_p0046.pdf' },
    ],
    documents: [
      { id: 'doc_1', title: 'Customer Parts Requirement Spec', type: 'Specification', date: '2026-08-27', size: '1.1 MB' },
      { id: 'doc_2', title: 'Supplier RFQ Package - TAS-JP', type: 'RFQ', date: '2026-08-27', size: '640 KB' },
    ],
  },
  {
    id: 'req_002',
    requestNumber: 'PR-10049',
    customerName: 'Wellington Prestige Motors',
    customerId: 'cust_wlg_prestige',
    customerEmail: 'parts@wlgprestige.co.nz',
    customerPhone: '+64 4 384 7799',
    customerBranch: 'Thorndon, Wellington',
    vehicle: {
      make: 'BMW',
      model: 'M3 Competition (G80)',
      year: 2022,
      vin: 'WBS43AY03NCF18204',
      rego: 'M3FAST',
      engineCode: 'S58B30T0 3.0L Twin Turbo',
      chassisCode: 'G80',
      transmission: '8-Speed M Steptronic',
    },
    part: {
      name: 'Laser Headlight Assembly - Right Front (Driver Side)',
      partNumber: '63119853318',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      condition: 'New',
      notes: 'Must include complete control modules and coding tags. European spec (RHD).',
      images: ['/images/parts/bmw_headlight.jpg'],
    },
    priority: 'High',
    status: 'Quote Ready',
    sourcingStatus: 'Sourcing Complete',
    assignedTo: 'Sarah Wilson',
    assignedStaffId: 'usr_sarah_wilson',
    createdAt: '2026-08-26T14:30:00Z',
    updatedAt: '2026-08-28T02:10:00Z',
    targetBudgetNZD: 3800,
    selectedSupplierQuoteId: 'sq_bmw_01',
    quotesCount: 2,
    timeline: [
      {
        title: 'Request Sourced',
        timestamp: '2026-08-27T08:00:00Z',
        actor: 'Sarah Wilson',
        description: 'Bavaria EuroParts confirmed OEM unit in Munich.',
      },
      {
        title: 'Supplier Selected & Customer Quoted',
        timestamp: '2026-08-27T16:00:00Z',
        actor: 'Sarah Wilson',
        description: 'Quote sent to customer for trade sign-off.',
      },
    ],
    internalNotes: [
      {
        id: 'note_bmw_1',
        author: 'Sarah Wilson',
        timestamp: '2026-08-27T09:30:00Z',
        text: 'Munich hub confirmed RHD UK/NZ beam pattern on module 63119853318.',
      },
    ],
    customerAttachments: [
      { name: 'Damaged_Headlamp_Photo.jpg', size: '3.1 MB', url: '/docs/bmw_damaged.jpg' },
    ],
    documents: [
      { id: 'doc_bmw_1', title: 'Supplier Quotation - BEP-DE', type: 'Supplier Quote', date: '2026-08-27', size: '890 KB' },
    ],
  },
  {
    id: 'req_003',
    requestNumber: 'PR-10050',
    customerName: 'Precision 4WD Christchurch',
    customerId: 'cust_chch_4wd',
    customerEmail: 'orders@precision4wd.co.nz',
    customerPhone: '+64 3 365 2200',
    customerBranch: 'Middleton, Christchurch',
    vehicle: {
      make: 'Subaru',
      model: 'WRX STI',
      year: 2019,
      vin: 'JF1VAFEK9K8501923',
      rego: 'STI555',
      engineCode: 'EJ257 Turbo',
      chassisCode: 'VAB',
      transmission: '6-Speed Manual (DCCD)',
    },
    part: {
      name: 'Driver Controlled Centre Differential (DCCD) Module',
      partNumber: '38220AA180',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      condition: 'New',
      notes: 'Factory STI assembly. Includes wiring pigtail and solenoid.',
      images: [],
    },
    priority: 'Normal',
    status: 'Payment Received',
    sourcingStatus: 'Sourcing Complete',
    assignedTo: 'Liam Evans',
    assignedStaffId: 'usr_liam_evans',
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-08-28T05:00:00Z',
    targetBudgetNZD: 2400,
    selectedSupplierQuoteId: 'sq_subaru_01',
    purchaseOrderId: 'po_001',
    quotesCount: 2,
    timeline: [
      {
        title: 'Payment Confirmed by Accounts',
        timestamp: '2026-08-28T04:45:00Z',
        actor: 'Finance System',
        description: 'NZD $2,760 trade payment settled. Ready for PO execution.',
      },
    ],
    internalNotes: [
      {
        id: 'note_sub_1',
        author: 'Liam Evans',
        timestamp: '2026-08-26T10:00:00Z',
        text: 'Nagoya JDM Hub reserved last remaining OEM unit on holding order.',
      },
    ],
    customerAttachments: [],
    documents: [
      { id: 'doc_sub_1', title: 'Payment Receipt #REC-9821', type: 'Receipt', date: '2026-08-28', size: '210 KB' },
    ],
  },
  {
    id: 'req_004',
    requestNumber: 'PR-10051',
    customerName: 'Apex Commercial Fleet NZ',
    customerId: 'cust_apex_fleet',
    customerEmail: 'fleet@apexrepairs.co.nz',
    customerPhone: '+64 9 274 8811',
    customerBranch: 'East Tamaki, Auckland',
    vehicle: {
      make: 'Isuzu',
      model: 'NPR 75/190 Tipper',
      year: 2021,
      vin: 'MP1NPR75K00718293',
      rego: 'ISZ811',
      engineCode: '4HK1-TCS 5.2L Diesel',
      chassisCode: 'NPR75',
      transmission: 'Smoother 6-Speed AMT',
    },
    part: {
      name: 'Common Rail High Pressure Fuel Injection Pump',
      partNumber: '8-98077-840-0',
      quantity: 2,
      qualityPreference: 'Genuine OEM',
      condition: 'New',
      notes: 'Commercial delivery truck broken down. Must dispatch via express air within 48 hours.',
      images: [],
    },
    priority: 'Urgent',
    status: 'Ready for Procurement',
    sourcingStatus: 'Sourcing Complete',
    assignedTo: 'Michael Chen',
    assignedStaffId: 'usr_michael_chen',
    createdAt: '2026-08-27T16:00:00Z',
    updatedAt: '2026-08-28T06:00:00Z',
    targetBudgetNZD: 4200,
    selectedSupplierQuoteId: 'sq_isuzu_01',
    quotesCount: 2,
    timeline: [
      {
        title: 'Customer Approved & Credit Verified',
        timestamp: '2026-08-28T05:30:00Z',
        actor: 'Michael Chen',
        description: 'Trade credit limit verified. Ready to issue Purchase Order PO-NZ-4030.',
      },
    ],
    internalNotes: [
      {
        id: 'note_isz_1',
        author: 'Michael Chen',
        timestamp: '2026-08-28T05:45:00Z',
        text: 'Tokyo Auto Spares holding 2 units in Yokohama bonded warehouse.',
      },
    ],
    customerAttachments: [],
    documents: [],
  },
  {
    id: 'req_005',
    requestNumber: 'PR-10052',
    customerName: 'Hamilton Japanese Imports',
    customerId: 'cust_hji_01',
    customerEmail: 'parts@hji.co.nz',
    customerPhone: '+64 7 849 2011',
    customerBranch: 'Te Rapa, Hamilton',
    vehicle: {
      make: 'Nissan',
      model: 'Leaf 62kWh e+',
      year: 2020,
      vin: 'ZE1-049821',
      rego: 'EVL902',
      engineCode: 'EM57 160kW Electric',
      chassisCode: 'ZE1',
      transmission: 'Single Speed Reducer',
    },
    part: {
      name: 'Onboard Charger (OBC) & PDM Inverter Assembly',
      partNumber: '296A0-5SN0A',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      condition: 'Grade A Used',
      notes: 'Verified tested working unit from salvage Japanese vehicle. Max 25,000 km.',
      images: [],
    },
    priority: 'Normal',
    status: 'Awaiting Supplier',
    sourcingStatus: 'Supplier Contacted',
    assignedTo: 'Liam Evans',
    assignedStaffId: 'usr_liam_evans',
    createdAt: '2026-08-28T01:00:00Z',
    updatedAt: '2026-08-28T03:00:00Z',
    targetBudgetNZD: 2100,
    quotesCount: 1,
    timeline: [
      {
        title: 'RFQ Sent to Kansai Remanufacturing',
        timestamp: '2026-08-28T02:00:00Z',
        actor: 'Liam Evans',
        description: 'Requested health check certificate and diagnostic bench test output.',
      },
    ],
    internalNotes: [],
    customerAttachments: [],
    documents: [],
  },
  {
    id: 'req_006',
    requestNumber: 'PR-10053',
    customerName: 'Otago Auto Restoration',
    customerId: 'cust_otago_rest',
    customerEmail: 'repairs@otagorestore.co.nz',
    customerPhone: '+64 3 477 9900',
    customerBranch: 'Dunedin Central',
    vehicle: {
      make: 'Mazda',
      model: 'RX-7 Type-R (FD3S)',
      year: 1999,
      vin: 'FD3S-504912',
      rego: 'ROTARY',
      engineCode: '13B-REW Twin Turbo',
      chassisCode: 'FD3S',
      transmission: '5-Speed Manual',
    },
    part: {
      name: 'OEM Twin Turbo Sequential Actuator Valve Set',
      partNumber: 'N3A1-13-700A',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      condition: 'New',
      notes: 'Discontinued part in NZ. Checking Mazda Heritage Programme supply in Hiroshima/Tokyo.',
      images: [],
    },
    priority: 'High',
    status: 'New',
    sourcingStatus: 'Not Started',
    assignedTo: 'Sarah Wilson',
    assignedStaffId: 'usr_sarah_wilson',
    createdAt: '2026-08-28T06:30:00Z',
    updatedAt: '2026-08-28T06:30:00Z',
    targetBudgetNZD: 1500,
    quotesCount: 0,
    timeline: [
      {
        title: 'New Sourcing Request Logged',
        timestamp: '2026-08-28T06:30:00Z',
        actor: 'Portal Webhook',
        description: 'Customer submitted parts enquiry via Trade Portal.',
      },
    ],
    internalNotes: [],
    customerAttachments: [],
    documents: [],
  },
  {
    id: 'req_007',
    requestNumber: 'PR-10044',
    customerName: 'Bayswater Fleet Service',
    customerId: 'cust_bayswater',
    customerEmail: 'service@bayswaterfleet.co.nz',
    customerPhone: '+64 9 444 1900',
    customerBranch: 'North Shore, Auckland',
    vehicle: {
      make: 'Ford',
      model: 'Ranger Wildtrak 2.0 Bi-Turbo',
      year: 2022,
      vin: 'MNBXXMR60NP192834',
      rego: 'FOD402',
      engineCode: 'YN2X 2.0L EcoBlue Bi-Turbo',
      chassisCode: 'P703',
      transmission: '10-Speed Automatic',
    },
    part: {
      name: 'Transfer Case Electric Shift Motor',
      partNumber: 'JB3G-7G360-AA',
      quantity: 1,
      qualityPreference: 'Genuine OEM',
      condition: 'New',
      notes: '4WD system stuck in Low range.',
      images: [],
    },
    priority: 'Urgent',
    status: 'Exception',
    sourcingStatus: 'Sourcing Complete',
    assignedTo: 'Elena Rostova',
    assignedStaffId: 'usr_elena_rostova',
    createdAt: '2026-08-24T10:00:00Z',
    updatedAt: '2026-08-28T04:15:00Z',
    targetBudgetNZD: 1200,
    selectedSupplierQuoteId: 'sq_ford_01',
    purchaseOrderId: 'po_003',
    quotesCount: 2,
    timeline: [
      {
        title: 'Supplier Delayed Notification',
        timestamp: '2026-08-28T04:15:00Z',
        actor: 'Elena Rostova',
        description: 'Trans-Tasman reported 48h freight delay due to Sydney flight cargo backlogs.',
      },
    ],
    internalNotes: [
      {
        id: 'note_exc_1',
        author: 'Elena Rostova',
        timestamp: '2026-08-28T04:20:00Z',
        text: 'Raised Exception EXC-7041. Re-routing consignment on Qantas Freight flight QF143 tonight.',
      },
    ],
    customerAttachments: [],
    documents: [],
  },
];

export const INITIAL_PROCUREMENT_REQUESTS: ProcurementRequest[] = INITIAL_REQUESTS;

export const INITIAL_SUPPLIER_QUOTES: SupplierQuoteItem[] = [
  // Quotes for PR-10048 (Hilux Turbo)
  {
    id: 'sq_hilux_01',
    quoteNumber: 'SQ-9021',
    requestId: 'req_001',
    requestRef: 'PR-10048',
    supplierId: 'sup_tokyo_oem',
    supplierName: 'Tokyo Auto Spares Co., Ltd.',
    supplierCode: 'TAS-JP',
    partName: 'Turbocharger Assembly with Stepper Motor (1GD-FTV)',
    partNumber: '17201-11080',
    quantity: 1,
    condition: 'New OEM Factory Boxed',
    warrantyMonths: 12,
    unitCostNZD: 1280.0,
    freightCostNZD: 240.0,
    handlingCostNZD: 45.0,
    totalCostNZD: 1565.0,
    availability: 'In Stock',
    leadTimeDays: 3,
    leadTimeDisplay: '3 Days',
    validUntil: '2026-09-04',
    status: 'Received',
    createdAt: '2026-08-28T03:30:00Z',
    notes: 'Direct from Toyota Tsusho distribution centre. Includes factory gaskets and pre-lube syringe.',
    paymentTerms: 'Net 30 Days (Standard Trade)',
    isPreferred: true,
    attachments: [
      { name: 'TAS_Quotation_SQ9021.pdf', size: '420 KB', url: '/docs/quote_tas_9021.pdf' },
      { name: 'Toyota_OEM_Box_Photo.jpg', size: '1.8 MB', url: '/docs/turbo_tas.jpg' },
    ],
  },
  {
    id: 'sq_hilux_02',
    quoteNumber: 'SQ-9022',
    requestId: 'req_001',
    requestRef: 'PR-10048',
    supplierId: 'sup_nagoya_distrib',
    supplierName: 'Nagoya JDM Hub Supply',
    supplierCode: 'NJH-JP',
    partName: 'Turbocharger Assembly 1GD-FTV (Toyota Genuine)',
    partNumber: '17201-11080',
    quantity: 1,
    condition: 'New OEM',
    warrantyMonths: 12,
    unitCostNZD: 1340.0,
    freightCostNZD: 210.0,
    handlingCostNZD: 40.0,
    totalCostNZD: 1590.0,
    availability: '1–2 Days',
    leadTimeDays: 4,
    leadTimeDisplay: '4 Days',
    validUntil: '2026-09-03',
    status: 'Received',
    createdAt: '2026-08-28T03:40:00Z',
    notes: 'Dispatches from Nagoya terminal. Gasket kit sold separately for $35 NZD.',
    paymentTerms: 'Prepaid Wire / Telegraphic Transfer',
    isPreferred: false,
    attachments: [
      { name: 'NJH_Quote_PR10048.pdf', size: '310 KB', url: '/docs/njh_quote.pdf' },
    ],
  },
  {
    id: 'sq_hilux_03',
    quoteNumber: 'SQ-9023',
    requestId: 'req_001',
    requestRef: 'PR-10048',
    supplierId: 'sup_melbourne_aftermarket',
    supplierName: 'Trans-Tasman Auto Wholesale',
    supplierCode: 'TTA-AU',
    partName: 'Garrett OEM Replacement Turbocharger 1GD-FTV',
    partNumber: '898950-5001S',
    quantity: 1,
    condition: 'New Tier-1 OE Garrett',
    warrantyMonths: 24,
    unitCostNZD: 1420.0,
    freightCostNZD: 145.0,
    handlingCostNZD: 25.0,
    totalCostNZD: 1590.0,
    availability: 'In Stock',
    leadTimeDays: 2,
    leadTimeDisplay: '2 Days',
    validUntil: '2026-09-05',
    status: 'Received',
    createdAt: '2026-08-28T04:10:00Z',
    notes: 'Express overnight DHL from Melbourne airport to Auckland.',
    paymentTerms: 'Net 14 Days',
    isPreferred: false,
    attachments: [
      { name: 'TTA_Garrett_SpecSheet.pdf', size: '680 KB', url: '/docs/garrett_spec.pdf' },
    ],
  },

  // Quotes for PR-10049 (BMW M3 Headlight)
  {
    id: 'sq_bmw_01',
    quoteNumber: 'SQ-8994',
    requestId: 'req_002',
    requestRef: 'PR-10049',
    supplierId: 'sup_munich_euro',
    supplierName: 'Bavaria EuroParts GmbH',
    supplierCode: 'BEP-DE',
    partName: 'Laser Headlight Assembly - Right Front (RHD)',
    partNumber: '63119853318',
    quantity: 1,
    condition: 'New OEM Genuine BMW in Sealed Carton',
    warrantyMonths: 24,
    unitCostNZD: 2950.0,
    freightCostNZD: 380.0,
    handlingCostNZD: 85.0,
    totalCostNZD: 3415.0,
    availability: 'In Stock',
    leadTimeDays: 4,
    leadTimeDisplay: '4 Days',
    validUntil: '2026-09-02',
    status: 'Accepted',
    createdAt: '2026-08-27T08:00:00Z',
    notes: 'Authentic BMW AG Munich parts stock. Includes all 3 control modules.',
    paymentTerms: 'Net 30 Days (SEPA / Wire)',
    isPreferred: true,
    attachments: [
      { name: 'Bavaria_Quote_63119853318.pdf', size: '540 KB', url: '/docs/bmw_quote.pdf' },
    ],
  },
  {
    id: 'sq_bmw_02',
    quoteNumber: 'SQ-8995',
    requestId: 'req_002',
    requestRef: 'PR-10049',
    supplierId: 'sup_tokyo_oem',
    supplierName: 'Tokyo Auto Spares Co., Ltd.',
    supplierCode: 'TAS-JP',
    partName: 'BMW Laser Headlight Assembly RH (Japan Spec RHD)',
    partNumber: '63119853318',
    quantity: 1,
    condition: 'New OEM',
    warrantyMonths: 12,
    unitCostNZD: 3180.0,
    freightCostNZD: 290.0,
    handlingCostNZD: 60.0,
    totalCostNZD: 3530.0,
    availability: '3–5 Days',
    leadTimeDays: 6,
    leadTimeDisplay: '6 Days',
    validUntil: '2026-09-01',
    status: 'Rejected',
    createdAt: '2026-08-27T09:15:00Z',
    notes: 'Slightly higher unit cost than Munich distributor.',
    paymentTerms: 'Net 30 Days',
    isPreferred: false,
  },

  // Quotes for PR-10050 (Subaru DCCD)
  {
    id: 'sq_subaru_01',
    quoteNumber: 'SQ-8940',
    requestId: 'req_003',
    requestRef: 'PR-10050',
    supplierId: 'sup_nagoya_distrib',
    supplierName: 'Nagoya JDM Hub Supply',
    supplierCode: 'NJH-JP',
    partName: 'Subaru STI DCCD Differential Centre Unit',
    partNumber: '38220AA180',
    quantity: 1,
    condition: 'New OEM STI Spec',
    warrantyMonths: 12,
    unitCostNZD: 1890.0,
    freightCostNZD: 195.0,
    handlingCostNZD: 40.0,
    totalCostNZD: 2125.0,
    availability: 'In Stock',
    leadTimeDays: 3,
    leadTimeDisplay: '3 Days',
    validUntil: '2026-09-02',
    status: 'Accepted',
    createdAt: '2026-08-26T07:30:00Z',
    notes: 'OEM STI genuine part. Ready to pack.',
    paymentTerms: 'Net 30 Days',
    isPreferred: true,
  },

  // Quotes for PR-10051 (Isuzu Fuel Pump)
  {
    id: 'sq_isuzu_01',
    quoteNumber: 'SQ-9010',
    requestId: 'req_004',
    requestRef: 'PR-10051',
    supplierId: 'sup_tokyo_oem',
    supplierName: 'Tokyo Auto Spares Co., Ltd.',
    supplierCode: 'TAS-JP',
    partName: 'Isuzu 4HK1 Denso Common Rail HP Pump',
    partNumber: '8-98077-840-0',
    quantity: 2,
    condition: 'New Genuine Denso / Isuzu OEM',
    warrantyMonths: 12,
    unitCostNZD: 1650.0,
    freightCostNZD: 310.0,
    handlingCostNZD: 60.0,
    totalCostNZD: 3670.0,
    availability: 'In Stock',
    leadTimeDays: 2,
    leadTimeDisplay: '2 Days',
    validUntil: '2026-09-06',
    status: 'Accepted',
    createdAt: '2026-08-28T02:00:00Z',
    notes: 'Includes Denso test calibration bench certificate for commercial warranty compliance.',
    paymentTerms: 'Net 30 Days',
    isPreferred: true,
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrderItem[] = [
  {
    id: 'po_001',
    poNumber: 'PO-NZ-4029',
    requestId: 'req_003',
    requestRef: 'PR-10050',
    quoteId: 'sq_subaru_01',
    quoteRef: 'SQ-8940',
    supplierId: 'sup_nagoya_distrib',
    supplierName: 'Nagoya JDM Hub Supply',
    supplierContact: 'Shinji Ogawa',
    supplierEmail: 's.ogawa@nagoyajdmhub.co.jp',
    customerName: 'Precision 4WD Christchurch',
    vehicleSummary: '2019 Subaru WRX STI (VAB)',
    partName: 'DCCD Centre Differential Unit (38220AA180)',
    partNumber: '38220AA180',
    quantity: 1,
    unitPriceNZD: 1890.0,
    freightCostNZD: 195.0,
    taxNZD: 0.0, // Zero-rated export
    totalAmountNZD: 2085.0,
    status: 'Ordered',
    createdAt: '2026-08-28T05:15:00Z',
    sentAt: '2026-08-28T05:30:00Z',
    confirmedAt: '2026-08-28T06:10:00Z',
    expectedDispatchDate: '2026-08-29',
    deliveryAddress: 'Autohub Air Logistics Facility, 12 Verissimo Drive, Mangere, Auckland 2022',
    deliveryHub: 'Auckland Airport Hub',
    shippingTerms: 'FOB Nagoya / DDP Auckland Hub',
    paymentTerms: 'Net 30 Days',
    notes: 'Please pack in heavy shock-absorbing foam crate with clear Autohub barcode label PO-NZ-4029.',
    documents: [
      { title: 'Purchase Order PDF (Signed)', type: 'PO Document', url: '/docs/po_4029.pdf', size: '240 KB' },
      { title: 'Supplier Order Acknowledgment', type: 'Confirmation', url: '/docs/ack_4029.pdf', size: '180 KB' },
    ],
    timeline: [
      { stage: 'PO Created', date: '2026-08-28 17:15', done: true, note: 'Generated by Liam Evans' },
      { stage: 'Sent to Supplier', date: '2026-08-28 17:30', done: true, note: 'Transmitted via EDI & Email' },
      { stage: 'Supplier Confirmed', date: '2026-08-28 18:10', done: true, note: 'Confirmed by Shinji Ogawa' },
      { stage: 'Dispatched to Air Hub', date: '2026-08-29', done: false, note: 'Pending warehouse handover' },
      { stage: 'Received at NZ Facility', date: '2026-08-31', done: false },
    ],
  },
  {
    id: 'po_002',
    poNumber: 'PO-NZ-4028',
    requestId: 'req_002',
    requestRef: 'PR-10049',
    quoteId: 'sq_bmw_01',
    quoteRef: 'SQ-8994',
    supplierId: 'sup_munich_euro',
    supplierName: 'Bavaria EuroParts GmbH',
    supplierContact: 'Markus Weber',
    supplierEmail: 'm.weber@bavaria-europarts.de',
    customerName: 'Wellington Prestige Motors',
    vehicleSummary: '2022 BMW M3 Competition (G80)',
    partName: 'Laser Headlight Assembly - Right Front',
    partNumber: '63119853318',
    quantity: 1,
    unitPriceNZD: 2950.0,
    freightCostNZD: 380.0,
    taxNZD: 0.0,
    totalAmountNZD: 3330.0,
    status: 'Supplier Confirmed',
    createdAt: '2026-08-27T17:00:00Z',
    sentAt: '2026-08-27T17:15:00Z',
    confirmedAt: '2026-08-28T01:30:00Z',
    expectedDispatchDate: '2026-08-29',
    deliveryAddress: 'Autohub Air Logistics Facility, Mangere, Auckland',
    deliveryHub: 'Auckland Airport Hub',
    shippingTerms: 'DDP Auckland Airport',
    paymentTerms: 'Net 30 Days',
    notes: 'European export customs declaration reference DE-MUC-99182.',
    documents: [
      { title: 'Purchase Order PO-NZ-4028', type: 'PO Document', url: '/docs/po_4028.pdf', size: '280 KB' },
    ],
    timeline: [
      { stage: 'PO Created', date: '2026-08-27 17:00', done: true },
      { stage: 'Sent to Supplier', date: '2026-08-27 17:15', done: true },
      { stage: 'Supplier Confirmed', date: '2026-08-28 01:30', done: true },
      { stage: 'Dispatched to Air Hub', date: '2026-08-29', done: false },
    ],
  },
  {
    id: 'po_003',
    poNumber: 'PO-NZ-4025',
    requestId: 'req_007',
    requestRef: 'PR-10044',
    quoteId: 'sq_ford_01',
    quoteRef: 'SQ-8812',
    supplierId: 'sup_melbourne_aftermarket',
    supplierName: 'Trans-Tasman Auto Wholesale',
    supplierContact: 'Brett Henderson',
    supplierEmail: 'bhenderson@transtasmanauto.com.au',
    customerName: 'Bayswater Fleet Service',
    vehicleSummary: '2022 Ford Ranger Wildtrak 2.0 Bi-Turbo',
    partName: 'Transfer Case Shift Motor (JB3G-7G360-AA)',
    partNumber: 'JB3G-7G360-AA',
    quantity: 1,
    unitPriceNZD: 920.0,
    freightCostNZD: 110.0,
    taxNZD: 0.0,
    totalAmountNZD: 1030.0,
    status: 'Exception',
    createdAt: '2026-08-25T09:00:00Z',
    sentAt: '2026-08-25T09:30:00Z',
    confirmedAt: '2026-08-25T10:15:00Z',
    expectedDispatchDate: '2026-08-26',
    deliveryAddress: 'Autohub Air Logistics Facility, Mangere, Auckland',
    deliveryHub: 'Auckland Airport Hub',
    shippingTerms: 'FOB Melbourne',
    paymentTerms: 'Net 14 Days',
    notes: 'Transit delay logged in Sydney airport cargo terminal.',
    documents: [
      { title: 'Purchase Order PO-NZ-4025', type: 'PO Document', url: '/docs/po_4025.pdf', size: '210 KB' },
    ],
    timeline: [
      { stage: 'PO Created', date: '2026-08-25 09:00', done: true },
      { stage: 'Sent to Supplier', date: '2026-08-25 09:30', done: true },
      { stage: 'Supplier Confirmed', date: '2026-08-25 10:15', done: true },
      { stage: 'Dispatched to Air Hub', date: '2026-08-26 14:00', done: true },
      { stage: 'Flight In Transit', date: '2026-08-27', done: false, note: 'Delayed in Sydney hub' },
    ],
  },
];

export const INITIAL_TASKS: ProcurementTaskItem[] = [
  {
    id: 'task_01',
    title: 'Review quotes and compare suppliers for PR-10048 (Hilux Turbo)',
    type: 'Compare quotations',
    requestId: 'req_001',
    requestRef: 'PR-10048',
    vehicleSummary: '2023 Toyota Hilux GR Sport',
    customerName: 'Auckland EuroTech Ltd',
    priority: 'Urgent',
    dueDate: '2026-08-28T12:00:00Z',
    dueBucket: 'Today',
    isCompleted: false,
    assignedTo: 'Sarah Wilson',
    targetUrl: '/procurement/quote-comparison?requestId=req_001',
  },
  {
    id: 'task_02',
    title: 'Issue purchase order PO-NZ-4030 for PR-10051 (Isuzu Fuel Pumps)',
    type: 'Create purchase order',
    requestId: 'req_004',
    requestRef: 'PR-10051',
    vehicleSummary: '2021 Isuzu NPR 75/190 Tipper',
    customerName: 'Apex Commercial Fleet NZ',
    priority: 'Urgent',
    dueDate: '2026-08-28T14:00:00Z',
    dueBucket: 'Today',
    isCompleted: false,
    assignedTo: 'Michael Chen',
    targetUrl: '/procurement/purchase-orders?action=new&requestId=req_004',
  },
  {
    id: 'task_03',
    title: 'Contact Kansai Remanufacturing regarding Nissan Leaf PDM Inverter',
    type: 'Contact supplier',
    requestId: 'req_005',
    requestRef: 'PR-10052',
    vehicleSummary: '2020 Nissan Leaf 62kWh e+',
    customerName: 'Hamilton Japanese Imports',
    priority: 'Normal',
    dueDate: '2026-08-28T16:00:00Z',
    dueBucket: 'Today',
    isCompleted: false,
    assignedTo: 'Liam Evans',
    targetUrl: '/procurement/sourcing/req_005',
  },
  {
    id: 'task_04',
    title: 'Resolve freight delay exception EXC-7041 (Ford Ranger Motor)',
    type: 'Resolve procurement exception',
    requestId: 'req_007',
    requestRef: 'PR-10044',
    vehicleSummary: '2022 Ford Ranger Wildtrak',
    customerName: 'Bayswater Fleet Service',
    priority: 'Urgent',
    dueDate: '2026-08-27T17:00:00Z',
    dueBucket: 'Overdue',
    isCompleted: false,
    assignedTo: 'Elena Rostova',
    targetUrl: '/procurement/exceptions',
  },
  {
    id: 'task_05',
    title: 'Begin OEM heritage search for Mazda RX-7 Actuator Valve Set',
    type: 'Review sourcing request',
    requestId: 'req_006',
    requestRef: 'PR-10053',
    vehicleSummary: '1999 Mazda RX-7 (FD3S)',
    customerName: 'Otago Auto Restoration',
    priority: 'High',
    dueDate: '2026-08-29T10:00:00Z',
    dueBucket: 'Upcoming',
    isCompleted: false,
    assignedTo: 'Sarah Wilson',
    targetUrl: '/procurement/sourcing/req_006',
  },
  {
    id: 'task_06',
    title: 'Follow up BMW M3 Headlight dispatch tracking with Munich hub',
    type: 'Follow up supplier',
    requestId: 'req_002',
    requestRef: 'PR-10049',
    vehicleSummary: '2022 BMW M3 Competition',
    customerName: 'Wellington Prestige Motors',
    priority: 'Normal',
    dueDate: '2026-08-29T15:00:00Z',
    dueBucket: 'Upcoming',
    isCompleted: false,
    assignedTo: 'Sarah Wilson',
    targetUrl: '/procurement/purchase-orders/po_002',
  },
];

export const INITIAL_EXCEPTIONS: ProcurementExceptionItem[] = [
  {
    id: 'exc_001',
    code: 'EXC-7041',
    title: 'Trans-Tasman air cargo transit bottleneck at Sydney terminal',
    type: 'Shipping Delay',
    severity: 'High',
    stage: 'Supplier Communication',
    requestId: 'req_007',
    requestRef: 'PR-10044',
    poNumber: 'PO-NZ-4025',
    supplierName: 'Trans-Tasman Auto Wholesale',
    customerName: 'Bayswater Fleet Service',
    vehicleSummary: '2022 Ford Ranger Wildtrak 2.0 Bi-Turbo',
    partSummary: 'Transfer Case Shift Motor (JB3G-7G360-AA)',
    description: 'Qantas air freight flight delayed due to ground handling strikes in Sydney. Package delayed by approx 24-36 hours.',
    assignedTo: 'Elena Rostova',
    createdAt: '2026-08-28T04:15:00Z',
    updatedAt: '2026-08-28T05:30:00Z',
    actions: [
      {
        timestamp: '2026-08-28T04:20:00Z',
        user: 'Elena Rostova',
        note: 'Exception detected from DHL Global Forwarding automated tracking webhook.',
        stage: 'Review',
      },
      {
        timestamp: '2026-08-28T04:45:00Z',
        user: 'Elena Rostova',
        note: 'Assigned to Elena Rostova. Contacted supplier logistics rep Brett Henderson.',
        stage: 'Assign',
      },
      {
        timestamp: '2026-08-28T05:30:00Z',
        user: 'Elena Rostova',
        note: 'Supplier negotiated priority re-manifest on Qantas flight QF143 direct to AKL arriving 29 Aug 06:00.',
        stage: 'Supplier Communication',
      },
    ],
  },
  {
    id: 'exc_002',
    code: 'EXC-7039',
    title: 'Part condition minor scratch on chrome surround',
    type: 'Wrong Part',
    severity: 'Medium',
    stage: 'Resolution',
    requestId: 'req_002',
    requestRef: 'PR-10049',
    supplierName: 'Bavaria EuroParts GmbH',
    customerName: 'Wellington Prestige Motors',
    vehicleSummary: '2022 BMW M3 Competition',
    partSummary: 'Laser Headlight (Alternative batch)',
    description: 'Pre-dispatch quality photo inspection in Munich revealed minor blemish on non-OEM outer packaging box. Verified part intact.',
    assignedTo: 'Sarah Wilson',
    createdAt: '2026-08-27T10:00:00Z',
    updatedAt: '2026-08-27T15:00:00Z',
    resolution: 'Munich hub repacked into reinforced flight crate and certified 100% optical perfection.',
    resolvedAt: '2026-08-27T15:00:00Z',
    actions: [
      {
        timestamp: '2026-08-27T10:00:00Z',
        user: 'Sarah Wilson',
        note: 'Photo inspection flagged during sourcing verification.',
        stage: 'Investigate',
      },
      {
        timestamp: '2026-08-27T15:00:00Z',
        user: 'Sarah Wilson',
        note: 'Markus Weber sent replacement batch photo with 10/10 quality clearance.',
        stage: 'Resolution',
      },
    ],
  },
];

export const INITIAL_CONVERSATIONS: SupplierConversation[] = [
  {
    id: 'conv_01',
    supplierId: 'sup_tokyo_oem',
    supplierName: 'Tokyo Auto Spares Co., Ltd.',
    lastMessage: 'Hai Sarah-san, we have prepared the calibration test sheet for the Hilux turbo and Isuzu pumps.',
    lastMessageTime: '18 mins ago',
    unreadCount: 1,
    relatedRequestRef: 'PR-10048',
    relatedPoNumber: 'PO-NZ-4030',
    messages: [
      {
        id: 'msg_01',
        supplierId: 'sup_tokyo_oem',
        supplierName: 'Tokyo Auto Spares Co., Ltd.',
        requestId: 'req_001',
        requestRef: 'PR-10048',
        sender: 'Sarah Wilson',
        senderRole: 'Procurement Specialist',
        isInternalNote: false,
        message: 'Konnichiwa Kenji-san. Can you confirm if part 17201-11080 is genuine factory Toyota and in stock at Yokohama?',
        timestamp: '2026-08-27T10:15:00Z',
      },
      {
        id: 'msg_02',
        supplierId: 'sup_tokyo_oem',
        supplierName: 'Tokyo Auto Spares Co., Ltd.',
        requestId: 'req_001',
        requestRef: 'PR-10048',
        sender: 'Kenji Takahashi',
        senderRole: 'Supplier Representative',
        isInternalNote: false,
        message: 'Konnichiwa Sarah-san! Yes, we have 4 units brand new in Toyota factory carton in Yokohama warehouse. Quote SQ-9021 submitted.',
        timestamp: '2026-08-28T03:30:00Z',
      },
      {
        id: 'msg_03',
        supplierId: 'sup_tokyo_oem',
        supplierName: 'Tokyo Auto Spares Co., Ltd.',
        sender: 'Sarah Wilson',
        senderRole: 'Procurement Specialist',
        isInternalNote: true,
        message: 'INTERNAL NOTE: Kenji agreed to waive the $45 handling fee if we bundle the Isuzu HP pump order today.',
        timestamp: '2026-08-28T04:00:00Z',
      },
      {
        id: 'msg_04',
        supplierId: 'sup_tokyo_oem',
        supplierName: 'Tokyo Auto Spares Co., Ltd.',
        sender: 'Kenji Takahashi',
        senderRole: 'Supplier Representative',
        isInternalNote: false,
        message: 'Hai Sarah-san, we have prepared the calibration test sheet for the Hilux turbo and Isuzu pumps.',
        timestamp: '2026-08-28T06:05:00Z',
      },
    ],
  },
  {
    id: 'conv_02',
    supplierId: 'sup_munich_euro',
    supplierName: 'Bavaria EuroParts GmbH',
    lastMessage: 'Order PO-NZ-4028 acknowledged. Packing will finish by 14:00 Munich time today.',
    lastMessageTime: '3 hours ago',
    unreadCount: 0,
    relatedRequestRef: 'PR-10049',
    relatedPoNumber: 'PO-NZ-4028',
    messages: [
      {
        id: 'msg_bav_1',
        supplierId: 'sup_munich_euro',
        supplierName: 'Bavaria EuroParts GmbH',
        sender: 'Sarah Wilson',
        senderRole: 'Procurement Specialist',
        isInternalNote: false,
        message: 'Hi Markus, PO-NZ-4028 has been issued for the BMW G80 laser headlight. Please confirm expected air waybill number.',
        timestamp: '2026-08-27T17:15:00Z',
      },
      {
        id: 'msg_bav_2',
        supplierId: 'sup_munich_euro',
        supplierName: 'Bavaria EuroParts GmbH',
        sender: 'Markus Weber',
        senderRole: 'Supplier Representative',
        isInternalNote: false,
        message: 'Order PO-NZ-4028 acknowledged. Packing will finish by 14:00 Munich time today. Lufthansa Cargo tracking to follow.',
        timestamp: '2026-08-28T01:30:00Z',
      },
    ],
  },
];

export const INITIAL_DOCUMENTS: ProcurementDocumentItem[] = [
  {
    id: 'pdoc_01',
    title: 'Supplier Quotation SQ-9021 (Hilux Turbo OEM)',
    type: 'Supplier Quote',
    requestId: 'req_001',
    requestRef: 'PR-10048',
    supplierName: 'Tokyo Auto Spares Co., Ltd.',
    customerName: 'Auckland EuroTech Ltd',
    date: '2026-08-28',
    uploadedBy: 'Sarah Wilson',
    fileSize: '420 KB',
    fileFormat: 'PDF',
    downloadUrl: '/docs/quote_tas_9021.pdf',
    isInternalOnly: false,
  },
  {
    id: 'pdoc_02',
    title: 'Purchase Order PO-NZ-4029 (Subaru STI DCCD)',
    type: 'Purchase Order',
    requestId: 'req_003',
    requestRef: 'PR-10050',
    poNumber: 'PO-NZ-4029',
    supplierName: 'Nagoya JDM Hub Supply',
    customerName: 'Precision 4WD Christchurch',
    date: '2026-08-28',
    uploadedBy: 'Liam Evans',
    fileSize: '240 KB',
    fileFormat: 'PDF',
    downloadUrl: '/docs/po_4029.pdf',
    isInternalOnly: false,
  },
  {
    id: 'pdoc_03',
    title: 'Supplier Proforma Invoice INV-TAS-88192',
    type: 'Supplier Invoice',
    requestId: 'req_004',
    requestRef: 'PR-10051',
    poNumber: 'PO-NZ-4030',
    supplierName: 'Tokyo Auto Spares Co., Ltd.',
    customerName: 'Apex Commercial Fleet NZ',
    date: '2026-08-28',
    uploadedBy: 'Michael Chen',
    fileSize: '380 KB',
    fileFormat: 'PDF',
    downloadUrl: '/docs/inv_88192.pdf',
    isInternalOnly: true,
  },
  {
    id: 'pdoc_04',
    title: 'Air Waybill & Customs Export Declaration (Munich - Auckland)',
    type: 'Freight Document',
    requestId: 'req_002',
    requestRef: 'PR-10049',
    poNumber: 'PO-NZ-4028',
    supplierName: 'Bavaria EuroParts GmbH',
    customerName: 'Wellington Prestige Motors',
    date: '2026-08-27',
    uploadedBy: 'Elena Rostova',
    fileSize: '1.4 MB',
    fileFormat: 'PDF',
    downloadUrl: '/docs/awb_lufthansa.pdf',
    isInternalOnly: false,
  },
  {
    id: 'pdoc_05',
    title: 'Denso Commercial Calibration Certificate & Packing Slip',
    type: 'Packing Document',
    requestId: 'req_004',
    requestRef: 'PR-10051',
    supplierName: 'Tokyo Auto Spares Co., Ltd.',
    customerName: 'Apex Commercial Fleet NZ',
    date: '2026-08-28',
    uploadedBy: 'Michael Chen',
    fileSize: '890 KB',
    fileFormat: 'PDF',
    downloadUrl: '/docs/denso_cert.pdf',
    isInternalOnly: false,
  },
];

export const INITIAL_SHIPMENTS: ShipmentDispatchItem[] = [
  {
    id: 'shp_01',
    shipmentNumber: 'SHP-8092',
    requestId: 'req_003',
    requestRef: 'PR-10050',
    poNumber: 'PO-NZ-4029',
    customerName: 'Precision 4WD Christchurch',
    supplierName: 'Nagoya JDM Hub Supply',
    partName: 'Subaru STI DCCD Differential',
    partNumber: '38220AA180',
    quantity: 1,
    freightMethod: 'Air Freight',
    carrier: 'Air New Zealand Cargo / Nippon Express',
    trackingCode: 'NZ-CARGO-7749219',
    currentLocation: 'Nagoya Chubu Centrair Cargo Terminal',
    originHub: 'Nagoya (NGO)',
    destinationHub: 'Auckland Airport (AKL)',
    eta: '2026-08-31 14:00',
    status: 'Ready for Dispatch',
    weightKg: 8.4,
    dimensionsCm: '35 x 30 x 28',
    verifiedChecklist: {
      partVerified: true,
      quantityVerified: true,
      supplierVerified: true,
      shippingInfoVerified: true,
    },
  },
  {
    id: 'shp_02',
    shipmentNumber: 'SHP-8089',
    requestId: 'req_002',
    requestRef: 'PR-10049',
    poNumber: 'PO-NZ-4028',
    customerName: 'Wellington Prestige Motors',
    supplierName: 'Bavaria EuroParts GmbH',
    partName: 'BMW M3 Laser Headlight Assembly',
    partNumber: '63119853318',
    quantity: 1,
    freightMethod: 'Air Express',
    carrier: 'DHL Express International',
    trackingCode: 'DHL-EX-99281044',
    currentLocation: 'Munich Airport Hub (MUC) - In Flight to Singapore Transit',
    originHub: 'Munich (MUC)',
    destinationHub: 'Auckland Airport (AKL)',
    eta: '2026-08-30 08:30',
    status: 'In Transit',
    weightKg: 6.2,
    dimensionsCm: '75 x 40 x 35',
    verifiedChecklist: {
      partVerified: true,
      quantityVerified: true,
      supplierVerified: true,
      shippingInfoVerified: true,
    },
  },
  {
    id: 'shp_03',
    shipmentNumber: 'SHP-8077',
    requestId: 'req_007',
    requestRef: 'PR-10044',
    poNumber: 'PO-NZ-4025',
    customerName: 'Bayswater Fleet Service',
    supplierName: 'Trans-Tasman Auto Wholesale',
    partName: 'Transfer Case Shift Motor (Ford Ranger)',
    partNumber: 'JB3G-7G360-AA',
    quantity: 1,
    freightMethod: 'Air Freight',
    carrier: 'Qantas Freight',
    trackingCode: 'QF-FRT-1430992',
    currentLocation: 'Sydney Kingsford Smith Cargo Bay (Delayed transit)',
    originHub: 'Melbourne (MEL)',
    destinationHub: 'Auckland Airport (AKL)',
    eta: '2026-08-29 06:00 (Revised)',
    status: 'Exception',
    exceptionNote: 'Delayed due to Sydney ground handling backlog. Rescheduled onto QF143.',
    weightKg: 3.1,
    dimensionsCm: '25 x 20 x 18',
    verifiedChecklist: {
      partVerified: true,
      quantityVerified: true,
      supplierVerified: true,
      shippingInfoVerified: true,
    },
  },
];

export const INITIAL_NOTIFICATIONS: ProcurementNotificationItem[] = [
  {
    id: 'notif_01',
    title: 'Supplier Quote Received: SQ-9021',
    description: 'Tokyo Auto Spares submitted quote for PR-10048 (Hilux Turbo OEM). Unit cost $1,280 NZD.',
    type: 'Supplier quote received',
    timestamp: '25 mins ago',
    isRead: false,
    requestId: 'req_001',
    targetUrl: '/procurement/quote-comparison?requestId=req_001',
    priority: 'Urgent',
  },
  {
    id: 'notif_02',
    title: 'Customer Trade Payment Received',
    description: 'Precision 4WD Christchurch paid $2,760 NZD for Subaru WRX STI DCCD. PO-NZ-4029 ready.',
    type: 'Payment received',
    timestamp: '1 hour ago',
    isRead: false,
    requestId: 'req_003',
    targetUrl: '/procurement/purchase-orders/po_001',
    priority: 'High',
  },
  {
    id: 'notif_03',
    title: 'New Urgent Request Assigned',
    description: 'Assigned PR-10051 (Isuzu Fuel Pumps x2) for fleet repair with 48h turnaround requirement.',
    type: 'New request assigned',
    timestamp: '2 hours ago',
    isRead: false,
    requestId: 'req_004',
    targetUrl: '/procurement/requests/req_004',
    priority: 'Urgent',
  },
  {
    id: 'notif_04',
    title: 'Logistics Alert: Transit Exception EXC-7041',
    description: 'Qantas Freight reported delay in Sydney hub for Ford Ranger Transfer Motor.',
    type: 'Shipment exception',
    timestamp: '3 hours ago',
    isRead: true,
    requestId: 'req_007',
    targetUrl: '/procurement/exceptions',
    priority: 'High',
  },
  {
    id: 'notif_05',
    title: 'Quote Expiring in 24 Hours',
    description: 'Supplier quote SQ-8994 for BMW M3 laser headlight valid until 02 Sept.',
    type: 'Quote expiring',
    timestamp: '5 hours ago',
    isRead: true,
    requestId: 'req_002',
    targetUrl: '/procurement/supplier-quotes/sq_bmw_01',
    priority: 'Normal',
  },
];
