// PROCURly Finance Portal Mock Data Repository
import {
  FinanceStaffUser,
  FinancePayment,
  AwaitingPaymentItem,
  FinanceTransaction,
  CreditAccount,
  RefundItem,
  FinancialException,
  FinanceCustomerQuote,
  ApprovedOrderFinance,
  CustomerFinancialProfile,
  FinanceTask,
  FinanceNotification,
  FinanceDocument,
} from '@/types/finance';

export const INITIAL_FINANCE_STAFF: FinanceStaffUser[] = [
  {
    id: 'usr_claire_vance',
    name: 'Claire Vance',
    email: 'claire.vance@autohub.co.nz',
    role: 'Financial Controller',
    avatar: 'CV',
    phone: '+64 21 445 102',
    department: 'Commercial Treasury & Risk',
    permissions: ['ALL_PERMISSIONS', 'APPROVE_HIGH_CREDIT', 'AUTHORIZE_REFUNDS', 'RELEASE_ORDERS'],
  },
  {
    id: 'usr_david_maclean',
    name: 'David MacLean',
    email: 'david.maclean@autohub.co.nz',
    role: 'Senior Finance Manager',
    avatar: 'DM',
    phone: '+64 21 789 231',
    department: 'Accounts Receivable & Settlements',
    permissions: ['VERIFY_PAYMENTS', 'MANAGE_INVOICES', 'CLEAR_ORDERS', 'EXPORT_LEDGERS'],
  },
  {
    id: 'usr_anita_sharma',
    name: 'Anita Sharma',
    email: 'anita.sharma@autohub.co.nz',
    role: 'Credit & Collections Lead',
    avatar: 'AS',
    phone: '+64 22 901 884',
    department: 'Trade Credit & Customer Risk',
    permissions: ['ADJUST_CREDIT_LIMITS', 'MANAGE_HOLDS', 'SEND_REMINDERS', 'COLLECTIONS_ESCALATION'],
  },
  {
    id: 'usr_marcus_wong',
    name: 'Marcus Wong',
    email: 'marcus.wong@autohub.co.nz',
    role: 'Accounts & Reconciliation Officer',
    avatar: 'MW',
    phone: '+64 27 334 519',
    department: 'Bank Reconciliation & Gateway Ops',
    permissions: ['RECONCILE_TRANSACTIONS', 'RECORD_PAYMENTS', 'INVESTIGATE_EXCEPTIONS'],
  },
  {
    id: 'usr_sophia_bennett',
    name: 'Sophia Bennett',
    email: 'sophia.bennett@autohub.co.nz',
    role: 'Financial Compliance Auditor',
    avatar: 'SB',
    phone: '+64 21 662 908',
    department: 'Audit, Tax & NZ Inland Revenue',
    permissions: ['VIEW_AUDIT_LOGS', 'GENERATE_TAX_REPORTS', 'EXPORT_LEDGERS'],
  },
];

export const INITIAL_FINANCE_PAYMENTS: FinancePayment[] = [
  {
    id: 'PAY-00123',
    requestNumber: 'AH-P-000123',
    orderNumber: 'ORD-2026-0089',
    customerId: 'cus_autocare_akl',
    customerName: 'AutoCare Auckland',
    customerEmail: 'accounts@autocareauckland.co.nz',
    amount: 485.0,
    subtotal: 395.0,
    freight: 26.96,
    gst: 63.04,
    method: 'Card',
    status: 'Received',
    paymentDate: '28 Aug 2026, 14:22',
    gatewayReference: 'ch_3Nxp4Z2eZvKYlo2C1g9fL2m9',
    authCode: 'AUTH-991823',
    cardBrand: 'Visa',
    cardLast4: '4242',
    allocatedBy: 'Claire Vance',
    receiptNumber: 'REC-2026-0123',
    invoiceNumber: 'INV-2026-0123',
    quoteNumber: 'QUO-000123-v3',
    partsSummary: 'Toyota Hiace Left Front Lower Control Arm',
    vehicleSummary: '2019 Toyota Hiace (3.0L Diesel KDH201)',
    internalNotes: ['Card payment processed automatically via Stripe. Funds settled to BNZ master merchant.'],
    auditTrail: [
      {
        id: 'aud_1',
        timestamp: '28 Aug 2026, 14:22:10',
        actor: 'AutoCare Auckland (Customer)',
        actorRole: 'Customer',
        action: 'Payment Submitted',
        details: 'Card authorized for NZ$485.00 via Stripe Gateway',
      },
      {
        id: 'aud_2',
        timestamp: '28 Aug 2026, 14:22:15',
        actor: 'System Automated Clearance',
        actorRole: 'System',
        action: 'Financial Clearance Granted',
        details: 'Verified payment confirmation. Auto-released request to Procurement pipeline.',
      },
    ],
  },
  {
    id: 'PAY-00122',
    requestNumber: 'AH-P-000122',
    orderNumber: 'ORD-2026-0088',
    customerId: 'cus_central_motors',
    customerName: 'Central Motors',
    customerEmail: 'finance@centralmotors.co.nz',
    amount: 720.0,
    subtotal: 580.0,
    freight: 46.09,
    gst: 93.91,
    method: 'Bank Transfer',
    status: 'Pending',
    paymentDate: '28 Aug 2026, 11:45',
    dueDate: '29 Aug 2026',
    gatewayReference: 'ANZ-PAY-00122-REF',
    bankAccountLast4: '8814',
    allocatedBy: 'David MacLean',
    invoiceNumber: 'INV-2026-0122',
    quoteNumber: 'QUO-2026-0122',
    partsSummary: 'Subaru Impreza WRX STI EJ207 Genuine High-Pressure Fuel Pump',
    vehicleSummary: '2016 Subaru WRX STI VAB (EJ207 Turbo)',
    internalNotes: ['Customer submitted manual bank remittance. Pending BNZ direct clearing feed reconciliation.'],
    auditTrail: [
      {
        id: 'aud_3',
        timestamp: '28 Aug 2026, 11:45:00',
        actor: 'Central Motors',
        actorRole: 'Customer',
        action: 'Bank Remittance Uploaded',
        details: 'Customer flagged ANZ manual transfer of NZ$720.00',
      },
    ],
  },
  {
    id: 'PAY-00121',
    requestNumber: 'AH-P-000121',
    orderNumber: 'ORD-2026-0087',
    customerId: 'cus_west_auto',
    customerName: 'West Auto',
    customerEmail: 'service@westauto.co.nz',
    amount: 310.0,
    subtotal: 240.0,
    freight: 29.57,
    gst: 40.43,
    method: 'Card',
    status: 'Failed',
    paymentDate: '27 Aug 2026, 17:15',
    failureReason: 'Declined: Do not honour (Card issuer blocked transaction / daily threshold reached)',
    cardBrand: 'Mastercard',
    cardLast4: '9012',
    quoteNumber: 'QUO-2026-0121',
    partsSummary: 'Mazda CX-5 KE Rear Shock Absorber Kit',
    vehicleSummary: '2015 Mazda CX-5 KE5FW (PY-VPS 2.5L)',
    internalNotes: ['Automatic SMS/Email failed payment alert dispatched to customer. Customer contacted by phone.'],
    auditTrail: [
      {
        id: 'aud_4',
        timestamp: '27 Aug 2026, 17:15:33',
        actor: 'Stripe Gateway',
        actorRole: 'Payment Gateway',
        action: 'Payment Failed',
        details: 'Card declined: generic_decline. Status code 402.',
      },
    ],
  },
  {
    id: 'PAY-00120',
    requestNumber: 'AH-P-000120',
    orderNumber: 'ORD-2026-0086',
    customerId: 'cus_tauranga_euro',
    customerName: 'Tauranga Euro Specialists',
    customerEmail: 'parts@taurangaeuro.co.nz',
    amount: 1850.0,
    subtotal: 1520.0,
    freight: 88.7,
    gst: 241.3,
    method: 'Trade Credit',
    status: 'Credit Approved',
    paymentDate: '27 Aug 2026, 13:00',
    receiptNumber: 'CRD-2026-0120',
    invoiceNumber: 'INV-2026-0120',
    quoteNumber: 'QUO-2026-0120',
    partsSummary: 'BMW N55 Turbocharger Core Assembly & Gasket Kit',
    vehicleSummary: '2014 BMW 335i F30 (N55 TwinPower)',
    internalNotes: ['Approved against active Trade Credit facility. Available credit remaining: $20,900.'],
    auditTrail: [
      {
        id: 'aud_5',
        timestamp: '27 Aug 2026, 13:00:12',
        actor: 'Anita Sharma',
        actorRole: 'Credit & Collections Lead',
        action: 'Trade Credit Allocated',
        details: 'NZ$1,850.00 debited against approved credit limit. Financially cleared.',
      },
    ],
  },
  {
    id: 'PAY-00119',
    requestNumber: 'AH-P-000119',
    orderNumber: 'ORD-2026-0085',
    customerId: 'cus_south_island_fleet',
    customerName: 'South Island Fleet Services',
    customerEmail: 'ap@sifleet.co.nz',
    amount: 3450.0,
    subtotal: 2850.0,
    freight: 150.0,
    gst: 450.0,
    method: 'Account2Account',
    status: 'Received',
    paymentDate: '26 Aug 2026, 16:20',
    gatewayReference: 'A2A-BNZ-998124',
    receiptNumber: 'REC-2026-0119',
    invoiceNumber: 'INV-2026-0119',
    quoteNumber: 'QUO-2026-0119',
    partsSummary: 'Isuzu Forward FSR Complete Turbo Manifold & Injectors (Set of 6)',
    vehicleSummary: '2017 Isuzu Forward FSR90 (4HK1-TCS Diesel)',
    internalNotes: ['Instant A2A direct bank settlement cleared immediately.'],
    auditTrail: [
      {
        id: 'aud_6',
        timestamp: '26 Aug 2026, 16:20:05',
        actor: 'Account2Account Gateway',
        actorRole: 'Gateway',
        action: 'Direct Bank Settlement',
        details: 'NZ$3,450.00 received and confirmed by BNZ API.',
      },
    ],
  },
  {
    id: 'PAY-00118',
    requestNumber: 'AH-P-000118',
    orderNumber: 'ORD-2026-0084',
    customerId: 'cus_autocare_akl',
    customerName: 'AutoCare Auckland',
    customerEmail: 'accounts@autocareauckland.co.nz',
    amount: 1240.0,
    subtotal: 1020.0,
    freight: 58.26,
    gst: 161.74,
    method: 'Card',
    status: 'Refunded',
    paymentDate: '24 Aug 2026, 09:30',
    gatewayReference: 'ch_3Nwx882eZvKYlo2C0p1q8A9',
    receiptNumber: 'REC-2026-0118',
    invoiceNumber: 'INV-2026-0118',
    quoteNumber: 'QUO-2026-0118',
    partsSummary: 'Nissan Leaf ZE1 40kWh Replacement Inverter Assembly',
    vehicleSummary: '2019 Nissan Leaf ZE1 (EM57 EV)',
    internalNotes: ['Refund processed in full: Supplier confirmed part out of stock in Yokohama depot with no ETA.'],
    auditTrail: [
      {
        id: 'aud_7',
        timestamp: '24 Aug 2026, 09:30:00',
        actor: 'AutoCare Auckland',
        actorRole: 'Customer',
        action: 'Payment Received',
        details: 'NZ$1,240.00 settled via Card',
      },
      {
        id: 'aud_8',
        timestamp: '25 Aug 2026, 15:40:00',
        actor: 'Claire Vance',
        actorRole: 'Financial Controller',
        action: 'Refund Authorized',
        details: 'Full refund of NZ$1,240.00 issued to original Visa *4242 (REF-0089).',
      },
    ],
  },
  {
    id: 'PAY-00117',
    requestNumber: 'AH-P-000117',
    orderNumber: 'ORD-2026-0083',
    customerId: 'cus_north_shore_auto',
    customerName: 'North Shore Auto Group',
    customerEmail: 'admin@northshoreauto.co.nz',
    amount: 980.0,
    subtotal: 810.0,
    freight: 42.17,
    gst: 127.83,
    method: 'Card',
    status: 'Failed',
    paymentDate: '28 Aug 2026, 08:10',
    failureReason: 'Card Expired / Insufficient Funds',
    cardBrand: 'Visa',
    cardLast4: '1109',
    quoteNumber: 'QUO-2026-0117',
    partsSummary: 'Audi Q7 4L Front Air Suspension Strut (Pair)',
    vehicleSummary: '2013 Audi Q7 3.0 TDI (CRCA)',
    internalNotes: ['Attempted retry at 10:00 AM failed again. Follow-up task assigned to Marcus Wong.'],
    auditTrail: [
      {
        id: 'aud_9',
        timestamp: '28 Aug 2026, 08:10:22',
        actor: 'Stripe Gateway',
        actorRole: 'Gateway',
        action: 'Card Failed',
        details: 'Card failed: insufficient_funds',
      },
    ],
  },
  {
    id: 'PAY-00116',
    requestNumber: 'AH-P-000116',
    orderNumber: 'ORD-2026-0082',
    customerId: 'cus_wellington_diesel',
    customerName: 'Wellington Commercial Diesel',
    customerEmail: 'billing@wellingtondiesel.co.nz',
    amount: 5885.0,
    subtotal: 4900.0,
    freight: 220.0,
    gst: 765.0,
    method: 'Bank Transfer',
    status: 'Received',
    paymentDate: '28 Aug 2026, 12:10',
    gatewayReference: 'BNZ-TRF-00116-CONF',
    receiptNumber: 'REC-2026-0116',
    invoiceNumber: 'INV-2026-0116',
    quoteNumber: 'QUO-2026-0116',
    partsSummary: 'Hino 500 Series J08E Reconditioned Short Block Assembly',
    vehicleSummary: '2018 Hino 500 Series (J08E 7.7L Turbo)',
    internalNotes: ['High-value bank transfer verified directly with BNZ commercial desk. Cleared for dispatch.'],
    auditTrail: [
      {
        id: 'aud_10',
        timestamp: '28 Aug 2026, 12:10:00',
        actor: 'David MacLean',
        actorRole: 'Senior Finance Manager',
        action: 'Manual Reconciliation',
        details: 'Verified funds deposited in BNZ 02-0100-XXXX. Cleared to Procurement.',
      },
    ],
  },
];

export const INITIAL_AWAITING_PAYMENTS: AwaitingPaymentItem[] = [
  {
    id: 'AWT-001',
    requestNumber: 'AH-P-000125',
    orderNumber: 'ORD-2026-0091',
    customerId: 'cus_west_auto',
    customerName: 'West Auto',
    contactEmail: 'service@westauto.co.nz',
    contactPhone: '+64 9 834 7711',
    quoteValue: 2450.0,
    amountDue: 2450.0,
    quoteDate: '22 Aug 2026',
    dueDate: '25 Aug 2026',
    daysOutstanding: 3,
    agingBucket: '1-7 Days',
    status: 'Overdue',
    paymentMethodExpected: 'Card',
    lastReminderDate: '27 Aug 2026',
    reminderCount: 2,
    notes: 'Quote accepted by workshop manager on 22 Aug. Payment link sent via SMS and Email.',
  },
  {
    id: 'AWT-002',
    requestNumber: 'AH-P-000126',
    orderNumber: 'ORD-2026-0092',
    customerId: 'cus_central_motors',
    customerName: 'Central Motors',
    contactEmail: 'finance@centralmotors.co.nz',
    contactPhone: '+64 7 855 4321',
    quoteValue: 1820.0,
    amountDue: 1820.0,
    quoteDate: '28 Aug 2026',
    dueDate: '28 Aug 2026',
    daysOutstanding: 0,
    agingBucket: 'Current',
    status: 'Due Today',
    paymentMethodExpected: 'Bank Transfer',
    reminderCount: 1,
    notes: 'Invoice INV-2026-0126 generated. Remittance advice promised by 5 PM today.',
  },
  {
    id: 'AWT-003',
    requestNumber: 'AH-P-000127',
    orderNumber: 'ORD-2026-0093',
    customerId: 'cus_north_shore_auto',
    customerName: 'North Shore Auto Group',
    contactEmail: 'admin@northshoreauto.co.nz',
    contactPhone: '+64 9 489 9000',
    quoteValue: 1680.0,
    amountDue: 1680.0,
    quoteDate: '15 Aug 2026',
    dueDate: '18 Aug 2026',
    daysOutstanding: 10,
    agingBucket: '8-30 Days',
    status: 'Escalated',
    paymentMethodExpected: 'Card',
    lastReminderDate: '26 Aug 2026',
    reminderCount: 3,
    notes: 'Account near credit cap. Escalated to Anita Sharma for trade hold review.',
  },
  {
    id: 'AWT-004',
    requestNumber: 'AH-P-000128',
    orderNumber: 'ORD-2026-0094',
    customerId: 'cus_penrose_mechanics',
    customerName: 'Penrose Commercial Mechanics',
    contactEmail: 'accounts@penrosemechanics.co.nz',
    contactPhone: '+64 9 579 1100',
    quoteValue: 1300.0,
    amountDue: 1300.0,
    quoteDate: '27 Aug 2026',
    dueDate: '30 Aug 2026',
    daysOutstanding: 0,
    agingBucket: 'Current',
    status: 'Due Soon',
    paymentMethodExpected: 'Card',
    reminderCount: 0,
    notes: 'Customer approved quote yesterday. Standard 3-day approval window.',
  },
];

export const INITIAL_FINANCE_TRANSACTIONS: FinanceTransaction[] = [
  {
    id: 'TXN-998231',
    reference: 'PAY-00123',
    requestNumber: 'AH-P-000123',
    orderNumber: 'ORD-2026-0089',
    customerId: 'cus_autocare_akl',
    customerName: 'AutoCare Auckland',
    type: 'Payment',
    amount: 485.0,
    fee: 8.49,
    netAmount: 476.51,
    currency: 'NZD',
    method: 'Card',
    status: 'Reconciled',
    gatewayId: 'ch_3Nxp4Z2eZvKYlo2C1g9fL2m9',
    channel: 'Online Portal',
    timestamp: '28 Aug 2026, 14:22:10',
    reconciledAt: '28 Aug 2026, 15:00:00',
    reconciledBy: 'Marcus Wong',
    description: 'Customer payment for Toyota Hiace Control Arms',
  },
  {
    id: 'TXN-998230',
    reference: 'PAY-00116',
    requestNumber: 'AH-P-000116',
    orderNumber: 'ORD-2026-0082',
    customerId: 'cus_wellington_diesel',
    customerName: 'Wellington Commercial Diesel',
    type: 'Payment',
    amount: 5885.0,
    fee: 0.0,
    netAmount: 5885.0,
    currency: 'NZD',
    method: 'Bank Transfer',
    status: 'Reconciled',
    gatewayId: 'BNZ-TRF-00116-CONF',
    channel: 'Direct Bank Wire',
    timestamp: '28 Aug 2026, 12:10:00',
    reconciledAt: '28 Aug 2026, 12:45:00',
    reconciledBy: 'David MacLean',
    description: 'Direct wire deposit for Hino 500 Reconditioned Short Block',
  },
  {
    id: 'TXN-998229',
    reference: 'PAY-00122',
    requestNumber: 'AH-P-000122',
    orderNumber: 'ORD-2026-0088',
    customerId: 'cus_central_motors',
    customerName: 'Central Motors',
    type: 'Payment',
    amount: 720.0,
    fee: 0.0,
    netAmount: 720.0,
    currency: 'NZD',
    method: 'Bank Transfer',
    status: 'Pending',
    gatewayId: 'ANZ-PAY-00122-REF',
    channel: 'Direct Bank Wire',
    timestamp: '28 Aug 2026, 11:45:00',
    description: 'Pending clearing wire for Subaru WRX STI Fuel Pump',
  },
  {
    id: 'TXN-998228',
    reference: 'PAY-00120',
    requestNumber: 'AH-P-000120',
    orderNumber: 'ORD-2026-0086',
    customerId: 'cus_tauranga_euro',
    customerName: 'Tauranga Euro Specialists',
    type: 'Credit',
    amount: 1850.0,
    fee: 0.0,
    netAmount: 1850.0,
    currency: 'NZD',
    method: 'Trade Credit',
    status: 'Completed',
    gatewayId: 'CRD-LEDGER-00120',
    channel: 'Trade Ledger',
    timestamp: '27 Aug 2026, 13:00:12',
    description: 'Approved trade credit allocation for BMW N55 Turbo Kit',
  },
  {
    id: 'TXN-998227',
    reference: 'REF-0089',
    requestNumber: 'AH-P-000118',
    orderNumber: 'ORD-2026-0084',
    customerId: 'cus_autocare_akl',
    customerName: 'AutoCare Auckland',
    type: 'Refund',
    amount: -1240.0,
    fee: -2.5,
    netAmount: -1237.5,
    currency: 'NZD',
    method: 'Card',
    status: 'Completed',
    gatewayId: 're_3Nwx882eZvKYlo2C0p1q8A9',
    channel: 'Online Portal',
    timestamp: '25 Aug 2026, 15:40:00',
    reconciledAt: '25 Aug 2026, 16:00:00',
    reconciledBy: 'Claire Vance',
    description: 'Full refund for unavailable Nissan Leaf ZE1 Inverter',
  },
  {
    id: 'TXN-998226',
    reference: 'ADJ-2026-041',
    requestNumber: 'AH-P-000112',
    customerId: 'cus_south_island_fleet',
    customerName: 'South Island Fleet Services',
    type: 'Adjustment',
    amount: -150.0,
    fee: 0.0,
    netAmount: -150.0,
    currency: 'NZD',
    method: 'Account2Account',
    status: 'Completed',
    gatewayId: 'ADJ-CREDIT-9921',
    channel: 'Trade Ledger',
    timestamp: '25 Aug 2026, 10:15:00',
    reconciledAt: '25 Aug 2026, 10:30:00',
    reconciledBy: 'Anita Sharma',
    description: 'Logistics consolidation freight rebate on consolidated shipment',
  },
];

export const INITIAL_CREDIT_ACCOUNTS: CreditAccount[] = [
  {
    id: 'ACC-CR-001',
    customerId: 'cus_autocare_akl',
    customerName: 'AutoCare Auckland',
    nzbn: '9429038819201',
    creditLimit: 20000.0,
    creditUsed: 8400.0,
    creditAvailable: 11600.0,
    utilizationPct: 42.0,
    outstandingAmount: 8400.0,
    overdueAmount: 0.0,
    paymentTerms: '20th of Month Following',
    status: 'Active',
    riskRating: 'Low',
    approvedDate: '15 Jan 2025',
    approvedBy: 'Claire Vance',
    reviewDate: '15 Jan 2027',
    contactPerson: 'Graeme Collins',
    contactEmail: 'accounts@autocareauckland.co.nz',
    contactPhone: '+64 9 525 8890',
    billingAddress: '42 Great South Road, Penrose, Auckland 1061',
    creditTransactions: [
      {
        id: 'cl_1',
        date: '20 Aug 2026',
        orderNumber: 'ORD-2026-0081',
        description: 'Toyota Hilux 1GD Engine Assembly',
        debit: 5200.0,
        credit: 0.0,
        balance: 8400.0,
        recordedBy: 'Anita Sharma',
      },
      {
        id: 'cl_2',
        date: '10 Aug 2026',
        orderNumber: 'PMT-JULY-STATEMENT',
        description: 'July Statement Settlement via BNZ Direct Debit',
        debit: 0.0,
        credit: 7800.0,
        balance: 3200.0,
        recordedBy: 'Marcus Wong',
      },
    ],
    holdsHistory: [],
  },
  {
    id: 'ACC-CR-002',
    customerId: 'cus_central_motors',
    customerName: 'Central Motors',
    nzbn: '9429041192834',
    creditLimit: 15000.0,
    creditUsed: 14200.0,
    creditAvailable: 800.0,
    utilizationPct: 94.7,
    outstandingAmount: 14200.0,
    overdueAmount: 1200.0,
    paymentTerms: 'Net 30 Days',
    status: 'Near Limit',
    riskRating: 'Medium',
    approvedDate: '01 Mar 2025',
    approvedBy: 'Claire Vance',
    reviewDate: '01 Sep 2026',
    contactPerson: 'Jason Wright',
    contactEmail: 'finance@centralmotors.co.nz',
    contactPhone: '+64 7 855 4321',
    billingAddress: '112 Te Rapa Road, Hamilton 3200',
    creditTransactions: [
      {
        id: 'cl_3',
        date: '22 Aug 2026',
        orderNumber: 'ORD-2026-0079',
        description: 'Subaru Levorg FA20 DIT Transmission',
        debit: 4800.0,
        credit: 0.0,
        balance: 14200.0,
        recordedBy: 'Anita Sharma',
      },
    ],
    holdsHistory: [
      {
        id: 'ch_1',
        date: '24 Aug 2026',
        action: 'Placed on Hold',
        reason: 'Credit threshold exceeded $14,000 without prior expansion authorization.',
        performedBy: 'Anita Sharma',
      },
      {
        id: 'ch_2',
        date: '25 Aug 2026',
        action: 'Hold Lifted',
        reason: 'Customer made interim $2,000 settlement. Limit capped at $15k.',
        performedBy: 'Claire Vance',
      },
    ],
  },
  {
    id: 'ACC-CR-003',
    customerId: 'cus_west_auto',
    customerName: 'West Auto',
    nzbn: '9429037748190',
    creditLimit: 10000.0,
    creditUsed: 10250.0,
    creditAvailable: 0.0,
    utilizationPct: 102.5,
    outstandingAmount: 10250.0,
    overdueAmount: 4350.0,
    paymentTerms: 'Net 14 Days',
    status: 'Overdue',
    riskRating: 'High',
    approvedDate: '10 Nov 2024',
    approvedBy: 'David MacLean',
    reviewDate: '10 May 2026',
    contactPerson: 'Darren Price',
    contactEmail: 'service@westauto.co.nz',
    contactPhone: '+64 9 834 7711',
    billingAddress: '88 Lincoln Road, Henderson, Auckland 0610',
    creditTransactions: [],
    holdsHistory: [
      {
        id: 'ch_3',
        date: '18 Aug 2026',
        action: 'Suspended',
        reason: 'Overdue balance of $4,350 past 30 days. Auto-ordering restricted.',
        performedBy: 'Anita Sharma',
      },
    ],
  },
  {
    id: 'ACC-CR-004',
    customerId: 'cus_tauranga_euro',
    customerName: 'Tauranga Euro Specialists',
    nzbn: '9429048891273',
    creditLimit: 25000.0,
    creditUsed: 4100.0,
    creditAvailable: 20900.0,
    utilizationPct: 16.4,
    outstandingAmount: 4100.0,
    overdueAmount: 0.0,
    paymentTerms: '20th of Month Following',
    status: 'Active',
    riskRating: 'Low',
    approvedDate: '12 Feb 2025',
    approvedBy: 'Claire Vance',
    reviewDate: '12 Feb 2027',
    contactPerson: 'Stefan Meyer',
    contactEmail: 'parts@taurangaeuro.co.nz',
    contactPhone: '+64 7 578 3344',
    billingAddress: '15 Hewletts Road, Mount Maunganui 3116',
    creditTransactions: [],
    holdsHistory: [],
  },
  {
    id: 'ACC-CR-005',
    customerId: 'cus_south_island_fleet',
    customerName: 'South Island Fleet Services',
    nzbn: '9429031129984',
    creditLimit: 30000.0,
    creditUsed: 18500.0,
    creditAvailable: 11500.0,
    utilizationPct: 61.7,
    outstandingAmount: 18500.0,
    overdueAmount: 0.0,
    paymentTerms: '20th of Month Following',
    status: 'Active',
    riskRating: 'Low',
    approvedDate: '05 Jan 2024',
    approvedBy: 'Claire Vance',
    reviewDate: '05 Jan 2027',
    contactPerson: 'Hamish McLeod',
    contactEmail: 'ap@sifleet.co.nz',
    contactPhone: '+64 3 348 9011',
    billingAddress: '55 Waterloo Road, Hornby, Christchurch 8042',
    creditTransactions: [],
    holdsHistory: [],
  },
  {
    id: 'ACC-CR-006',
    customerId: 'cus_north_shore_auto',
    customerName: 'North Shore Auto Group',
    nzbn: '9429039918234',
    creditLimit: 12000.0,
    creditUsed: 12000.0,
    creditAvailable: 0.0,
    utilizationPct: 100.0,
    outstandingAmount: 12000.0,
    overdueAmount: 2800.0,
    paymentTerms: 'Net 30 Days',
    status: 'On Hold',
    riskRating: 'High',
    approvedDate: '18 Apr 2025',
    approvedBy: 'Claire Vance',
    reviewDate: '18 Oct 2026',
    contactPerson: 'Brendan Kelly',
    contactEmail: 'admin@northshoreauto.co.nz',
    contactPhone: '+64 9 489 9000',
    billingAddress: '210 Wairau Road, Glenfield, Auckland 0627',
    creditTransactions: [],
    holdsHistory: [
      {
        id: 'ch_4',
        date: '20 Aug 2026',
        action: 'Placed on Hold',
        reason: 'Credit limit reached 100% capacity and overdue invoice outstanding.',
        performedBy: 'Anita Sharma',
      },
    ],
  },
];

export const INITIAL_REFUNDS: RefundItem[] = [
  {
    id: 'REF-0089',
    paymentId: 'PAY-00118',
    requestNumber: 'AH-P-000118',
    orderNumber: 'ORD-2026-0084',
    customerId: 'cus_autocare_akl',
    customerName: 'AutoCare Auckland',
    originalAmount: 1240.0,
    refundAmount: 1240.0,
    reason: 'Part Unavailable at Origin',
    detailedReason: 'Japanese supplier Tokyo Auto Spares Co confirmed zero stock of Nissan Leaf ZE1 Inverter in warehouse with no manufacturing run scheduled.',
    status: 'Refunded',
    requestedBy: 'Sarah Wilson (Procurement)',
    requestedDate: '25 Aug 2026, 11:20',
    reviewedBy: 'David MacLean',
    reviewedDate: '25 Aug 2026, 14:00',
    processedBy: 'Claire Vance',
    processedDate: '25 Aug 2026, 15:40',
    refundMethod: 'Card',
    destinationAccountRef: 'Visa ending 4242 (Stripe re_3Nwx882eZvKYlo2C0p1q8A9)',
    approvalHistory: [
      {
        stage: 'Procurement Sourcing Discontinuation',
        actor: 'Sarah Wilson',
        timestamp: '25 Aug 2026, 11:20',
        outcome: 'Approved',
        comments: 'Part unavailable from all 3 Japanese vendor channels.',
      },
      {
        stage: 'Finance Risk & Ledger Review',
        actor: 'David MacLean',
        timestamp: '25 Aug 2026, 14:00',
        outcome: 'Approved',
        comments: 'Original payment confirmed. Full refund clearance warranted.',
      },
      {
        stage: 'Treasury Settlement Execution',
        actor: 'Claire Vance',
        timestamp: '25 Aug 2026, 15:40',
        outcome: 'Approved',
        comments: 'Stripe refund executed. Customer notified via email.',
      },
    ],
    auditTrail: [
      {
        id: 'aud_ref_1',
        timestamp: '25 Aug 2026, 15:40:12',
        actor: 'Claire Vance',
        actorRole: 'Financial Controller',
        action: 'Refund Processed',
        details: 'NZ$1,240.00 refunded via Stripe API',
      },
    ],
  },
  {
    id: 'REF-0090',
    paymentId: 'PAY-00121',
    requestNumber: 'AH-P-000121',
    orderNumber: 'ORD-2026-0087',
    customerId: 'cus_west_auto',
    customerName: 'West Auto',
    originalAmount: 310.0,
    refundAmount: 310.0,
    reason: 'Customer Cancellation Before Dispatch',
    detailedReason: 'Customer vehicle was written off by insurance prior to part shipment.',
    status: 'Under Review',
    requestedBy: 'Darren Price (Customer)',
    requestedDate: '27 Aug 2026, 18:30',
    reviewedBy: 'Marcus Wong',
    reviewedDate: '28 Aug 2026, 09:15',
    refundMethod: 'Card',
    destinationAccountRef: 'Mastercard ending 9012',
    approvalHistory: [
      {
        stage: 'Customer Service Intake',
        actor: 'Marcus Wong',
        timestamp: '28 Aug 2026, 09:15',
        outcome: 'Pending',
        comments: 'Confirming logistics cancellation with Auckland handling hub.',
      },
    ],
    auditTrail: [],
  },
  {
    id: 'REF-0091',
    paymentId: 'PAY-00115',
    requestNumber: 'AH-P-000115',
    orderNumber: 'ORD-2026-0081',
    customerId: 'cus_penrose_mechanics',
    customerName: 'Penrose Commercial Mechanics',
    originalAmount: 850.0,
    refundAmount: 180.0,
    reason: 'Pricing Adjustment / Freight Rebate',
    detailedReason: 'Freight consolidation rebate approved following air-to-sea sea freight conversion requested by customer.',
    status: 'Approved',
    requestedBy: 'Liam Evans (Procurement)',
    requestedDate: '28 Aug 2026, 10:00',
    reviewedBy: 'Claire Vance',
    reviewedDate: '28 Aug 2026, 11:30',
    refundMethod: 'Bank Transfer',
    destinationAccountRef: 'ANZ Account 01-0288-0091823-00',
    approvalHistory: [
      {
        stage: 'Freight Rate Audit',
        actor: 'Liam Evans',
        timestamp: '28 Aug 2026, 10:00',
        outcome: 'Approved',
        comments: 'Verified NZ$180.00 difference in air vs ocean freight rate.',
      },
      {
        stage: 'Finance Approval',
        actor: 'Claire Vance',
        timestamp: '28 Aug 2026, 11:30',
        outcome: 'Approved',
        comments: 'Partial refund approved for queue dispatch.',
      },
    ],
    auditTrail: [],
  },
];

export const INITIAL_FINANCIAL_EXCEPTIONS: FinancialException[] = [
  {
    id: 'EXC-FIN-0041',
    type: 'Payment Failed',
    severity: 'Critical',
    stage: 'Investigate',
    requestNumber: 'AH-P-000121',
    paymentId: 'PAY-00121',
    customerId: 'cus_west_auto',
    customerName: 'West Auto',
    amountAtRisk: 310.0,
    detectedAt: '27 Aug 2026, 17:15',
    assignedOfficer: 'Marcus Wong',
    assignedOfficerAvatar: 'MW',
    summary: 'Card payment failed twice due to issuer threshold decline on workshop Visa.',
    investigationFindings: 'Customer card expired yesterday; customer requested bank invoice or secondary card link.',
    resolutionNotes: 'Generated Account2Account direct transfer link and dispatched to customer.',
    status: 'In Progress',
    timeline: [
      {
        stage: 'Detect',
        timestamp: '27 Aug 2026, 17:15',
        actor: 'System Gateway',
        note: 'Payment failure webhook received from Stripe.',
      },
      {
        stage: 'Review',
        timestamp: '27 Aug 2026, 17:30',
        actor: 'Claire Vance',
        note: 'Flagged as high-urgency part for stranded vehicle.',
      },
      {
        stage: 'Assign',
        timestamp: '28 Aug 2026, 08:30',
        actor: 'Claire Vance',
        note: 'Assigned to Marcus Wong for phone verification.',
      },
      {
        stage: 'Investigate',
        timestamp: '28 Aug 2026, 09:40',
        actor: 'Marcus Wong',
        note: 'Spoke with Darren at West Auto; replacement debit card provided.',
      },
    ],
  },
  {
    id: 'EXC-FIN-0042',
    type: 'Credit Limit Exceeded',
    severity: 'High',
    stage: 'Take Action',
    requestNumber: 'AH-P-000124',
    customerId: 'cus_central_motors',
    customerName: 'Central Motors',
    amountAtRisk: 14200.0,
    detectedAt: '28 Aug 2026, 09:10',
    assignedOfficer: 'Anita Sharma',
    assignedOfficerAvatar: 'AS',
    summary: 'Central Motors approved quote exceeds available trade credit facility by $600.',
    investigationFindings: 'Customer has 2 open orders totaling $14.2k against $15k limit. New request is $1.4k.',
    resolutionNotes: 'Require interim remittance of $1,200 overdue balance before clearing new order.',
    status: 'In Progress',
    timeline: [
      {
        stage: 'Detect',
        timestamp: '28 Aug 2026, 09:10',
        actor: 'Credit Engine',
        note: 'Automatic credit block triggered.',
      },
      {
        stage: 'Review',
        timestamp: '28 Aug 2026, 09:30',
        actor: 'Anita Sharma',
        note: 'Reviewed 6-month payment behavior; 94% on-time record.',
      },
      {
        stage: 'Take Action',
        timestamp: '28 Aug 2026, 11:00',
        actor: 'Anita Sharma',
        note: 'Offered temporary 7-day limit extension or prompt bank transfer settlement.',
      },
    ],
  },
  {
    id: 'EXC-FIN-0043',
    type: 'Payment Mismatch',
    severity: 'Medium',
    stage: 'Resolve',
    requestNumber: 'AH-P-000119',
    paymentId: 'PAY-00119',
    customerId: 'cus_south_island_fleet',
    customerName: 'South Island Fleet Services',
    amountAtRisk: 3450.0,
    detectedAt: '26 Aug 2026, 16:25',
    assignedOfficer: 'David MacLean',
    assignedOfficerAvatar: 'DM',
    summary: 'Bank wire reference omitted customer reference prefix on BNZ feed.',
    investigationFindings: 'Remittance matched against statement amount and NZBN entity name.',
    resolutionNotes: 'Matched manual BNZ reference to PAY-00119. Allocated in ledger.',
    status: 'Resolved',
    timeline: [
      {
        stage: 'Detect',
        timestamp: '26 Aug 2026, 16:25',
        actor: 'BNZ Reconciliation Bot',
        note: 'Unmatched deposit of $3,450.00 identified.',
      },
      {
        stage: 'Investigate',
        timestamp: '27 Aug 2026, 09:00',
        actor: 'David MacLean',
        note: 'Customer accounts department confirmed wire timestamp.',
      },
      {
        stage: 'Resolve',
        timestamp: '27 Aug 2026, 10:15',
        actor: 'David MacLean',
        note: 'Transaction reconciled. Order released.',
      },
    ],
  },
  {
    id: 'EXC-FIN-0044',
    type: 'Duplicate Payment',
    severity: 'Medium',
    stage: 'Close',
    requestNumber: 'AH-P-000114',
    customerId: 'cus_autocare_akl',
    customerName: 'AutoCare Auckland',
    amountAtRisk: 420.0,
    detectedAt: '24 Aug 2026, 14:00',
    assignedOfficer: 'Claire Vance',
    assignedOfficerAvatar: 'CV',
    summary: 'Customer submitted dual credit card authorizations for identical quote.',
    investigationFindings: 'Second transaction reversed immediately prior to settlement cut-off.',
    resolutionNotes: 'Stripe authorization voided. No double charge occurred.',
    status: 'Closed',
    timeline: [
      {
        stage: 'Detect',
        timestamp: '24 Aug 2026, 14:00',
        actor: 'Stripe Webhook',
        note: 'Idempotency key collision resolved.',
      },
      {
        stage: 'Close',
        timestamp: '24 Aug 2026, 14:10',
        actor: 'Claire Vance',
        note: 'Void confirmed. Exception closed.',
      },
    ],
  },
];

export const INITIAL_CUSTOMER_QUOTES_FINANCE: FinanceCustomerQuote[] = [
  {
    id: 'QUO-2026-0123',
    quoteNumber: 'QUO-000123-v3',
    requestNumber: 'AH-P-000123',
    customerId: 'cus_autocare_akl',
    customerName: 'AutoCare Auckland',
    vehicleSummary: '2019 Toyota Hiace (3.0L Diesel KDH201)',
    partsSummary: 'Toyota Hiace Left Front Lower Control Arm',
    partsSubtotal: 395.0,
    freightCost: 26.96,
    customsDuty: 0.0,
    marginAmount: 78.5,
    gstAmount: 63.04,
    totalAmount: 485.0,
    quoteDate: '28 Aug 2026',
    validUntil: '04 Sep 2026',
    status: 'Approved by Customer',
    paymentStatus: 'Paid',
    financialClearanceReady: true,
    clearedForProcurement: true,
  },
  {
    id: 'QUO-2026-0122',
    quoteNumber: 'QUO-2026-0122',
    requestNumber: 'AH-P-000122',
    customerId: 'cus_central_motors',
    customerName: 'Central Motors',
    vehicleSummary: '2016 Subaru WRX STI VAB (EJ207 Turbo)',
    partsSummary: 'Subaru Impreza WRX STI EJ207 Genuine High-Pressure Fuel Pump',
    partsSubtotal: 580.0,
    freightCost: 46.09,
    customsDuty: 0.0,
    marginAmount: 110.0,
    gstAmount: 93.91,
    totalAmount: 720.0,
    quoteDate: '28 Aug 2026',
    validUntil: '04 Sep 2026',
    status: 'Approved by Customer',
    paymentStatus: 'Pending',
    financialClearanceReady: false,
    clearedForProcurement: false,
  },
  {
    id: 'QUO-2026-0120',
    quoteNumber: 'QUO-2026-0120',
    requestNumber: 'AH-P-000120',
    customerId: 'cus_tauranga_euro',
    customerName: 'Tauranga Euro Specialists',
    vehicleSummary: '2014 BMW 335i F30 (N55 TwinPower)',
    partsSummary: 'BMW N55 Turbocharger Core Assembly & Gasket Kit',
    partsSubtotal: 1520.0,
    freightCost: 88.7,
    customsDuty: 0.0,
    marginAmount: 320.0,
    gstAmount: 241.3,
    totalAmount: 1850.0,
    quoteDate: '27 Aug 2026',
    validUntil: '03 Sep 2026',
    status: 'Approved by Customer',
    paymentStatus: 'Credit Approved',
    financialClearanceReady: true,
    clearedForProcurement: true,
  },
  {
    id: 'QUO-2026-0124',
    quoteNumber: 'QUO-2026-0124',
    requestNumber: 'AH-P-000124',
    customerId: 'cus_north_shore_auto',
    customerName: 'North Shore Auto Group',
    vehicleSummary: '2017 Lexus RX450h GYL25 (2GR-FXS Hybrid)',
    partsSummary: 'Lexus RX450h Genuine Inverter Water Pump & Coolant Manifold',
    partsSubtotal: 820.0,
    freightCost: 45.0,
    customsDuty: 0.0,
    marginAmount: 145.0,
    gstAmount: 130.5,
    totalAmount: 995.5,
    quoteDate: '28 Aug 2026',
    validUntil: '04 Sep 2026',
    status: 'Sent',
    paymentStatus: 'Awaiting Payment',
    financialClearanceReady: false,
    clearedForProcurement: false,
  },
];

export const INITIAL_APPROVED_ORDERS_FINANCE: ApprovedOrderFinance[] = [
  {
    id: 'ORD-2026-0089',
    orderNumber: 'ORD-2026-0089',
    requestNumber: 'AH-P-000123',
    customerId: 'cus_autocare_akl',
    customerName: 'AutoCare Auckland',
    totalAmount: 485.0,
    partsCost: 395.0,
    freightCost: 26.96,
    margin: 78.5,
    gst: 63.04,
    orderDate: '28 Aug 2026',
    approvedDate: '28 Aug 2026, 14:20',
    paymentMethod: 'Card',
    paymentStatus: 'Received',
    clearanceStatus: 'Financially Cleared',
    creditVerified: true,
    clearedAt: '28 Aug 2026, 14:22:15',
    clearedBy: 'System Automated Clearance',
    releasedToProcurementAt: '28 Aug 2026, 14:22:20',
    procurementPoRef: 'PO-2026-0089',
    notes: 'Paid in full via Visa. Instant clearance dispatched to Sarah Wilson (Procurement Lead).',
    parts: [
      {
        name: 'Toyota Hiace TRH200 Front Lower Control Arm (LH)',
        partNumber: '48069-26140',
        qty: 1,
        unitPrice: 197.5,
      },
      {
        name: 'Toyota Hiace TRH200 Front Lower Control Arm (RH)',
        partNumber: '48068-26140',
        qty: 1,
        unitPrice: 197.5,
      },
    ],
  },
  {
    id: 'ORD-2026-0088',
    orderNumber: 'ORD-2026-0088',
    requestNumber: 'AH-P-000122',
    customerId: 'cus_central_motors',
    customerName: 'Central Motors',
    totalAmount: 720.0,
    partsCost: 580.0,
    freightCost: 46.09,
    margin: 110.0,
    gst: 93.91,
    orderDate: '28 Aug 2026',
    approvedDate: '28 Aug 2026, 11:40',
    paymentMethod: 'Bank Transfer',
    paymentStatus: 'Pending',
    clearanceStatus: 'Awaiting Payment',
    creditVerified: false,
    notes: 'Awaiting bank confirmation before issuing PO to Nagoya JDM Hub.',
    parts: [
      {
        name: 'Subaru Impreza WRX STI EJ207 High-Pressure Fuel Pump',
        partNumber: '42022FE011',
        qty: 1,
        unitPrice: 580.0,
      },
    ],
  },
  {
    id: 'ORD-2026-0086',
    orderNumber: 'ORD-2026-0086',
    requestNumber: 'AH-P-000120',
    customerId: 'cus_tauranga_euro',
    customerName: 'Tauranga Euro Specialists',
    totalAmount: 1850.0,
    partsCost: 1520.0,
    freightCost: 88.7,
    margin: 320.0,
    gst: 241.3,
    orderDate: '27 Aug 2026',
    approvedDate: '27 Aug 2026, 12:55',
    paymentMethod: 'Trade Credit',
    paymentStatus: 'Credit Approved',
    clearanceStatus: 'Financially Cleared',
    creditVerified: true,
    clearedAt: '27 Aug 2026, 13:00:12',
    clearedBy: 'Anita Sharma',
    releasedToProcurementAt: '27 Aug 2026, 13:02:00',
    procurementPoRef: 'PO-2026-0086',
    notes: 'Credit verified. Customer balance within healthy limit. PO dispatched to Munich Euro Auto Spares.',
    parts: [
      {
        name: 'BMW N55 Turbocharger Core Assembly',
        partNumber: '11657636424',
        qty: 1,
        unitPrice: 1520.0,
      },
    ],
  },
  {
    id: 'ORD-2026-0085',
    orderNumber: 'ORD-2026-0085',
    requestNumber: 'AH-P-000119',
    customerId: 'cus_south_island_fleet',
    customerName: 'South Island Fleet Services',
    totalAmount: 3450.0,
    partsCost: 2850.0,
    freightCost: 150.0,
    margin: 550.0,
    gst: 450.0,
    orderDate: '26 Aug 2026',
    approvedDate: '26 Aug 2026, 16:15',
    paymentMethod: 'Account2Account',
    paymentStatus: 'Received',
    clearanceStatus: 'Financially Cleared',
    creditVerified: true,
    clearedAt: '26 Aug 2026, 16:20:05',
    clearedBy: 'Marcus Wong',
    releasedToProcurementAt: '26 Aug 2026, 16:25:00',
    procurementPoRef: 'PO-2026-0085',
    notes: 'A2A verified. Heavy commercial priority procurement released.',
    parts: [
      {
        name: 'Isuzu Forward FSR Turbo Manifold & Injectors (Set of 6)',
        partNumber: '8-98012-345-0',
        qty: 1,
        unitPrice: 2850.0,
      },
    ],
  },
];

export const INITIAL_CUSTOMER_FINANCIAL_PROFILES: CustomerFinancialProfile[] = [
  {
    id: 'cus_autocare_akl',
    name: 'AutoCare Auckland',
    nzbn: '9429038819201',
    legalEntity: 'AutoCare Auckland Limited',
    accountType: 'Trade Credit Account',
    accountStatus: 'Active',
    creditStatus: 'Active',
    creditLimit: 20000.0,
    currentExposure: 8400.0,
    availableCredit: 11600.0,
    outstandingBalance: 8400.0,
    overdueBalance: 0.0,
    lifetimeRevenue: 48520.0,
    lifetimeOrdersCount: 38,
    lastPaymentDate: '28 Aug 2026',
    lastPaymentAmount: 485.0,
    paymentBehaviour: 'Excellent (100% on time)',
    creditTerms: '20th of Month Following',
    billingEmail: 'accounts@autocareauckland.co.nz',
    phone: '+64 9 525 8890',
    address: '42 Great South Road, Penrose, Auckland 1061',
    financialNotes: 'Long-standing tier-1 trade partner with direct electronic debit authorization and spotless 24-month payment history.',
  },
  {
    id: 'cus_central_motors',
    name: 'Central Motors',
    nzbn: '9429041192834',
    legalEntity: 'Central Motors Hamilton Limited',
    accountType: 'Trade Credit Account',
    accountStatus: 'Active',
    creditStatus: 'Near Limit',
    creditLimit: 15000.0,
    currentExposure: 14200.0,
    availableCredit: 800.0,
    outstandingBalance: 14200.0,
    overdueBalance: 1200.0,
    lifetimeRevenue: 32100.0,
    lifetimeOrdersCount: 24,
    lastPaymentDate: '25 Aug 2026',
    lastPaymentAmount: 2000.0,
    paymentBehaviour: 'Good (94% on time)',
    creditTerms: 'Net 30 Days',
    billingEmail: 'finance@centralmotors.co.nz',
    phone: '+64 7 855 4321',
    address: '112 Te Rapa Road, Hamilton 3200',
    financialNotes: 'High-volume workshop. Currently at 94.7% credit utilization. Requires monitoring before new PO authorization.',
  },
  {
    id: 'cus_west_auto',
    name: 'West Auto',
    nzbn: '9429037748190',
    legalEntity: 'West Auto Services Ltd',
    accountType: 'Cash / Pre-Payment Only',
    accountStatus: 'Under Review',
    creditStatus: 'Overdue',
    creditLimit: 10000.0,
    currentExposure: 10250.0,
    availableCredit: 0.0,
    outstandingBalance: 10250.0,
    overdueBalance: 4350.0,
    lifetimeRevenue: 19800.0,
    lifetimeOrdersCount: 15,
    lastPaymentDate: '12 Aug 2026',
    lastPaymentAmount: 1100.0,
    paymentBehaviour: 'High Risk (Repeated Overdue)',
    creditTerms: 'Net 14 Days (Restricted to Pre-Payment)',
    billingEmail: 'service@westauto.co.nz',
    phone: '+64 9 834 7711',
    address: '88 Lincoln Road, Henderson, Auckland 0610',
    financialNotes: 'Overdue balance of $4,350 past 30 days. Auto-ordering restricted. Pre-payment via Stripe / A2A required.',
  },
  {
    id: 'cus_tauranga_euro',
    name: 'Tauranga Euro Specialists',
    nzbn: '9429048891273',
    legalEntity: 'Bay of Plenty Euro Parts Limited',
    accountType: 'Trade Credit Account',
    accountStatus: 'Active',
    creditStatus: 'Active',
    creditLimit: 25000.0,
    currentExposure: 4100.0,
    availableCredit: 20900.0,
    utilizationPct: 16.4,
    outstandingBalance: 4100.0,
    overdueBalance: 0.0,
    lifetimeRevenue: 64200.0,
    lifetimeOrdersCount: 42,
    lastPaymentDate: '27 Aug 2026',
    lastPaymentAmount: 1850.0,
    paymentBehaviour: 'Excellent (100% on time)',
    creditTerms: '20th of Month Following',
    billingEmail: 'parts@taurangaeuro.co.nz',
    phone: '+64 7 578 3344',
    address: '15 Hewletts Road, Mount Maunganui 3116',
    financialNotes: 'Premium German vehicle specialist. Consistently settles accounts within terms.',
  },
  {
    id: 'cus_south_island_fleet',
    name: 'South Island Fleet Services',
    nzbn: '9429031129984',
    legalEntity: 'South Island Heavy Fleet Logistics Ltd',
    accountType: 'Fleet Enterprise',
    accountStatus: 'Active',
    creditStatus: 'Active',
    creditLimit: 30000.0,
    currentExposure: 18500.0,
    availableCredit: 11500.0,
    outstandingBalance: 18500.0,
    overdueBalance: 0.0,
    lifetimeRevenue: 98400.0,
    lifetimeOrdersCount: 65,
    lastPaymentDate: '26 Aug 2026',
    lastPaymentAmount: 3450.0,
    paymentBehaviour: 'Excellent (100% on time)',
    creditTerms: '20th of Month Following',
    billingEmail: 'ap@sifleet.co.nz',
    phone: '+64 3 348 9011',
    address: '55 Waterloo Road, Hornby, Christchurch 8042',
    financialNotes: 'Enterprise fleet contract covering commercial diesel powertrains across Canterbury & Otago.',
  },
  {
    id: 'cus_north_shore_auto',
    name: 'North Shore Auto Group',
    nzbn: '9429039918234',
    legalEntity: 'North Shore Prestige Motors Ltd',
    accountType: 'Trade Credit Account',
    accountStatus: 'On Hold',
    creditStatus: 'Suspended',
    creditLimit: 12000.0,
    currentExposure: 12000.0,
    availableCredit: 0.0,
    outstandingBalance: 12000.0,
    overdueBalance: 2800.0,
    lifetimeRevenue: 28900.0,
    lifetimeOrdersCount: 20,
    lastPaymentDate: '15 Aug 2026',
    lastPaymentAmount: 1400.0,
    paymentBehaviour: 'Watchlist (Delayed)',
    creditTerms: 'Net 30 Days',
    billingEmail: 'admin@northshoreauto.co.nz',
    phone: '+64 9 489 9000',
    address: '210 Wairau Road, Glenfield, Auckland 0627',
    financialNotes: 'Trade facility temporarily on hold pending settlement of $2,800 overdue invoice from July ledger.',
  },
];

export const INITIAL_FINANCE_TASKS: FinanceTask[] = [
  {
    id: 'TSK-FIN-001',
    title: 'Verify Bank Remittance for Central Motors ($720.00)',
    category: 'Verify Payment',
    priority: 'Urgent',
    dueDate: '28 Aug 2026, 17:00',
    dueCategory: 'Due Today',
    targetUrl: '/finance/payments/PAY-00122',
    referenceId: 'PAY-00122',
    assignedTo: 'David MacLean',
    isCompleted: false,
  },
  {
    id: 'TSK-FIN-002',
    title: 'Review Failed Card Payment for West Auto ($310.00)',
    category: 'Review Failed Payment',
    priority: 'Urgent',
    dueDate: '28 Aug 2026, 16:30',
    dueCategory: 'Due Today',
    targetUrl: '/finance/exceptions/EXC-FIN-0041',
    referenceId: 'EXC-FIN-0041',
    assignedTo: 'Marcus Wong',
    isCompleted: false,
  },
  {
    id: 'TSK-FIN-003',
    title: 'Confirm Credit Cap Extension Request for Central Motors',
    category: 'Confirm Credit Account',
    priority: 'High',
    dueDate: '29 Aug 2026, 12:00',
    dueCategory: 'Upcoming',
    targetUrl: '/finance/credit-accounts/cus_central_motors',
    referenceId: 'cus_central_motors',
    assignedTo: 'Anita Sharma',
    isCompleted: false,
  },
  {
    id: 'TSK-FIN-004',
    title: 'Process Customer Refund Request REF-0090 ($310.00)',
    category: 'Process Refund',
    priority: 'High',
    dueDate: '29 Aug 2026, 15:00',
    dueCategory: 'Upcoming',
    targetUrl: '/finance/refunds/REF-0090',
    referenceId: 'REF-0090',
    assignedTo: 'Claire Vance',
    isCompleted: false,
  },
  {
    id: 'TSK-FIN-005',
    title: 'Review Overdue Balances on 8-30 Day Aging Queue',
    category: 'Review Outstanding Payment',
    priority: 'Normal',
    dueDate: '30 Aug 2026, 17:00',
    dueCategory: 'Upcoming',
    targetUrl: '/finance/awaiting-payment',
    referenceId: 'AWT-003',
    assignedTo: 'Anita Sharma',
    isCompleted: false,
  },
  {
    id: 'TSK-FIN-006',
    title: 'Reconcile Stripe Gateway Settlement Batch #8812',
    category: 'Reconcile Transaction',
    priority: 'Normal',
    dueDate: '28 Aug 2026, 18:00',
    dueCategory: 'Due Today',
    targetUrl: '/finance/transactions',
    referenceId: 'TXN-998231',
    assignedTo: 'Marcus Wong',
    isCompleted: true,
    completedAt: '28 Aug 2026, 15:00',
    completedBy: 'Marcus Wong',
  },
];

export const INITIAL_FINANCE_NOTIFICATIONS: FinanceNotification[] = [
  {
    id: 'notif_fin_1',
    title: 'Payment Received — NZ$485.00',
    description: 'AutoCare Auckland settled PAY-00123 via Visa Card. Cleared for Procurement.',
    category: 'Payment Received',
    timestamp: '28 Aug 2026, 14:22',
    timeAgo: '28m ago',
    isRead: false,
    severity: 'Success',
    targetUrl: '/finance/payments/PAY-00123',
  },
  {
    id: 'notif_fin_2',
    title: 'Payment Failed — Card Declined (NZ$310.00)',
    description: 'West Auto payment attempt for AH-P-000121 declined by card issuer.',
    category: 'Payment Failed',
    timestamp: '27 Aug 2026, 17:15',
    timeAgo: 'Yesterday',
    isRead: false,
    severity: 'Critical',
    targetUrl: '/finance/exceptions/EXC-FIN-0041',
  },
  {
    id: 'notif_fin_3',
    title: 'Credit Limit Reached — Central Motors (94.7%)',
    description: 'Central Motors has reached $14,200 of $15,000 credit ceiling.',
    category: 'Credit Limit Reached',
    timestamp: '28 Aug 2026, 09:10',
    timeAgo: '5h ago',
    isRead: false,
    severity: 'Warning',
    targetUrl: '/finance/credit-accounts/cus_central_motors',
  },
  {
    id: 'notif_fin_4',
    title: 'Refund Processed — REF-0089 (NZ$1,240.00)',
    description: 'Full refund for unavailable Nissan Leaf Inverter completed via Stripe.',
    category: 'Refund Approved',
    timestamp: '25 Aug 2026, 15:40',
    timeAgo: '3 days ago',
    isRead: true,
    severity: 'Info',
    targetUrl: '/finance/refunds/REF-0089',
  },
  {
    id: 'notif_fin_5',
    title: 'Payment Overdue — West Auto (3 Days)',
    description: 'Invoice for AH-P-000125 is 3 days overdue ($2,450.00). Second reminder sent.',
    category: 'Payment Overdue',
    timestamp: '27 Aug 2026, 10:00',
    timeAgo: '1 day ago',
    isRead: true,
    severity: 'Warning',
    targetUrl: '/finance/awaiting-payment',
  },
];

export const INITIAL_FINANCE_DOCUMENTS: FinanceDocument[] = [
  {
    id: 'DOC-INV-0123',
    documentNumber: 'INV-2026-0123',
    category: 'Invoice',
    title: 'Tax Invoice — AutoCare Auckland (AH-P-000123)',
    requestNumber: 'AH-P-000123',
    orderNumber: 'ORD-2026-0089',
    customerName: 'AutoCare Auckland',
    customerId: 'cus_autocare_akl',
    amount: 485.0,
    currency: 'NZD',
    issueDate: '28 Aug 2026',
    dueDate: '28 Aug 2026',
    status: 'Paid',
    fileSize: '142 KB',
    fileFormat: 'PDF',
  },
  {
    id: 'DOC-REC-0123',
    documentNumber: 'REC-2026-0123',
    category: 'Payment Receipt',
    title: 'Payment Confirmation Receipt — PAY-00123',
    requestNumber: 'AH-P-000123',
    paymentNumber: 'PAY-00123',
    orderNumber: 'ORD-2026-0089',
    customerName: 'AutoCare Auckland',
    customerId: 'cus_autocare_akl',
    amount: 485.0,
    currency: 'NZD',
    issueDate: '28 Aug 2026',
    status: 'Issued',
    fileSize: '118 KB',
    fileFormat: 'PDF',
  },
  {
    id: 'DOC-INV-0122',
    documentNumber: 'INV-2026-0122',
    category: 'Invoice',
    title: 'Tax Invoice — Central Motors (AH-P-000122)',
    requestNumber: 'AH-P-000122',
    orderNumber: 'ORD-2026-0088',
    customerName: 'Central Motors',
    customerId: 'cus_central_motors',
    amount: 720.0,
    currency: 'NZD',
    issueDate: '28 Aug 2026',
    dueDate: '29 Aug 2026',
    status: 'Issued',
    fileSize: '145 KB',
    fileFormat: 'PDF',
  },
  {
    id: 'DOC-REF-0089',
    documentNumber: 'REF-2026-0089',
    category: 'Refund Note',
    title: 'Credit & Refund Note — REF-0089 (AutoCare Auckland)',
    requestNumber: 'AH-P-000118',
    paymentNumber: 'PAY-00118',
    customerName: 'AutoCare Auckland',
    customerId: 'cus_autocare_akl',
    amount: 1240.0,
    currency: 'NZD',
    issueDate: '25 Aug 2026',
    status: 'Processed',
    fileSize: '124 KB',
    fileFormat: 'PDF',
  },
  {
    id: 'DOC-CRD-001',
    documentNumber: 'CRD-AGR-2025-01',
    category: 'Credit Statement',
    title: 'Master Trade Credit Facility Agreement ($20,000 Limit)',
    customerName: 'AutoCare Auckland',
    customerId: 'cus_autocare_akl',
    amount: 20000.0,
    currency: 'NZD',
    issueDate: '15 Jan 2025',
    status: 'Issued',
    fileSize: '380 KB',
    fileFormat: 'PDF',
  },
  {
    id: 'DOC-TAX-2026-07',
    documentNumber: 'GST-STMT-2026-07',
    category: 'Tax Certificate',
    title: 'July 2026 Inland Revenue GST Output Summary',
    customerName: 'Autohub NZ Internal Treasury',
    customerId: 'internal',
    amount: 48920.0,
    currency: 'NZD',
    issueDate: '05 Aug 2026',
    status: 'Processed',
    fileSize: '512 KB',
    fileFormat: 'PDF',
  },
];
